#!/usr/bin/env bash
# Launch the DeepSeek-V3.2 REAP NVFP4 SFT run in a 2x2 tmux dashboard:
#   top-left: node 0 training log      top-right: node 1 training log
#   bottom-left: node 0 GPU monitor    bottom-right: node 1 GPU monitor

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MEGATRON_DIR="${MEGATRON_DIR:-"$(cd "$SCRIPT_DIR/../.." && pwd)"}"
cd "$MEGATRON_DIR"

command -v tmux >/dev/null || {
    echo "tmux is required for this launcher" >&2
    exit 1
}

SESSION="${SESSION:-deepseek_sft_real}"
ATTACH="${ATTACH:-1}"
if tmux has-session -t "$SESSION" 2>/dev/null; then
    if [[ "$ATTACH" == "1" ]]; then
        echo "tmux session '$SESSION' already exists; attaching." >&2
        exec tmux attach-session -t "$SESSION"
    fi
    echo "tmux session '$SESSION' already exists; leaving it running." >&2
    exit 0
fi

TS="${TS:-$(date -u +%Y%m%d_%H%M%S)}"
RUN_NAME="${WANDB_EXP_NAME:-deepseek-v32-reap-sft-2b-${TS}}"
LOG_DIR="${LOG_DIR:-"$HOME/logs"}"
LOG0="$LOG_DIR/${RUN_NAME}_node0.log"
LOG1="$LOG_DIR/${RUN_NAME}_node1.log"
mkdir -p "$LOG_DIR"

REMOTE_HOST="${REMOTE_HOST:-sjpat@10.180.0.45}"
SSH_KEY="${SSH_KEY:-$HOME/.ssh/google_compute_engine}"
REMOTE_MEGATRON_DIR="${REMOTE_MEGATRON_DIR:-/home/sjpat/Megatron-LM}"
REMOTE_RUNNER="/tmp/${RUN_NAME}_node1.sh"

MASTER_ADDR="${MASTER_ADDR:-10.200.0.21}"
MASTER_PORT="${MASTER_PORT:-29673}"
TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-"$HOME/.cache/triton/deepseek_v32_reap_sft"}"

# 2x the 1B-token target: 61056 samples * 32768 tokens/sample ~= 2.0007B tokens.
TRAIN_SAMPLES="${TRAIN_SAMPLES:-61056}"
SAVE_INTERVAL="${SAVE_INTERVAL:-100}"
DECODER_FIRST_PIPELINE_NUM_LAYERS="${DECODER_FIRST_PIPELINE_NUM_LAYERS:-16}"
DECODER_LAST_PIPELINE_NUM_LAYERS="${DECODER_LAST_PIPELINE_NUM_LAYERS:-15}"
PIPELINE_MODEL_PARALLEL_LAYOUT="${PIPELINE_MODEL_PARALLEL_LAYOUT:-Et*16|t*15|t*15|t*15L}"
OVERLAP_PARAM_GATHER="${OVERLAP_PARAM_GATHER:-0}"
# Megatron keeps checkpoints whose iteration is divisible by this value and
# deletes the previous non-retained checkpoint after a new save. Pick a value
# above the planned run so only the newest checkpoint remains.
SAVE_RETAIN_INTERVAL="${SAVE_RETAIN_INTERVAL:-100000}"
if (( SAVE_RETAIN_INTERVAL % SAVE_INTERVAL != 0 )); then
    echo "SAVE_RETAIN_INTERVAL=$SAVE_RETAIN_INTERVAL must be divisible by SAVE_INTERVAL=$SAVE_INTERVAL" >&2
    exit 1
fi

cat <<EOF
Run name:      $RUN_NAME
Node 0 log:    $LOG0
Node 1 log:    $LOG1
Train samples: $TRAIN_SAMPLES
Save every:    $SAVE_INTERVAL updates
Retention:     keep latest normal Megatron checkpoint only
ZCC:           ENABLE_ZCC=${ENABLE_ZCC:-0} (last successful probe used 0)
Param gather:  OVERLAP_PARAM_GATHER=$OVERLAP_PARAM_GATHER
PP layout:     ${PIPELINE_MODEL_PARALLEL_LAYOUT:-first=$DECODER_FIRST_PIPELINE_NUM_LAYERS middle=auto last=$DECODER_LAST_PIPELINE_NUM_LAYERS}
StreamBP MoE:  chunk_forward=${STREAMBP_MOE_CHUNK_FORWARD:-0} mlp_chunks=${STREAMBP_MOE_MLP_CHUNKS:-2}
Quant stack:   spinquant=${SPINQUANT:-1} turboquant=${TURBOQUANT:-1} indexcache=${INDEXCACHE:-1}
MoE LB type:   ${MOE_ROUTER_LOAD_BALANCING_TYPE:-seq_aux_loss}
MoE aux coeff: ${MOE_AUX_LOSS_COEFF:-1e-4}
MoE bias upd:  ${MOE_ROUTER_BIAS_UPDATE_RATE:-1e-3}
MoE bias rule: ${MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD:-sign}
ECO:           enabled=${FLASH_ADAMW_ECO:-1} lr_floor=${FLASH_ADAMW_ECO_LR_FLOOR:-base} projection=${FLASH_ADAMW_ECO_PROJECTION:-gain}
Triton cache:  TRITON_CACHE_AUTOTUNING=1 TRITON_CACHE_DIR=$TRITON_CACHE_DIR
EOF

if [[ "${SYNC_REMOTE:-1}" == "1" ]]; then
    mapfile -t SYNC_FILES < <(
        {
            git diff --name-only
            git diff --name-only --cached
            git ls-files --others --exclude-standard
        } | sort -u | grep -Ev '^(artifacts/|\.pytest_cache/|.*__pycache__/|.*\.pyc$)' || true
    )
    if ((${#SYNC_FILES[@]})); then
        echo "Syncing ${#SYNC_FILES[@]} changed/untracked repo files to $REMOTE_HOST ..."
        tar -cf - "${SYNC_FILES[@]}" | ssh -i "$SSH_KEY" "$REMOTE_HOST" \
            "cd '$REMOTE_MEGATRON_DIR' && tar -xf -"
    fi
fi

write_env_block() {
    local node_rank="$1"
    cat <<EOF
export PATH="\$HOME/.local/bin:\$PATH"
export CC="${CC:-/usr/bin/gcc}"
export CXX="${CXX:-/usr/bin/g++}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export TRITON_CACHE_AUTOTUNING="${TRITON_CACHE_AUTOTUNING:-1}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR}"
export NNODES="${NNODES:-2}"
export GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
export MASTER_ADDR="${MASTER_ADDR}"
export MASTER_PORT="${MASTER_PORT}"
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-gpu}"
export NCCL_IB_HCA="${NCCL_IB_HCA:-mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7}"
export NCCL_NVLS_ENABLE="${NCCL_NVLS_ENABLE:-0}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export TP="${TP:-4}"
export PP="${PP:-4}"
export CP="${CP:-1}"
export EP="${EP:-4}"
export ETP="${ETP:-1}"
export DECODER_FIRST_PIPELINE_NUM_LAYERS="${DECODER_FIRST_PIPELINE_NUM_LAYERS}"
export DECODER_LAST_PIPELINE_NUM_LAYERS="${DECODER_LAST_PIPELINE_NUM_LAYERS}"
export PIPELINE_MODEL_PARALLEL_LAYOUT="${PIPELINE_MODEL_PARALLEL_LAYOUT}"
export SEQ_LENGTH="${SEQ_LENGTH:-32768}"
export MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-2}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-32}"
export GRAD_REDUCE_IN_BF16="${GRAD_REDUCE_IN_BF16:-1}"
export DISTRIBUTED_TIMEOUT_MINUTES="${DISTRIBUTED_TIMEOUT_MINUTES:-120}"
export WANDB_ENTITY="${WANDB_ENTITY:-blaise-ai}"
export WANDB_PROJECT="${WANDB_PROJECT:-corsaire-1}"
export WANDB_EXP_NAME="${RUN_NAME}"
export LOG_MEMORY_INTERVAL="${LOG_MEMORY_INTERVAL:-10}"
export LOG_NUM_ZEROS_IN_GRAD="${LOG_NUM_ZEROS_IN_GRAD:-1}"
export TRAIN_SAMPLES="${TRAIN_SAMPLES}"
export SAVE_INTERVAL="${SAVE_INTERVAL}"
export SAVE_RETAIN_INTERVAL="${SAVE_RETAIN_INTERVAL}"
export DISABLE_SAVE="${DISABLE_SAVE:-0}"
export NO_SAVE_OPTIM="${NO_SAVE_OPTIM:-0}"
export NO_SAVE_RNG="${NO_SAVE_RNG:-0}"
export EVAL_INTERVAL="${EVAL_INTERVAL:-100000}"
export LOG_INTERVAL="${LOG_INTERVAL:-1}"
export TENSORBOARD_LOG_INTERVAL="${TENSORBOARD_LOG_INTERVAL:-1}"
export OVERLAP_PARAM_GATHER="${OVERLAP_PARAM_GATHER}"
export USE_STREAMBP="${USE_STREAMBP:-1}"
export STREAMBP_CHUNK_SIZE="${STREAMBP_CHUNK_SIZE:-2048}"
export STREAMBP_MOE_CHUNK_FORWARD="${STREAMBP_MOE_CHUNK_FORWARD:-0}"
export STREAMBP_MOE_MLP_CHUNKS="${STREAMBP_MOE_MLP_CHUNKS:-2}"
export SPINQUANT="${SPINQUANT:-1}"
export TURBOQUANT="${TURBOQUANT:-1}"
export INDEXCACHE="${INDEXCACHE:-1}"
export MOE_ROUTER_LOAD_BALANCING_TYPE="${MOE_ROUTER_LOAD_BALANCING_TYPE:-seq_aux_loss}"
export MOE_AUX_LOSS_COEFF="${MOE_AUX_LOSS_COEFF:-1e-4}"
export MOE_ROUTER_BIAS_UPDATE_RATE="${MOE_ROUTER_BIAS_UPDATE_RATE:-1e-3}"
export MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD="${MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD:-sign}"
export MOE_ROUTER_QUANTILE_BIAS_ITERS="${MOE_ROUTER_QUANTILE_BIAS_ITERS:-5}"
export MOE_ROUTER_QUANTILE_BIAS_SYNC_SCORES="${MOE_ROUTER_QUANTILE_BIAS_SYNC_SCORES:-1}"
export DSA_CHUNK_SIZE="${DSA_CHUNK_SIZE:-2048}"
export DSA_INDEXER_TOPK="${DSA_INDEXER_TOPK:-1024}"
export DSA_INDEXER_LOSS_COEFF="${DSA_INDEXER_LOSS_COEFF:-0.01}"
export MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS="${MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS:-1}"
export MEGATRON_DSA_TRITON_BWD_NUM_WARPS="${MEGATRON_DSA_TRITON_BWD_NUM_WARPS:-2}"
export MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST="${MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST:-1}"
export FLASH_ADAMW_ECO="${FLASH_ADAMW_ECO:-1}"
export FLASH_ADAMW_ECO_LR_FLOOR="${FLASH_ADAMW_ECO_LR_FLOOR:-base}"
export FLASH_ADAMW_ECO_PROJECTION="${FLASH_ADAMW_ECO_PROJECTION:-gain}"
export FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET:-2.0}"
export FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET:-0.25}"
export FLASH_ADAMW_ECO_PROJECTION_STEPS="${FLASH_ADAMW_ECO_PROJECTION_STEPS:-16}"
export FLASH_ADAMW_COMPRESS_STATE_DICT="${FLASH_ADAMW_COMPRESS_STATE_DICT:-1}"
export ENABLE_ZCC="${ENABLE_ZCC:-0}"
export ZCC_RETAIN_LATEST="${ZCC_RETAIN_LATEST:-1}"
export MEGATRON_NUMERIC_DEBUG="${MEGATRON_NUMERIC_DEBUG:-0}"
export MEGATRON_NUMERIC_DEBUG_RANKS="${MEGATRON_NUMERIC_DEBUG_RANKS:-all}"
export MEGATRON_NUMERIC_DEBUG_HOOK_RANKS="${MEGATRON_NUMERIC_DEBUG_HOOK_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS="${MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_DSA_RANKS="${MEGATRON_NUMERIC_DEBUG_DSA_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_RANKS="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_PARAM_RANKS="${MEGATRON_NUMERIC_DEBUG_PARAM_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_START_ITER="${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}"
export MEGATRON_NUMERIC_DEBUG_HOOK_START_ITER="${MEGATRON_NUMERIC_DEBUG_HOOK_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_START_ITER="${MEGATRON_NUMERIC_DEBUG_ROUTER_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_DSA_START_ITER="${MEGATRON_NUMERIC_DEBUG_DSA_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_START_ITER="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_PARAM_START_ITER="${MEGATRON_NUMERIC_DEBUG_PARAM_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_FIRST_N="${MEGATRON_NUMERIC_DEBUG_FIRST_N:-16}"
export MEGATRON_NUMERIC_DEBUG_INTERVAL="${MEGATRON_NUMERIC_DEBUG_INTERVAL:-1}"
export MEGATRON_NUMERIC_DEBUG_MAX_ELEMS="${MEGATRON_NUMERIC_DEBUG_MAX_ELEMS:-262144}"
export MEGATRON_NUMERIC_DEBUG_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_FULL_FINITE:-0}"
export MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT="${MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT:-16}"
export MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS="${MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS:-0}"
export MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS="${MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS:-0}"
export MEGATRON_NUMERIC_DEBUG_HOOK_CLASSES="${MEGATRON_NUMERIC_DEBUG_HOOK_CLASSES:-TransformerLayer,MoELayer,TopKRouter,DSAttention,DSAIndexer,SelfAttention,MLP}"
export MEGATRON_NUMERIC_DEBUG_VERBOSE_HOOKS="${MEGATRON_NUMERIC_DEBUG_VERBOSE_HOOKS:-0}"
export MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE="${MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE:-1}"
export MEGATRON_NUMERIC_DEBUG_PARAM_STATS="${MEGATRON_NUMERIC_DEBUG_PARAM_STATS:-0}"
export MEGATRON_NUMERIC_DEBUG_TOPK="${MEGATRON_NUMERIC_DEBUG_TOPK:-16}"
export MEGATRON_NUMERIC_DEBUG_ROUTER="${MEGATRON_NUMERIC_DEBUG_ROUTER:-0}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE="${MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE:-0}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_LIMIT="${MEGATRON_NUMERIC_DEBUG_ROUTER_LIMIT:-64}"
export MEGATRON_NUMERIC_DEBUG_DSA="${MEGATRON_NUMERIC_DEBUG_DSA:-0}"
export MEGATRON_NUMERIC_DEBUG_DSA_FORCE="${MEGATRON_NUMERIC_DEBUG_DSA_FORCE:-0}"
export MEGATRON_NUMERIC_DEBUG_DSA_LIMIT="${MEGATRON_NUMERIC_DEBUG_DSA_LIMIT:-64}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_LIMIT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_LIMIT:-32}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_ADAM_LIMIT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_ADAM_LIMIT:-32}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_ABORT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_ABORT:-${MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE:-1}}"
export MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS="${MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS:-0}"
export MEGATRON_NUMERIC_DEBUG_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_GRAD_ABORT:-1}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD:-0}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_ABORT:-1}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD:-0}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_FULL_FINITE:-1}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_ABORT:-1}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_STAGE_LIMIT="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_STAGE_LIMIT:-8}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD:-0}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_STAGE_LIMIT="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_STAGE_LIMIT:-4}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_COPY_LIMIT="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_COPY_LIMIT:-8}"
export MEGATRON_NUMERIC_DEBUG_LOSS="${MEGATRON_NUMERIC_DEBUG_LOSS:-0}"
export MEGATRON_NUMERIC_DEBUG_BATCH="${MEGATRON_NUMERIC_DEBUG_BATCH:-0}"
export MEGATRON_FLASH_ADAMW_NVFP4_USE_MAIN_GRAD="${MEGATRON_FLASH_ADAMW_NVFP4_USE_MAIN_GRAD:-0}"
export MEGATRON_GRAD_OWNERSHIP="${MEGATRON_GRAD_OWNERSHIP:-0}"
export MEGATRON_GRAD_OWNERSHIP_RANKS="${MEGATRON_GRAD_OWNERSHIP_RANKS:-all}"
export MEGATRON_GRAD_OWNERSHIP_START_ITER="${MEGATRON_GRAD_OWNERSHIP_START_ITER:-1}"
export MEGATRON_GRAD_OWNERSHIP_FIRST_N="${MEGATRON_GRAD_OWNERSHIP_FIRST_N:-8}"
export MEGATRON_GRAD_OWNERSHIP_INTERVAL="${MEGATRON_GRAD_OWNERSHIP_INTERVAL:-1}"
export MEGATRON_GRAD_OWNERSHIP_TOP_OWNERS="${MEGATRON_GRAD_OWNERSHIP_TOP_OWNERS:-32}"
export MEGATRON_GRAD_OWNERSHIP_TOP_PARAMS="${MEGATRON_GRAD_OWNERSHIP_TOP_PARAMS:-0}"
export NODE_RANK="$node_rank"
mkdir -p "\$TRITON_CACHE_DIR"
EOF
}

NODE0_RUNNER="$LOG_DIR/${RUN_NAME}_node0_runner.sh"
NODE1_LOCAL_RUNNER="$LOG_DIR/${RUN_NAME}_node1_runner.sh"
NODE1_WRAPPER="$LOG_DIR/${RUN_NAME}_node1_wrapper.sh"
LOCAL_MONITOR="$LOG_DIR/${RUN_NAME}_node0_gpu_monitor.sh"
REMOTE_MONITOR="$LOG_DIR/${RUN_NAME}_node1_gpu_monitor.sh"

{
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    write_env_block 0
    echo "cd '$MEGATRON_DIR'"
    echo "echo '[node0] starting $RUN_NAME at '\"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    echo "examples/sft/run_sft_deepseek_nvfp4.sh 2>&1 | tee '$LOG0'"
} > "$NODE0_RUNNER"

{
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    write_env_block 1
    echo "cd '$REMOTE_MEGATRON_DIR'"
    echo "echo '[node1] starting $RUN_NAME at '\"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    echo "examples/sft/run_sft_deepseek_nvfp4.sh"
} > "$NODE1_LOCAL_RUNNER"

chmod +x "$NODE0_RUNNER" "$NODE1_LOCAL_RUNNER"
ssh -i "$SSH_KEY" "$REMOTE_HOST" "cat > '$REMOTE_RUNNER' && chmod +x '$REMOTE_RUNNER'" < "$NODE1_LOCAL_RUNNER"

cat > "$NODE1_WRAPPER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
ssh -tt -i "$SSH_KEY" "$REMOTE_HOST" "bash '$REMOTE_RUNNER'" 2>&1 | tee "$LOG1"
EOF

cat > "$LOCAL_MONITOR" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if command -v nvtop >/dev/null 2>&1; then
    exec nvtop
fi
exec watch -n 2 'nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw --format=csv'
EOF

cat > "$REMOTE_MONITOR" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec ssh -tt -i "$SSH_KEY" "$REMOTE_HOST" 'if command -v nvtop >/dev/null 2>&1; then exec nvtop; fi; exec watch -n 2 "nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw --format=csv"'
EOF

chmod +x "$NODE1_WRAPPER" "$LOCAL_MONITOR" "$REMOTE_MONITOR"

tmux new-session -d -s "$SESSION" -n train
P0="$(tmux display-message -p -t "$SESSION:0" '#{pane_id}')"
tmux send-keys -t "$P0" "bash '$NODE0_RUNNER'; echo; echo '[node0 pane exited]'; exec bash" C-m
tmux split-window -h -t "$P0"
P1="$(tmux display-message -p -t "$SESSION:0" '#{pane_id}')"
tmux send-keys -t "$P1" "bash '$NODE1_WRAPPER'; echo; echo '[node1 pane exited]'; exec bash" C-m
tmux split-window -v -t "$P0" "bash '$LOCAL_MONITOR'"
tmux split-window -v -t "$P1" "bash '$REMOTE_MONITOR'"
tmux select-layout -t "$SESSION:0" tiled >/dev/null
tmux set-option -t "$SESSION" remain-on-exit on >/dev/null
if [[ "$ATTACH" == "1" ]]; then
    tmux attach-session -t "$SESSION"
else
    echo "tmux session '$SESSION' started. Attach with: tmux attach -t '$SESSION'"
fi
