#!/usr/bin/env bash
# Launch the DeepSeek-V3.2 REAP NVFP4 SFT run in a 2x2 tmux dashboard:
#   top-left: node 0 training log      top-right: node 1 training log
#   bottom-left: node 0 GPU monitor    bottom-right: node 1 GPU monitor

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MEGATRON_DIR="${MEGATRON_DIR:-"$(cd "$SCRIPT_DIR/../.." && pwd)"}"
cd "$MEGATRON_DIR"

command -v tmux >/dev/null || {
    echo "tmux is required for this launcher" >&2
    exit 1
}

SESSION="${SESSION:-corsaire_1_research_preview}"
ATTACH="${ATTACH:-1}"
if [[ "${DRY_RUN:-0}" != "1" ]] && tmux has-session -t "$SESSION" 2>/dev/null; then
    if [[ "$ATTACH" == "1" ]]; then
        echo "tmux session '$SESSION' already exists; attaching." >&2
        exec tmux attach-session -t "$SESSION"
    fi
    echo "tmux session '$SESSION' already exists; leaving it running." >&2
    exit 0
fi

TS="${TS:-$(date -u +%Y%m%d_%H%M%S)}"
RUN_NAME="${WANDB_EXP_NAME:-corsaire-1-research-preview}"
LOG_DIR="${LOG_DIR:-"$HOME/logs"}"
LOG0="$LOG_DIR/${RUN_NAME}_node0.log"
LOG1="$LOG_DIR/${RUN_NAME}_node1.log"
mkdir -p "$LOG_DIR"

# Offline is the default for every training run. To intentionally publish live,
# set both WANDB_FORCE_OFFLINE=0 and WANDB_MODE=online at launch.
WANDB_FORCE_OFFLINE="${WANDB_FORCE_OFFLINE:-1}"
if [[ "$WANDB_FORCE_OFFLINE" == "1" ]]; then
    WANDB_MODE=offline
else
    WANDB_MODE="${WANDB_MODE:-offline}"
fi
export WANDB_FORCE_OFFLINE WANDB_MODE

MODEL_ID="${MODEL_ID:-BlaiseAI/DeepSeek-V3.2-REAP-345B-SpinQuant-ActKV-NVFP4}"
TOKENIZER_MODEL="${TOKENIZER_MODEL:-$MODEL_ID}"
LOAD_CKPT="${LOAD_CKPT:-"$HOME/checkpoints/deepseek_v32_reap_spinquant_actkv_nvfp4_megatron"}"
SAVE_CKPT="${SAVE_CKPT:-"$HOME/checkpoints/sft_deepseek_v32_reap_spinquant_actkv_nvfp4"}"

REMOTE_HOST="${REMOTE_HOST:-${NODE1_HOST:-}}"
SSH_KEY="${SSH_KEY:-}"
SSH_OPTS="${SSH_OPTS:-}"
REMOTE_MEGATRON_DIR="${REMOTE_MEGATRON_DIR:-/home/sjpat/Megatron-LM}"
REMOTE_RUNNER="${REMOTE_RUNNER:-/tmp/${RUN_NAME}_node1.sh}"

detect_master_addr() {
    if [[ -n "${MASTER_ADDR_IFNAME:-}" ]] && command -v ip >/dev/null 2>&1; then
        ip -o -4 addr show dev "$MASTER_ADDR_IFNAME" | awk '{split($4, a, "/"); print a[1]; exit}'
        return
    fi
    if command -v ip >/dev/null 2>&1; then
        local probe="${MASTER_ADDR_PROBE:-${REMOTE_HOST#*@}}"
        probe="${probe:-1.1.1.1}"
        ip -4 route get "$probe" 2>/dev/null | awk '{for (i=1; i<=NF; i++) if ($i == "src") {print $(i+1); exit}}'
        return
    fi
    hostname -I | awk '{print $1}'
}

MASTER_ADDR="${MASTER_ADDR:-$(detect_master_addr)}"
MASTER_PORT="${MASTER_PORT:-29673}"
TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-"$HOME/.cache/triton/deepseek_v32_reap_sft"}"
NNODES="${NNODES:-2}"
GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
TP="${TP:-4}"
PP="${PP:-4}"
CP="${CP:-1}"
EP="${EP:-4}"
ETP="${ETP:-1}"
MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-4}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-16}"
SEQ_LENGTH="${SEQ_LENGTH:-16384}"
WORLD_SIZE=$((NNODES * GPUS_PER_NODE))
if (( NNODES != 2 )); then
    echo "This tmux wrapper currently supports exactly 2 nodes; got NNODES=$NNODES." >&2
    echo "Use examples/sft/run_sft_deepseek_nvfp4.sh directly under a scheduler for NNODES != 2." >&2
    exit 1
fi
if [[ -z "$REMOTE_HOST" ]]; then
    echo "REMOTE_HOST or NODE1_HOST must be set for the second node." >&2
    echo "Example: REMOTE_HOST=user@10.0.0.12 MASTER_ADDR=$MASTER_ADDR SESSION=$SESSION examples/sft/launch_sft_deepseek_nvfp4_tmux.sh" >&2
    exit 1
fi
SSH_CMD=(ssh)
if [[ -n "$SSH_KEY" ]]; then
    SSH_CMD+=(-i "$SSH_KEY")
fi
if [[ -n "$SSH_OPTS" ]]; then
    # shellcheck disable=SC2206
    SSH_OPT_LIST=($SSH_OPTS)
    SSH_CMD+=("${SSH_OPT_LIST[@]}")
fi
SSH_TTY_PREFIX="$(printf '%q ' "${SSH_CMD[@]}" -tt "$REMOTE_HOST")"
DENSE_MODEL_PARALLEL_SIZE=$((TP * PP * CP))
EXPERT_MODEL_PIPELINE_PARALLEL_SIZE=$((ETP * EP * PP))
if (( WORLD_SIZE % DENSE_MODEL_PARALLEL_SIZE != 0 )); then
    echo "world_size=$WORLD_SIZE must be divisible by TP*PP*CP=$DENSE_MODEL_PARALLEL_SIZE" >&2
    exit 1
fi
if (( WORLD_SIZE % EXPERT_MODEL_PIPELINE_PARALLEL_SIZE != 0 )); then
    echo "world_size=$WORLD_SIZE must be divisible by ETP*EP*PP=$EXPERT_MODEL_PIPELINE_PARALLEL_SIZE" >&2
    exit 1
fi
DP=$((WORLD_SIZE / DENSE_MODEL_PARALLEL_SIZE))
EXPERT_DP=$((WORLD_SIZE / EXPERT_MODEL_PIPELINE_PARALLEL_SIZE))
if (( GLOBAL_BATCH_SIZE % (MICRO_BATCH_SIZE * DP) != 0 )); then
    echo "GLOBAL_BATCH_SIZE=$GLOBAL_BATCH_SIZE must be divisible by MICRO_BATCH_SIZE*DP=$((MICRO_BATCH_SIZE * DP))" >&2
    exit 1
fi
GRAD_ACCUM_STEPS=$((GLOBAL_BATCH_SIZE / (MICRO_BATCH_SIZE * DP)))

round_samples_to_updates() {
    local raw_samples="$1"
    local batch_size="$2"
    echo $(( ((raw_samples + batch_size - 1) / batch_size) * batch_size ))
}

# Token-target driven default. For 16k contexts, 2B tokens is 954 updates at
# GBS=128; override TRAIN_TOKEN_TARGET or TRAIN_SAMPLES for a different run.
DATA_PATH="${DATA_PATH:-"$HOME/data/sft/blaise-sft-training-mix/blaise-sft-training-mix-full.jsonl"}"
TRAIN_TOKEN_TARGET="${TRAIN_TOKEN_TARGET:-2000000000}"
if [[ -z "${TRAIN_SAMPLES:-}" ]]; then
    RAW_TRAIN_SAMPLES=$(( (TRAIN_TOKEN_TARGET + SEQ_LENGTH - 1) / SEQ_LENGTH ))
    TRAIN_SAMPLES="$(round_samples_to_updates "$RAW_TRAIN_SAMPLES" "$GLOBAL_BATCH_SIZE")"
fi
LR_DECAY_SAMPLES="${LR_DECAY_SAMPLES:-$TRAIN_SAMPLES}"
LR_WARMUP_TOKEN_TARGET="${LR_WARMUP_TOKEN_TARGET:-$((TRAIN_TOKEN_TARGET / 20))}"
if [[ -z "${LR_WARMUP_SAMPLES:-}" ]]; then
    RAW_WARMUP_SAMPLES=$(( (LR_WARMUP_TOKEN_TARGET + SEQ_LENGTH - 1) / SEQ_LENGTH ))
    LR_WARMUP_SAMPLES="$(round_samples_to_updates "$RAW_WARMUP_SAMPLES" "$GLOBAL_BATCH_SIZE")"
fi
TRAIN_UPDATES=$((TRAIN_SAMPLES / GLOBAL_BATCH_SIZE))
TRAIN_TOKENS=$((TRAIN_SAMPLES * SEQ_LENGTH))
WARMUP_TOKENS=$((LR_WARMUP_SAMPLES * SEQ_LENGTH))
SAVE_INTERVAL="${SAVE_INTERVAL:-50}"
DECODER_FIRST_PIPELINE_NUM_LAYERS="${DECODER_FIRST_PIPELINE_NUM_LAYERS:-16}"
DECODER_LAST_PIPELINE_NUM_LAYERS="${DECODER_LAST_PIPELINE_NUM_LAYERS:-15}"
ENABLE_VPP="${ENABLE_VPP:-1}"
if [[ -z "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" ]]; then
    if [[ "$PP" -eq 4 && "$ENABLE_VPP" == "1" ]]; then
        PIPELINE_MODEL_PARALLEL_LAYOUT="Et*5|t*4|t*4|t*3|t*4|t*4|t*4|t*4|t*4|t*4|t*4|t*4|t*3|t*4|t*3|t*3L"
    elif [[ "$PP" -eq 4 ]]; then
        PIPELINE_MODEL_PARALLEL_LAYOUT="Et*16|t*15|t*15|t*15L"
    fi
fi
if [[ -z "${OVERLAP_P2P_COMM_WARMUP_FLUSH:-}" ]]; then
    if [[ "$ENABLE_VPP" == "1" ]]; then
        OVERLAP_P2P_COMM_WARMUP_FLUSH=1
    else
        OVERLAP_P2P_COMM_WARMUP_FLUSH=0
    fi
fi
OVERLAP_PARAM_GATHER="${OVERLAP_PARAM_GATHER:-0}"
# Megatron keeps checkpoints whose iteration is divisible by this value and
# deletes the previous non-retained checkpoint after a new save. Pick a value
# above the planned run so only the newest checkpoint remains.
SAVE_RETAIN_INTERVAL="${SAVE_RETAIN_INTERVAL:-100000}"
if (( SAVE_RETAIN_INTERVAL % SAVE_INTERVAL != 0 )); then
    echo "SAVE_RETAIN_INTERVAL=$SAVE_RETAIN_INTERVAL must be divisible by SAVE_INTERVAL=$SAVE_INTERVAL" >&2
    exit 1
fi
if [[ -z "${STREAMBP_LOCAL_SEQ_LENGTH:-}" ]]; then
    if [[ "${SEQUENCE_PARALLEL:-auto}" == "1" || ( "${SEQUENCE_PARALLEL:-auto}" == "auto" && "$TP" -gt 1 ) ]]; then
        STREAMBP_LOCAL_SEQ_LENGTH=$(( (SEQ_LENGTH + TP - 1) / TP ))
    else
        STREAMBP_LOCAL_SEQ_LENGTH="$SEQ_LENGTH"
    fi
fi
if [[ -z "${STREAMBP_CHUNK_SIZE:-}" ]]; then
    # StreamBP disables itself when chunk_size covers the full local sequence.
    # Default to two chunks per local sequence-parallel shard.
    STREAMBP_CHUNK_SIZE=$(( (STREAMBP_LOCAL_SEQ_LENGTH + 1) / 2 ))
fi
if [[ -z "${MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE:-}" ]]; then
    MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE="$STREAMBP_CHUNK_SIZE"
fi
if [[ -z "${DSA_CHUNK_SIZE:-}" ]]; then
    DSA_CHUNK_SIZE="$STREAMBP_CHUNK_SIZE"
fi
if [[ -z "${APPLY_ROPE_FUSION:-}" ]]; then
    if (( CP > 1 )) || [[ "${MEGATRON_DSA_SPLIT_QK:-1}" == "1" ]]; then
        APPLY_ROPE_FUSION=0
    else
        APPLY_ROPE_FUSION=1
    fi
fi

cat <<EOF
Run name:      $RUN_NAME
Node 0 log:    $LOG0
Node 1 log:    $LOG1
Remote host:   $REMOTE_HOST
Master addr:   $MASTER_ADDR:$MASTER_PORT
Load ckpt:     $LOAD_CKPT
Save ckpt:     $SAVE_CKPT
Train samples: $TRAIN_SAMPLES
Train tokens:  target=$TRAIN_TOKEN_TARGET effective=$TRAIN_TOKENS updates=$TRAIN_UPDATES
Seq length:    $SEQ_LENGTH
Warmup:        samples=$LR_WARMUP_SAMPLES tokens=$WARMUP_TOKENS
World shape:   nodes=$NNODES gpus_per_node=$GPUS_PER_NODE world=$WORLD_SIZE
Parallelism:   TP=$TP PP=$PP CP=$CP DP=$DP EP=$EP ETP=$ETP expert_DP=$EXPERT_DP
Batches:       MBS=$MICRO_BATCH_SIZE GBS=$GLOBAL_BATCH_SIZE grad_accum=$GRAD_ACCUM_STEPS
Save every:    $SAVE_INTERVAL updates
Retention:     keep latest normal Megatron checkpoint only
ZCC:           ENABLE_ZCC=${ENABLE_ZCC:-1} durable_interval=${ZCC_DURABLE_INTERVAL:-50} retain_latest=${ZCC_RETAIN_LATEST:-1} fuse_state_buffer=${MEGATRON_FLASH_FUSE_STATE_BUFFER:-0}
Param gather:  OVERLAP_PARAM_GATHER=$OVERLAP_PARAM_GATHER
EP overlap:    overlap_moe=${OVERLAP_MOE_EXPERT_PARALLEL_COMM:-0} high_priority_a2a=${HIGH_PRIORITY_A2A_COMM_STREAM:-0} p2p_warmup_flush=${OVERLAP_P2P_COMM_WARMUP_FLUSH} p2p_prewarm=${MEGATRON_PREWARM_PIPELINE_P2P:-1} early_attn_release=${EP_OVERLAP_EARLY_ATTN_MEMORY_RELEASE:-0} delay_wgrad=${DELAY_WGRAD_COMPUTE:-0}
PP layout:     vpp=${ENABLE_VPP} ${PIPELINE_MODEL_PARALLEL_LAYOUT:-first=$DECODER_FIRST_PIPELINE_NUM_LAYERS middle=auto last=$DECODER_LAST_PIPELINE_NUM_LAYERS}
Layer StreamBP: USE_STREAMBP=${USE_STREAMBP:-0} local_seq=$STREAMBP_LOCAL_SEQ_LENGTH chunk=$STREAMBP_CHUNK_SIZE
StreamBP LM:   fused_lce=${MEGATRON_STREAMBP_FUSED_LCE:-0} decoupled_lce=${MEGATRON_CHUNKED_LM_HEAD_LOSS:-0} logits_chunk=${STREAMBP_LOGITS_CHUNK_SIZE:-8192} lce_sp_tile=${MEGATRON_STREAMBP_FUSED_LCE_SP_TILE_SIZE:-1024} lce_fwd_split=${LCE_FWD_VOCAB_SPLIT_SIZE:-8192} lce_bwd_split=${LCE_BWD_VOCAB_SPLIT_SIZE:-8192}
StreamBP MoE:  chunk_forward=${STREAMBP_MOE_CHUNK_FORWARD:-0} mlp_chunks=${STREAMBP_MOE_MLP_CHUNKS:-1} bwd_mlp_chunks=${STREAMBP_MOE_MLP_BACKWARD_CHUNKS:-1} attn_bwd_chunk=${MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE} split_mlp_attn_bwd=${MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD:-0} skip_pp=${MEGATRON_STREAMBP_SKIP_PP_RANKS-}
Replay offload: keep_storages="${MEGATRON_FINE_OFFLOAD_STREAMBP_REPLAY_KEEP_STORAGES:-core_attn attn_proj expert_fc1}" pin=${MEGATRON_FINE_OFFLOAD_PIN_MEMORY:-auto} pinned_max_mb=${MEGATRON_FINE_OFFLOAD_PINNED_MAX_MB:-64} strided_copy_chunk_mb=${MEGATRON_FINE_OFFLOAD_STRIDED_COPY_CHUNK_MB:-128}
Pipeline queue offload: enabled=${MEGATRON_PIPELINE_QUEUE_OFFLOAD:-0} min_mb=${MEGATRON_PIPELINE_QUEUE_OFFLOAD_MIN_MB:-1} pin=${MEGATRON_PIPELINE_QUEUE_OFFLOAD_PIN_MEMORY:-auto}
Replay saved tensors: offload=${MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD:-0} min_mb=${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MIN_MB:-16} free_mb=${MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB:-0} max_tensors=${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS:-0}
StreamBP hidden save: host=${MEGATRON_STREAMBP_HOST_SAVE_HIDDEN:-0} pin=${MEGATRON_STREAMBP_HOST_SAVE_PIN_MEMORY:-auto}
MoE replay trim: enabled=${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE:-0} free_mb=${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_FREE_MB:-16384} cached_mb=${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHED_MB:-2048} sync=${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_SYNC:-0}
Replay TE save: quantized_inputs=${MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS:-0} release_mlp_input=${MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD:-0}
TE grouped:    fuse_wgrad_accum=${MEGATRON_TE_GROUPED_LINEAR_FUSE_WGRAD_ACCUM:-1} pre_input_trim=${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM:-1} pre_output_trim=${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM:-1} alloc_audit=${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG:-0}:${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_RANKS:-0,7} retain_reentrant_tensor_objects=${MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD:-0}
MoE unpadding trim: enabled=${MEGATRON_MOE_UNPADDING_TRIM_CACHE:-0} free_mb=${MEGATRON_MOE_UNPADDING_TRIM_FREE_MB:-16384} cached_mb=${MEGATRON_MOE_UNPADDING_TRIM_CACHED_MB:-2048}
MoE fc1 trim: enabled=${MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE:-0} free_mb=${MEGATRON_MOE_EXPERT_FC1_TRIM_FREE_MB:-16384} reserve_mb=${MEGATRON_MOE_EXPERT_FC1_TRIM_RESERVE_MB:-2048} cached_mb=${MEGATRON_MOE_EXPERT_FC1_TRIM_CACHED_MB:-2048} sync=${MEGATRON_MOE_EXPERT_FC1_TRIM_SYNC:-0} gc=${MEGATRON_MOE_EXPERT_FC1_TRIM_GC:-0}
MoE fc2 trim: enabled=${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE:-0} free_mb=${MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB:-8192} cached_mb=${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB:-2048} sync=${MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC:-0}
MoE sort trim: enabled=${MEGATRON_MOE_SORT_TRIM_CACHE:-0} free_mb=${MEGATRON_MOE_SORT_TRIM_FREE_MB:-16384} safety_mb=${MEGATRON_MOE_SORT_TRIM_SAFETY_MB:-1024} cached_mb=${MEGATRON_MOE_SORT_TRIM_CACHED_MB:-2048} sync=${MEGATRON_MOE_SORT_TRIM_SYNC:-0}
MoE combine:  reduce_scatter_dtype=${MEGATRON_MOE_COMBINE_REDUCE_SCATTER_DTYPE:-input}
MLA key trim: enabled=${MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT:-0} margin_mb=${MEGATRON_MLA_KEY_CAT_TRIM_MARGIN_MB:-1024} cached_mb=${MEGATRON_MLA_KEY_CAT_TRIM_CACHED_MB:-512}
Tensor audit:  enabled=${MEGATRON_TENSOR_AUDIT:-0} ranks=${MEGATRON_TENSOR_AUDIT_RANKS:-all} filter=${MEGATRON_TENSOR_AUDIT_FILTER:-moe_expert} limit=${MEGATRON_TENSOR_AUDIT_LIMIT:-128}
Activation offload: disabled
Temp offload:  disabled
Pipeline progress: enabled=${MEGATRON_PIPELINE_PROGRESS_LOG:-0} interval=${MEGATRON_PIPELINE_PROGRESS_INTERVAL:-16} tp_ranks=${MEGATRON_PIPELINE_PROGRESS_TP_RANKS:-0}
MoE stage log: enabled=${MEGATRON_MOE_STAGE_PROGRESS_LOG:-0} ranks=${MEGATRON_MOE_STAGE_PROGRESS_RANKS:-0} sync=${MEGATRON_MOE_STAGE_PROGRESS_SYNC:-0}
Activation ECO: enabled=${NVFP4_ACTIVATION_ECO:-0} modules="${NVFP4_ACTIVATION_ECO_MODULES:-all}" recompute_only=${NVFP4_ACTIVATION_ECO_RECOMPUTE_ONLY:-1} backend=${NVFP4_ACTIVATION_ECO_QUANTIZER_BACKEND:-te} correction_dtype=${NVFP4_ACTIVATION_ECO_CORRECTION_DTYPE:-bf16} correction_tiles=${MEGATRON_ACT_ECO_CORRECTION_ROW_CHUNK:-2048}x${MEGATRON_ACT_ECO_CORRECTION_OUT_CHUNK:-2048}x${MEGATRON_ACT_ECO_CORRECTION_IN_CHUNK:-0}
Quant stack:   spinquant=${SPINQUANT:-1} higgs=${USE_HIGGS:-1} turboquant=${TURBOQUANT:-0} indexcache=${INDEXCACHE:-1} indexcache_hisa=${DSA_INDEXCACHE_HISA:-1}
RoPE fusion:   apply=${APPLY_ROPE_FUSION:-1}
DSA fused:     triton=${MEGATRON_DSA_TRITON:-1} triton_indexer=${MEGATRON_DSA_TRITON_INDEXER:-1} split_qk=${MEGATRON_DSA_SPLIT_QK:-1} streaming_topk=${MEGATRON_DSA_STREAMING_INDEXER_TOPK:-1} sort_topk=${MEGATRON_DSA_SORT_TOPK_INDICES:-0} compact_topk=${MEGATRON_DSA_COMPACT_TOPK_INDICES:-1} stream_triton_chunks=${MEGATRON_DSA_STREAM_TRITON_ATTENTION_CHUNKS:-1} validate_topk=${MEGATRON_DSA_VALIDATE_TOPK_INDICES:-0} hisa_slot_group=${MEGATRON_HISA_CANDIDATE_SLOT_GROUP:-8} hisa_temp_mb=${MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB:-0} hisa_free_reserve_mb=${MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB:-0} hisa_candidate_trim=${MEGATRON_HISA_CANDIDATE_TRIM_CACHE:-0} hisa_compact_candidate=${MEGATRON_HISA_COMPACT_CANDIDATE_TOPK:-1} hisa_selector_backend=${MEGATRON_HISA_SELECTOR_BACKEND:-megakernel} hisa_selector_cuda=${MEGATRON_HISA_SELECTOR_CUDA:-1} hisa_streaming_scratch=${MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH:-0} hisa_selector_row_chunk=${MEGATRON_HISA_SELECTOR_ROW_CHUNK:-512} hisa_bmm_tc=${MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES:-1} hisa_bmm_cublasdx=${MEGATRON_HISA_BMM_CUBLASDX_REFINE:-1} hisa_assume_sorted=${MEGATRON_HISA_ASSUME_SORTED_POSITIONS:-1} hisa_dense_fallback=${MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT:-0} hisa_fused_loss=${MEGATRON_HISA_FUSED_INDEXER_LOSS:-1} teacher_score_scratch=${MEGATRON_DSA_TEACHER_SCORE_SCRATCH:-1} bwd_score_scratch=${MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH:-1} dsa_bwd_trim=${MEGATRON_DSA_BACKWARD_TRIM_CACHE:-0} dsa_bwd_trim_sync=${MEGATRON_DSA_BACKWARD_TRIM_SYNC:-0} split_qk_reentrant_kv=${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD:-0} split_qk_reentrant_chunk=${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK:-32768} split_qk_defer_query=${MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS:-0} split_qk_pack_kv=${MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD:-1} hisa_target_triton=${MEGATRON_HISA_TARGET_TRITON:-1} hisa_target_block_k=${MEGATRON_HISA_TARGET_BLOCK_K:-64} selected_bwd_head_group=${MEGATRON_HISA_SELECTED_SCORE_BWD_HEAD_GROUP:-8} selected_bwd_warp_grouped=${MEGATRON_HISA_SELECTED_SCORE_BWD_WARP_GROUPED:-1} selected_bwd_tile=${MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N:-32} bwd_block_k=${MEGATRON_DSA_TRITON_BLOCK_K_BWD:-32} bwd_warps=${MEGATRON_DSA_TRITON_BWD_NUM_WARPS:-2} cuda_split_qk_row=${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD:-1} cuda_split_qk_row_query=${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD:-1} cuda_split_qk_warps=${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS:-8} cuda_kv_bwd=${MEGATRON_DSA_CUDA_KV_BWD:-0} cuda_kv_tile=${MEGATRON_DSA_CUDA_KV_BWD_TILE_Q:-2}x${MEGATRON_DSA_CUDA_KV_BWD_TILE_K:-4}
DSA top-k:     indexer=${DSA_INDEXER_TOPK:-1024} indexcache_block=${DSA_INDEXCACHE_HISA_BLOCK_TOPK:-64} chunk=${DSA_CHUNK_SIZE}
DSA SP q trim: enabled=${MEGATRON_DSA_SP_Q_PROJ_TRIM_CACHE:-0} safety_mb=${MEGATRON_DSA_SP_Q_PROJ_TRIM_SAFETY_MB:-1024} cached_mb=${MEGATRON_DSA_SP_Q_PROJ_TRIM_CACHED_MB:-512} sync=${MEGATRON_DSA_SP_Q_PROJ_TRIM_SYNC:-0}
DSA RoPE:      indexer_fusion=${MEGATRON_DSA_INDEXER_ROPE_FUSION:-1} inplace=${MEGATRON_DSA_INDEXER_ROPE_INPLACE:-1} torch_k_norm=${MEGATRON_DSA_INDEXER_TORCH_K_NORM:-1}
MoE local:     compact_deepep_permute=${MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE:-1} compact_backend=${MEGATRON_DEEPEP_COMPACT_BACKEND:-rowcuda} expert_major_dispatch=${MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH:-1} expert_major_combine=${MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE:-0} compact_cuda_unpermute=${MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE:-1} compact_stable_map=${MEGATRON_DEEPEP_COMPACT_STABLE_MAP:-0} compact_row_chunk=${MEGATRON_DEEPEP_COMPACT_ROW_CHUNK:-131072} weighted_swiglu=${MEGATRON_WEIGHTED_SWIGLU_FUSER:-triton}
DeepEP combine cfg: deepep_sms=${MEGATRON_DEEPEP_NUM_SMS:-24} group_size=${MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE:-8} sms=${MEGATRON_DEEPEP_COMBINE_NUM_SMS:-24} nvl_send=${MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS:-16} nvl_recv=${MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS:-256} rdma_send=${MEGATRON_DEEPEP_COMBINE_RDMA_SEND_TOKENS:-default} rdma_recv=${MEGATRON_DEEPEP_COMBINE_RDMA_RECV_TOKENS:-default}
MoE LB type:   ${MOE_ROUTER_LOAD_BALANCING_TYPE:-seq_aux_loss}
MoE padding:   quantization=${MOE_ROUTER_PADDING_FOR_QUANTIZATION:-0}
MoE aux coeff: ${MOE_AUX_LOSS_COEFF:-1e-4}
MoE bias upd:  ${MOE_ROUTER_BIAS_UPDATE_RATE:-1e-3}
MoE bias rule: ${MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD:-sign} application=${MOE_ROUTER_QUANTILE_BIAS_APPLICATION:-delayed} warmup_steps=${MOE_ROUTER_QUANTILE_BIAS_WARMUP_STEPS:-0}
MoE router freeze: params=${MEGATRON_FREEZE_ROUTER:-1} expert_bias=${MEGATRON_FREEZE_ROUTER_EXPERT_BIAS:-${MEGATRON_FREEZE_ROUTER:-1}}
Optimizer ECO: flash_adamw=${FLASH_ADAMW_ECO:-1} fsdp_inject=${FLASH_ADAMW_FSDP_ECO_INJECT:-0} lr_floor=${FLASH_ADAMW_ECO_LR_FLOOR:-base} projection=${FLASH_ADAMW_ECO_PROJECTION:-gain}
Triton cache:  TRITON_CACHE_AUTOTUNING=1 TRITON_CACHE_DIR=$TRITON_CACHE_DIR
DeepGEMM JIT:  DG_JIT_CACHE_DIR=${DG_JIT_CACHE_DIR:-$HOME/.cache/deep_gemm/deepseek_v32_reap_sft}
Allocator:     PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}
HF upload:     enabled=${HF_UPLOAD_CHECKPOINTS:-1} interval=${HF_UPLOAD_INTERVAL:-500} repo=${HF_REPO_ID:-BlaiseAI/corsaire-1-research-preview} retain=${HF_UPLOAD_RETAIN:-1}
W&B:           entity=${WANDB_ENTITY:-blaise-ai} project=${WANDB_PROJECT:-corsaire-1} run=$RUN_NAME mode=$WANDB_MODE force_offline=$WANDB_FORCE_OFFLINE
EOF

if [[ "${DRY_RUN:-0}" == "1" ]]; then
    echo "DRY_RUN=1 set; not syncing, creating tmux panes, or launching training."
    exit 0
fi

sync_load_checkpoint_metadata() {
    local tracker="$LOAD_CKPT/latest_checkpointed_iteration.txt"
    if [[ ! -f "$tracker" ]]; then
        echo "missing load checkpoint tracker: $tracker" >&2
        exit 1
    fi

    local iteration
    iteration="$(<"$tracker")"
    local iter_dir
    if [[ "$iteration" == "release" ]]; then
        iter_dir="release"
    else
        iter_dir="$(printf 'iter_%07d' "$iteration")"
    fi

    local rel_files=(
        "latest_checkpointed_iteration.txt"
        "latest_train_state.pt"
        "$iter_dir/.metadata"
        "$iter_dir/common.pt"
        "$iter_dir/metadata.json"
        "$iter_dir/train_state.pt"
        "$iter_dir/run_config.yaml"
    )

    local rel
    for rel in "${rel_files[@]}"; do
        if [[ ! -f "$LOAD_CKPT/$rel" ]]; then
            echo "missing load checkpoint metadata file: $LOAD_CKPT/$rel" >&2
            exit 1
        fi
    done

    echo "Syncing load checkpoint metadata/common files to $REMOTE_HOST ..."
    "${SSH_CMD[@]}" "$REMOTE_HOST" "mkdir -p '$LOAD_CKPT/$iter_dir'"
    tar -C "$LOAD_CKPT" -cf - "${rel_files[@]}" | "${SSH_CMD[@]}" "$REMOTE_HOST" \
        "tar -C '$LOAD_CKPT' -xf -"
    "${SSH_CMD[@]}" "$REMOTE_HOST" \
        "test -f '$LOAD_CKPT/latest_checkpointed_iteration.txt' && test -f '$LOAD_CKPT/$iter_dir/.metadata' && test -f '$LOAD_CKPT/$iter_dir/common.pt'"
}

if [[ "${SYNC_LOAD_CKPT_METADATA:-1}" == "1" ]]; then
    sync_load_checkpoint_metadata
fi

if [[ "${SYNC_REMOTE:-1}" == "1" ]]; then
    UPSTREAM_REF=""
    CURRENT_BRANCH="$(git symbolic-ref --quiet --short HEAD 2>/dev/null || true)"
    if [[ -n "$CURRENT_BRANCH" ]] && git rev-parse --verify --quiet "origin/$CURRENT_BRANCH" >/dev/null; then
        UPSTREAM_REF="origin/$CURRENT_BRANCH"
    elif git rev-parse --verify --quiet origin/dev-sft >/dev/null; then
        UPSTREAM_REF="origin/dev-sft"
    fi
    mapfile -t SYNC_FILES < <(
        {
            if [[ -n "$UPSTREAM_REF" ]]; then
                git diff --name-only "$UPSTREAM_REF..HEAD"
            fi
            git diff --name-only
            git diff --name-only --cached
            git ls-files --others --exclude-standard
        } | sort -u | grep -Ev '^(artifacts/|\.pytest_cache/|.*__pycache__/|.*\.pyc$)' || true
    )
    if ((${#SYNC_FILES[@]})); then
        echo "Syncing ${#SYNC_FILES[@]} changed/untracked repo files to $REMOTE_HOST ..."
        tar -cf - "${SYNC_FILES[@]}" | "${SSH_CMD[@]}" "$REMOTE_HOST" \
            "cd '$REMOTE_MEGATRON_DIR' && tar -xf -"
    fi
fi

if [[ "${ENABLE_TRAINING_DEBUG:-0}" != "1" ]]; then
    export MEGATRON_ACT_ECO_DEBUG_SYNC=0
    export MEGATRON_ACT_ECO_DEBUG_VERBOSE=0
    export MEGATRON_STREAMBP_DEBUG_SYNC=0
    export MEGATRON_STREAMBP_DEBUG_VERBOSE=0
    export MEGATRON_DDP_GRAD_DEBUG_SYNC=0
    export MEGATRON_DDP_GRAD_DEBUG_VERBOSE=0
    export MEGATRON_NUMERIC_DEBUG=0
    export MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS=0
    export MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS=0
    export MEGATRON_NUMERIC_DEBUG_PARAM_STATS=0
    export MEGATRON_NUMERIC_DEBUG_ROUTER=0
    export MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE=0
    export MEGATRON_NUMERIC_DEBUG_DSA=0
    export MEGATRON_NUMERIC_DEBUG_DSA_FORCE=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST=0
    export MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS=0
    export MEGATRON_NUMERIC_DEBUG_DDP_GRAD=0
    export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD=0
    export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD=0
    export MEGATRON_NUMERIC_DEBUG_LOSS=0
    export MEGATRON_NUMERIC_DEBUG_BATCH=0
    export MEGATRON_GRAD_OWNERSHIP=0
fi

write_env_block() {
    local node_rank="$1"
    cat <<EOF
export PATH="\$HOME/.local/bin:\$PATH"
export CC="${CC:-/usr/bin/gcc}"
export CXX="${CXX:-/usr/bin/g++}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
export MEGATRON_TEMP_ACTIVATION_OFFLOAD=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_MODULES=""
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_MIN_MB=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_EMPTY_CACHE=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_NON_BLOCKING=0
export MEGATRON_MOE_COMBINE_REDUCE_SCATTER_DTYPE="${MEGATRON_MOE_COMBINE_REDUCE_SCATTER_DTYPE:-input}"
if [[ -n "${CUDA_LAUNCH_BLOCKING:-}" ]]; then
    export CUDA_LAUNCH_BLOCKING="${CUDA_LAUNCH_BLOCKING:-}"
fi
export TRITON_CACHE_AUTOTUNING="${TRITON_CACHE_AUTOTUNING:-1}"
export TRITON_CACHE_DIR="${TRITON_CACHE_DIR}"
export DG_JIT_CACHE_DIR="\${DG_JIT_CACHE_DIR:-\$HOME/.cache/deep_gemm/deepseek_v32_reap_sft}"
mkdir -p "\$DG_JIT_CACHE_DIR"
export MODEL_ID="${MODEL_ID}"
export TOKENIZER_MODEL="${TOKENIZER_MODEL}"
export LOAD_CKPT="${LOAD_CKPT}"
export SAVE_CKPT="${SAVE_CKPT}"
export DATA_PATH="${DATA_PATH}"
export NNODES="${NNODES}"
export GPUS_PER_NODE="${GPUS_PER_NODE}"
export MASTER_ADDR="${MASTER_ADDR}"
export MASTER_PORT="${MASTER_PORT}"
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-gpu}"
export NCCL_IB_HCA="${NCCL_IB_HCA:-mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7}"
export NCCL_NVLS_ENABLE="${NCCL_NVLS_ENABLE:-0}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export TP="${TP}"
export PP="${PP}"
export CP="${CP}"
export EP="${EP}"
export ETP="${ETP}"
export DECODER_FIRST_PIPELINE_NUM_LAYERS="${DECODER_FIRST_PIPELINE_NUM_LAYERS}"
export DECODER_LAST_PIPELINE_NUM_LAYERS="${DECODER_LAST_PIPELINE_NUM_LAYERS}"
export ENABLE_VPP="${ENABLE_VPP}"
export PIPELINE_MODEL_PARALLEL_LAYOUT="${PIPELINE_MODEL_PARALLEL_LAYOUT}"
export PIPELINE_PARALLEL_SCHEDULE="${PIPELINE_PARALLEL_SCHEDULE:-}"
export NUM_LAYERS_PER_VIRTUAL_PIPELINE_STAGE="${NUM_LAYERS_PER_VIRTUAL_PIPELINE_STAGE:-}"
export NUM_VIRTUAL_STAGES_PER_PIPELINE_RANK="${NUM_VIRTUAL_STAGES_PER_PIPELINE_RANK:-}"
export SEQ_LENGTH="${SEQ_LENGTH}"
export MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE}"
export GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE}"
export GRAD_REDUCE_IN_BF16="${GRAD_REDUCE_IN_BF16:-1}"
export DISTRIBUTED_TIMEOUT_MINUTES="${DISTRIBUTED_TIMEOUT_MINUTES:-120}"
export WANDB_ENTITY="${WANDB_ENTITY:-blaise-ai}"
export WANDB_PROJECT="${WANDB_PROJECT:-corsaire-1}"
export WANDB_EXP_NAME="${RUN_NAME}"
export WANDB_FORCE_OFFLINE="${WANDB_FORCE_OFFLINE}"
export WANDB_MODE="${WANDB_MODE}"
export LOG_MEMORY_INTERVAL="${LOG_MEMORY_INTERVAL:-10}"
export LOG_NUM_ZEROS_IN_GRAD="${LOG_NUM_ZEROS_IN_GRAD:-1}"
export TRAIN_SAMPLES="${TRAIN_SAMPLES}"
export TRAIN_TOKEN_TARGET="${TRAIN_TOKEN_TARGET}"
export LR_DECAY_SAMPLES="${LR_DECAY_SAMPLES}"
export LR_WARMUP_SAMPLES="${LR_WARMUP_SAMPLES}"
export LR_WARMUP_TOKEN_TARGET="${LR_WARMUP_TOKEN_TARGET}"
export NUM_WORKERS="${NUM_WORKERS:-8}"
export SAVE_INTERVAL="${SAVE_INTERVAL}"
export SAVE_RETAIN_INTERVAL="${SAVE_RETAIN_INTERVAL}"
export DISABLE_SAVE="${DISABLE_SAVE:-0}"
export NO_SAVE_OPTIM="${NO_SAVE_OPTIM:-0}"
export NO_SAVE_RNG="${NO_SAVE_RNG:-0}"
export EVAL_INTERVAL="${EVAL_INTERVAL:-100000}"
export LOG_INTERVAL="${LOG_INTERVAL:-1}"
export TENSORBOARD_LOG_INTERVAL="${TENSORBOARD_LOG_INTERVAL:-1}"
export OVERLAP_PARAM_GATHER="${OVERLAP_PARAM_GATHER}"
export OVERLAP_MOE_EXPERT_PARALLEL_COMM="${OVERLAP_MOE_EXPERT_PARALLEL_COMM:-0}"
export HIGH_PRIORITY_A2A_COMM_STREAM="${HIGH_PRIORITY_A2A_COMM_STREAM:-0}"
export OVERLAP_P2P_COMM_WARMUP_FLUSH="${OVERLAP_P2P_COMM_WARMUP_FLUSH}"
export EP_OVERLAP_EARLY_ATTN_MEMORY_RELEASE="${EP_OVERLAP_EARLY_ATTN_MEMORY_RELEASE:-0}"
export DELAY_WGRAD_COMPUTE="${DELAY_WGRAD_COMPUTE:-0}"
export OVERLAP_DISPATCH_BACKWARD_WITH_EXPERTS_WGRAD="${OVERLAP_DISPATCH_BACKWARD_WITH_EXPERTS_WGRAD:-0}"
export MOE_HYBRIDEP_NUM_SMS_PREPROCESSING="${MOE_HYBRIDEP_NUM_SMS_PREPROCESSING:-}"
export USE_STREAMBP="${USE_STREAMBP:-0}"
export STREAMBP_CHUNK_SIZE="${STREAMBP_CHUNK_SIZE}"
export STREAMBP_LOCAL_SEQ_LENGTH="${STREAMBP_LOCAL_SEQ_LENGTH}"
export STREAMBP_LOGITS_CHUNK_SIZE="${STREAMBP_LOGITS_CHUNK_SIZE:-8192}"
export MEGATRON_STREAMBP_FUSED_LCE="${MEGATRON_STREAMBP_FUSED_LCE:-0}"
export MEGATRON_CHUNKED_LM_HEAD_LOSS="${MEGATRON_CHUNKED_LM_HEAD_LOSS:-0}"
export MEGATRON_STREAMBP_FUSED_LCE_SP_TILE_SIZE="${MEGATRON_STREAMBP_FUSED_LCE_SP_TILE_SIZE:-1024}"
export MEGATRON_STREAMBP_SKIP_PP_RANKS="${MEGATRON_STREAMBP_SKIP_PP_RANKS-}"
export STREAMBP_MOE_CHUNK_FORWARD="${STREAMBP_MOE_CHUNK_FORWARD:-0}"
export STREAMBP_MOE_MLP_CHUNKS="${STREAMBP_MOE_MLP_CHUNKS:-1}"
export STREAMBP_MOE_MLP_BACKWARD_CHUNKS="${STREAMBP_MOE_MLP_BACKWARD_CHUNKS:-1}"
export MOE_TOKEN_DISPATCHER_TYPE="${MOE_TOKEN_DISPATCHER_TYPE:-flex}"
export MOE_FLEX_DISPATCHER_BACKEND="${MOE_FLEX_DISPATCHER_BACKEND:-deepep}"
export MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD="${MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD:-0}"
export MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE="${MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE}"
export MOE_ROUTER_PADDING_FOR_QUANTIZATION="${MOE_ROUTER_PADDING_FOR_QUANTIZATION:-0}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE:-0}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_SYNC="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_SYNC:-0}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_FREE_MB="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_FREE_MB:-16384}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHED_MB="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHED_MB:-2048}"
export MEGATRON_STREAMBP_MOE_REPLAY_FORCE_TRIM="${MEGATRON_STREAMBP_MOE_REPLAY_FORCE_TRIM:-0}"
export MEGATRON_STREAMBP_SUPPRESS_TEMP_OFFLOAD_MODULES="${MEGATRON_STREAMBP_SUPPRESS_TEMP_OFFLOAD_MODULES:-moe_shared}"
export MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS="${MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS:-0}"
export MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD="${MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD:-0}"
export MEGATRON_STREAMBP_HOST_SAVE_HIDDEN="${MEGATRON_STREAMBP_HOST_SAVE_HIDDEN:-0}"
export MEGATRON_STREAMBP_HOST_SAVE_PIN_MEMORY="${MEGATRON_STREAMBP_HOST_SAVE_PIN_MEMORY:-auto}"
export MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD="${MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD:-0}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_MIN_MB="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MIN_MB:-16}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB:-0}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS:-0}"
export MEGATRON_TE_GROUPED_LINEAR_FUSE_WGRAD_ACCUM="${MEGATRON_TE_GROUPED_LINEAR_FUSE_WGRAD_ACCUM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_FREE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_FREE_MB:-2048}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_RESERVE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_RESERVE_MB:-512}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CACHED_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CACHED_MB:-256}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC:-0}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_FREE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_FREE_MB:-2048}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_RESERVE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_RESERVE_MB:-1024}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CACHED_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CACHED_MB:-256}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC:-0}"
export MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG="${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG:-0}"
export MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_RANKS="${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_RANKS:-0,7}"
export MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD="${MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD:-0}"
export MEGATRON_MOE_UNPADDING_TRIM_CACHE="${MEGATRON_MOE_UNPADDING_TRIM_CACHE:-0}"
export MEGATRON_MOE_UNPADDING_TRIM_FREE_MB="${MEGATRON_MOE_UNPADDING_TRIM_FREE_MB:-16384}"
export MEGATRON_MOE_UNPADDING_TRIM_CACHED_MB="${MEGATRON_MOE_UNPADDING_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE="${MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE:-0}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_FREE_MB="${MEGATRON_MOE_EXPERT_FC1_TRIM_FREE_MB:-16384}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_RESERVE_MB="${MEGATRON_MOE_EXPERT_FC1_TRIM_RESERVE_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_CACHED_MB="${MEGATRON_MOE_EXPERT_FC1_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_SYNC="${MEGATRON_MOE_EXPERT_FC1_TRIM_SYNC:-0}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_GC="${MEGATRON_MOE_EXPERT_FC1_TRIM_GC:-0}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE="${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE:-0}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB="${MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB:-8192}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB="${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC="${MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC:-0}"
export MEGATRON_MOE_SORT_TRIM_CACHE="${MEGATRON_MOE_SORT_TRIM_CACHE:-0}"
export MEGATRON_MOE_SORT_TRIM_FREE_MB="${MEGATRON_MOE_SORT_TRIM_FREE_MB:-16384}"
export MEGATRON_MOE_SORT_TRIM_SAFETY_MB="${MEGATRON_MOE_SORT_TRIM_SAFETY_MB:-1024}"
export MEGATRON_MOE_SORT_TRIM_CACHED_MB="${MEGATRON_MOE_SORT_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_SORT_TRIM_SYNC="${MEGATRON_MOE_SORT_TRIM_SYNC:-0}"
export MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT="${MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT:-0}"
export MEGATRON_MLA_KEY_CAT_TRIM_MARGIN_MB="${MEGATRON_MLA_KEY_CAT_TRIM_MARGIN_MB:-1024}"
export MEGATRON_MLA_KEY_CAT_TRIM_CACHED_MB="${MEGATRON_MLA_KEY_CAT_TRIM_CACHED_MB:-512}"
export MEGATRON_TENSOR_AUDIT="${MEGATRON_TENSOR_AUDIT:-0}"
export MEGATRON_TENSOR_AUDIT_RANKS="${MEGATRON_TENSOR_AUDIT_RANKS:-all}"
export MEGATRON_TENSOR_AUDIT_LIMIT="${MEGATRON_TENSOR_AUDIT_LIMIT:-128}"
export MEGATRON_TENSOR_AUDIT_FILTER="${MEGATRON_TENSOR_AUDIT_FILTER:-moe_expert}"
export MEGATRON_FINE_OFFLOAD_STREAMBP_REPLAY_KEEP_STORAGES="${MEGATRON_FINE_OFFLOAD_STREAMBP_REPLAY_KEEP_STORAGES:-core_attn attn_proj expert_fc1}"
export MEGATRON_FINE_OFFLOAD_FORCE_RELEASE_IN_STREAMBP_REPLAY="${MEGATRON_FINE_OFFLOAD_FORCE_RELEASE_IN_STREAMBP_REPLAY:-0}"
export MEGATRON_FINE_OFFLOAD_PIN_MEMORY="${MEGATRON_FINE_OFFLOAD_PIN_MEMORY:-auto}"
export MEGATRON_FINE_OFFLOAD_PINNED_MAX_MB="${MEGATRON_FINE_OFFLOAD_PINNED_MAX_MB:-64}"
export MEGATRON_FINE_OFFLOAD_STRIDED_COPY_CHUNK_MB="${MEGATRON_FINE_OFFLOAD_STRIDED_COPY_CHUNK_MB:-128}"
export MEGATRON_FINE_OFFLOAD_STRIDED_COPY_NON_BLOCKING="${MEGATRON_FINE_OFFLOAD_STRIDED_COPY_NON_BLOCKING:-0}"
export MEGATRON_PIPELINE_QUEUE_OFFLOAD="${MEGATRON_PIPELINE_QUEUE_OFFLOAD:-0}"
export MEGATRON_PIPELINE_QUEUE_OFFLOAD_MIN_MB="${MEGATRON_PIPELINE_QUEUE_OFFLOAD_MIN_MB:-1}"
export MEGATRON_PIPELINE_QUEUE_OFFLOAD_PIN_MEMORY="${MEGATRON_PIPELINE_QUEUE_OFFLOAD_PIN_MEMORY:-auto}"
export MEGATRON_ACT_ECO_CORRECTION_ROW_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_ROW_CHUNK:-2048}"
export MEGATRON_ACT_ECO_CORRECTION_OUT_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_OUT_CHUNK:-2048}"
export MEGATRON_ACT_ECO_CORRECTION_IN_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_IN_CHUNK:-0}"
export APPLY_ROPE_FUSION="${APPLY_ROPE_FUSION}"
export SPINQUANT="${SPINQUANT:-1}"
export TURBOQUANT="${TURBOQUANT:-0}"
export USE_HIGGS="${USE_HIGGS:-1}"
export HIGGS_KV_PRESET="${HIGGS_KV_PRESET:-dense_2bit}"
export INDEXCACHE="${INDEXCACHE:-1}"
export DSA_INDEXCACHE_QUANTIZATION="${DSA_INDEXCACHE_QUANTIZATION:-nvfp4_e2m1_ue8m0}"
export DSA_INDEXCACHE_QUANT_EPS="${DSA_INDEXCACHE_QUANT_EPS:-1e-4}"
export DSA_INDEXCACHE_HISA="${DSA_INDEXCACHE_HISA:-1}"
export DSA_INDEXCACHE_HISA_BLOCK_SIZE="${DSA_INDEXCACHE_HISA_BLOCK_SIZE:-128}"
export DSA_INDEXCACHE_HISA_BLOCK_TOPK="${DSA_INDEXCACHE_HISA_BLOCK_TOPK:-64}"
export DSA_INDEXCACHE_HISA_COMPRESSION_RATIO="${DSA_INDEXCACHE_HISA_COMPRESSION_RATIO:-4.0}"
export MOE_ROUTER_LOAD_BALANCING_TYPE="${MOE_ROUTER_LOAD_BALANCING_TYPE:-seq_aux_loss}"
export MOE_AUX_LOSS_COEFF="${MOE_AUX_LOSS_COEFF:-1e-4}"
export MOE_ROUTER_BIAS_UPDATE_RATE="${MOE_ROUTER_BIAS_UPDATE_RATE:-1e-3}"
export MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD="${MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD:-sign}"
export MOE_ROUTER_QUANTILE_BIAS_ITERS="${MOE_ROUTER_QUANTILE_BIAS_ITERS:-5}"
export MOE_ROUTER_QUANTILE_BIAS_APPLICATION="${MOE_ROUTER_QUANTILE_BIAS_APPLICATION:-delayed}"
export MOE_ROUTER_QUANTILE_BIAS_WARMUP_STEPS="${MOE_ROUTER_QUANTILE_BIAS_WARMUP_STEPS:-0}"
export MOE_ROUTER_QUANTILE_BIAS_SYNC_SCORES="${MOE_ROUTER_QUANTILE_BIAS_SYNC_SCORES:-1}"
export MEGATRON_FREEZE_ROUTER="${MEGATRON_FREEZE_ROUTER:-1}"
# Freeze router parameters, not the dynamic expert-bias load-balancing state.
export MEGATRON_FREEZE_ROUTER_EXPERT_BIAS="${MEGATRON_FREEZE_ROUTER_EXPERT_BIAS:-0}"
export DSA_CHUNK_SIZE="${DSA_CHUNK_SIZE}"
export DSA_INDEXER_TOPK="${DSA_INDEXER_TOPK:-1024}"
export DSA_INDEXER_LOSS_COEFF="${DSA_INDEXER_LOSS_COEFF:-0.1}"
export MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE="${MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE:-token_mean}"
export MEGATRON_DSA_TRITON="${MEGATRON_DSA_TRITON:-1}"
export MEGATRON_DSA_TRITON_INDEXER="${MEGATRON_DSA_TRITON_INDEXER:-1}"
export MEGATRON_DSA_SPLIT_QK="${MEGATRON_DSA_SPLIT_QK:-1}"
export MEGATRON_DSA_STREAMING_INDEXER_TOPK="${MEGATRON_DSA_STREAMING_INDEXER_TOPK:-1}"
export MEGATRON_DSA_INDEXER_ROPE_FUSION="${MEGATRON_DSA_INDEXER_ROPE_FUSION:-1}"
export MEGATRON_DSA_INDEXER_ROPE_INPLACE="${MEGATRON_DSA_INDEXER_ROPE_INPLACE:-1}"
export MEGATRON_DSA_INDEXER_TORCH_K_NORM="${MEGATRON_DSA_INDEXER_TORCH_K_NORM:-1}"
export MEGATRON_DSA_DEBUG_SYNC="${MEGATRON_DSA_DEBUG_SYNC:-0}"
export MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE="${MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE:-4096}"
export MEGATRON_DSA_SORT_TOPK_INDICES="${MEGATRON_DSA_SORT_TOPK_INDICES:-0}"
export MEGATRON_DSA_COMPACT_TOPK_INDICES="${MEGATRON_DSA_COMPACT_TOPK_INDICES:-1}"
export MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS="${MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS:-1}"
export MEGATRON_DSA_TRITON_BLOCK_K_BWD="${MEGATRON_DSA_TRITON_BLOCK_K_BWD:-32}"
export MEGATRON_DSA_TRITON_BWD_NUM_WARPS="${MEGATRON_DSA_TRITON_BWD_NUM_WARPS:-2}"
export MEGATRON_DSA_BACKWARD_TRIM_CACHE="${MEGATRON_DSA_BACKWARD_TRIM_CACHE:-0}"
export MEGATRON_DSA_BACKWARD_TRIM_SAFETY_MB="${MEGATRON_DSA_BACKWARD_TRIM_SAFETY_MB:-1024}"
export MEGATRON_DSA_BACKWARD_TRIM_CACHED_MB="${MEGATRON_DSA_BACKWARD_TRIM_CACHED_MB:-2048}"
export MEGATRON_DSA_BACKWARD_TRIM_SYNC="${MEGATRON_DSA_BACKWARD_TRIM_SYNC:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD="${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK="${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK:-32768}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS="${MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD="${MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD:-1}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD:-1}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD:-1}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS:-8}"
export MEGATRON_DSA_CUDA_KV_BWD="${MEGATRON_DSA_CUDA_KV_BWD:-0}"
export MEGATRON_DSA_CUDA_KV_BWD_TILE_Q="${MEGATRON_DSA_CUDA_KV_BWD_TILE_Q:-2}"
export MEGATRON_DSA_CUDA_KV_BWD_TILE_K="${MEGATRON_DSA_CUDA_KV_BWD_TILE_K:-4}"
export MEGATRON_DSA_VALIDATE_TOPK_INDICES="${MEGATRON_DSA_VALIDATE_TOPK_INDICES:-0}"
export MEGATRON_HISA_CANDIDATE_SLOT_GROUP="${MEGATRON_HISA_CANDIDATE_SLOT_GROUP:-8}"
export MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB="${MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB:-0}"
export MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB="${MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB:-0}"
export MEGATRON_HISA_CANDIDATE_TRIM_CACHE="${MEGATRON_HISA_CANDIDATE_TRIM_CACHE:-0}"
export MEGATRON_HISA_COMPACT_CANDIDATE_TOPK="${MEGATRON_HISA_COMPACT_CANDIDATE_TOPK:-1}"
export MEGATRON_HISA_SELECTOR_BACKEND="${MEGATRON_HISA_SELECTOR_BACKEND:-megakernel}"
export MEGATRON_HISA_SELECTOR_CUDA="${MEGATRON_HISA_SELECTOR_CUDA:-1}"
export MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH="${MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH:-0}"
export MEGATRON_HISA_SELECTOR_ROW_CHUNK="${MEGATRON_HISA_SELECTOR_ROW_CHUNK:-512}"
export MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES="${MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES:-1}"
export MEGATRON_HISA_BMM_CUBLASDX_REFINE="${MEGATRON_HISA_BMM_CUBLASDX_REFINE:-1}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_HEAD_GROUP="${MEGATRON_HISA_SELECTED_SCORE_BWD_HEAD_GROUP:-8}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_WARP_GROUPED="${MEGATRON_HISA_SELECTED_SCORE_BWD_WARP_GROUPED:-1}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N="${MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N:-32}"
export MEGATRON_HISA_ASSUME_SORTED_POSITIONS="${MEGATRON_HISA_ASSUME_SORTED_POSITIONS:-1}"
export MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT="${MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT:-0}"
export MEGATRON_HISA_FUSED_INDEXER_LOSS="${MEGATRON_HISA_FUSED_INDEXER_LOSS:-1}"
export MEGATRON_DSA_COMPACT_TOPK_INDICES="${MEGATRON_DSA_COMPACT_TOPK_INDICES:-1}"
export MEGATRON_DSA_STREAM_TRITON_ATTENTION_CHUNKS="${MEGATRON_DSA_STREAM_TRITON_ATTENTION_CHUNKS:-1}"
export MEGATRON_DSA_SP_PROJECT_BEFORE_GATHER="${MEGATRON_DSA_SP_PROJECT_BEFORE_GATHER:-1}"
export MEGATRON_HISA_TARGET_TRITON="${MEGATRON_HISA_TARGET_TRITON:-1}"
export MEGATRON_HISA_TARGET_BLOCK_K="${MEGATRON_HISA_TARGET_BLOCK_K:-64}"
export MEGATRON_HISA_TARGET_ROW_CHUNK="${MEGATRON_HISA_TARGET_ROW_CHUNK:-512}"
export MEGATRON_HISA_KL_GRAD_TRITON="${MEGATRON_HISA_KL_GRAD_TRITON:-1}"
export MEGATRON_PREWARM_PIPELINE_P2P="${MEGATRON_PREWARM_PIPELINE_P2P:-1}"
export MEGATRON_DSA_TEACHER_SCORE_SCRATCH="${MEGATRON_DSA_TEACHER_SCORE_SCRATCH:-1}"
export MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH="${MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH:-1}"
export MEGATRON_WEIGHTED_SWIGLU_FUSER="${MEGATRON_WEIGHTED_SWIGLU_FUSER:-triton}"
export MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE="${MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE:-1}"
export MEGATRON_DEEPEP_COMPACT_STABLE_MAP="${MEGATRON_DEEPEP_COMPACT_STABLE_MAP:-0}"
export MEGATRON_DEEPEP_COMPACT_ROW_CHUNK="${MEGATRON_DEEPEP_COMPACT_ROW_CHUNK:-131072}"
export MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST="${MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST:-1}"
export FINE_GRAINED_ACTIVATION_OFFLOADING=0
export OFFLOAD_MODULES=""
export MEGATRON_PIPELINE_PROGRESS_LOG="${MEGATRON_PIPELINE_PROGRESS_LOG:-0}"
export MEGATRON_PIPELINE_PROGRESS_INTERVAL="${MEGATRON_PIPELINE_PROGRESS_INTERVAL:-16}"
export MEGATRON_PIPELINE_PROGRESS_TP_RANKS="${MEGATRON_PIPELINE_PROGRESS_TP_RANKS:-0}"
export MEGATRON_MOE_STAGE_PROGRESS_LOG="${MEGATRON_MOE_STAGE_PROGRESS_LOG:-0}"
export MEGATRON_MOE_STAGE_PROGRESS_RANKS="${MEGATRON_MOE_STAGE_PROGRESS_RANKS:-0}"
export MEGATRON_MOE_STAGE_PROGRESS_SYNC="${MEGATRON_MOE_STAGE_PROGRESS_SYNC:-0}"
export NVFP4_ACTIVATION_ECO="${NVFP4_ACTIVATION_ECO:-0}"
export NVFP4_ACTIVATION_ECO_MODULES="${NVFP4_ACTIVATION_ECO_MODULES:-all}"
export NVFP4_ACTIVATION_ECO_RECOMPUTE_ONLY="${NVFP4_ACTIVATION_ECO_RECOMPUTE_ONLY:-1}"
export NVFP4_ACTIVATION_ECO_QUANTIZER_BACKEND="${NVFP4_ACTIVATION_ECO_QUANTIZER_BACKEND:-te}"
export NVFP4_ACTIVATION_ECO_CORRECTION_DTYPE="${NVFP4_ACTIVATION_ECO_CORRECTION_DTYPE:-bf16}"
export MEGATRON_ACT_ECO_DEBUG_SYNC="${MEGATRON_ACT_ECO_DEBUG_SYNC:-0}"
export MEGATRON_ACT_ECO_DEBUG_RANKS="${MEGATRON_ACT_ECO_DEBUG_RANKS:-all}"
export MEGATRON_ACT_ECO_DEBUG_VERBOSE="${MEGATRON_ACT_ECO_DEBUG_VERBOSE:-0}"
export MEGATRON_STREAMBP_DEBUG_SYNC="${MEGATRON_STREAMBP_DEBUG_SYNC:-0}"
export MEGATRON_STREAMBP_DEBUG_RANKS="${MEGATRON_STREAMBP_DEBUG_RANKS:-all}"
export MEGATRON_STREAMBP_DEBUG_VERBOSE="${MEGATRON_STREAMBP_DEBUG_VERBOSE:-0}"
export MEGATRON_DDP_GRAD_DEBUG_SYNC="${MEGATRON_DDP_GRAD_DEBUG_SYNC:-0}"
export MEGATRON_DDP_GRAD_DEBUG_RANKS="${MEGATRON_DDP_GRAD_DEBUG_RANKS:-all}"
export MEGATRON_DDP_GRAD_DEBUG_PARAM_REGEX="${MEGATRON_DDP_GRAD_DEBUG_PARAM_REGEX:-}"
export MEGATRON_DDP_GRAD_DEBUG_VERBOSE="${MEGATRON_DDP_GRAD_DEBUG_VERBOSE:-0}"
export FLASH_ADAMW_ECO="${FLASH_ADAMW_ECO:-1}"
export FLASH_ADAMW_FSDP_ECO_INJECT="${FLASH_ADAMW_FSDP_ECO_INJECT:-0}"
export FLASH_ADAMW_ECO_LR_FLOOR="${FLASH_ADAMW_ECO_LR_FLOOR:-base}"
export FLASH_ADAMW_ECO_PROJECTION="${FLASH_ADAMW_ECO_PROJECTION:-gain}"
export FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET:-2.0}"
export FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET:-0.25}"
export FLASH_ADAMW_ECO_PROJECTION_STEPS="${FLASH_ADAMW_ECO_PROJECTION_STEPS:-16}"
export FLASH_ADAMW_COMPRESS_STATE_DICT="${FLASH_ADAMW_COMPRESS_STATE_DICT:-1}"
export ENABLE_ZCC="${ENABLE_ZCC:-1}"
export MEGATRON_FLASH_FUSE_STATE_BUFFER="${MEGATRON_FLASH_FUSE_STATE_BUFFER:-0}"
export ZCC_FLASH_DEVICE="${ZCC_FLASH_DEVICE:-/dev/shm/megatron_zcc/$RUN_NAME}"
export ZCC_WORKERS_NUM="${ZCC_WORKERS_NUM:-8}"
export ZCC_DURABLE_INTERVAL="${ZCC_DURABLE_INTERVAL:-50}"
export ZCC_DURABLE_DIR="${ZCC_DURABLE_DIR:-$SAVE_CKPT/zcc/$RUN_NAME}"
export ZCC_COMPRESS="${ZCC_COMPRESS:-zstd:1}"
export ZCC_RETAIN_LATEST="${ZCC_RETAIN_LATEST:-1}"
export MEGATRON_NUMERIC_DEBUG="${MEGATRON_NUMERIC_DEBUG:-0}"
export MEGATRON_NUMERIC_DEBUG_RANKS="${MEGATRON_NUMERIC_DEBUG_RANKS:-all}"
export MEGATRON_NUMERIC_DEBUG_HOOK_RANKS="${MEGATRON_NUMERIC_DEBUG_HOOK_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS="${MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_DSA_RANKS="${MEGATRON_NUMERIC_DEBUG_DSA_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_RANKS="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_PARAM_RANKS="${MEGATRON_NUMERIC_DEBUG_PARAM_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS:-${MEGATRON_NUMERIC_DEBUG_RANKS:-all}}"
export MEGATRON_NUMERIC_DEBUG_START_ITER="${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}"
export MEGATRON_NUMERIC_DEBUG_HOOK_START_ITER="${MEGATRON_NUMERIC_DEBUG_HOOK_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_START_ITER="${MEGATRON_NUMERIC_DEBUG_ROUTER_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_DSA_START_ITER="${MEGATRON_NUMERIC_DEBUG_DSA_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_START_ITER="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_PARAM_START_ITER="${MEGATRON_NUMERIC_DEBUG_PARAM_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_START_ITER="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_START_ITER:-${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}}"
export MEGATRON_NUMERIC_DEBUG_FIRST_N="${MEGATRON_NUMERIC_DEBUG_FIRST_N:-16}"
export MEGATRON_NUMERIC_DEBUG_INTERVAL="${MEGATRON_NUMERIC_DEBUG_INTERVAL:-1}"
export MEGATRON_NUMERIC_DEBUG_MAX_ELEMS="${MEGATRON_NUMERIC_DEBUG_MAX_ELEMS:-262144}"
export MEGATRON_NUMERIC_DEBUG_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_FULL_FINITE:-0}"
export MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT="${MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT:-16}"
export MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS="${MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS:-0}"
export MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS="${MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS:-0}"
export MEGATRON_NUMERIC_DEBUG_HOOK_CLASSES="${MEGATRON_NUMERIC_DEBUG_HOOK_CLASSES:-TransformerLayer,MoELayer,TopKRouter,DSAttention,DSAIndexer,SelfAttention,MLP}"
export MEGATRON_NUMERIC_DEBUG_VERBOSE_HOOKS="${MEGATRON_NUMERIC_DEBUG_VERBOSE_HOOKS:-0}"
export MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE="${MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE:-1}"
export MEGATRON_NUMERIC_DEBUG_PARAM_STATS="${MEGATRON_NUMERIC_DEBUG_PARAM_STATS:-0}"
export MEGATRON_NUMERIC_DEBUG_TOPK="${MEGATRON_NUMERIC_DEBUG_TOPK:-16}"
export MEGATRON_NUMERIC_DEBUG_ROUTER="${MEGATRON_NUMERIC_DEBUG_ROUTER:-0}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE="${MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE:-0}"
export MEGATRON_NUMERIC_DEBUG_ROUTER_LIMIT="${MEGATRON_NUMERIC_DEBUG_ROUTER_LIMIT:-64}"
export MEGATRON_NUMERIC_DEBUG_DSA="${MEGATRON_NUMERIC_DEBUG_DSA:-0}"
export MEGATRON_NUMERIC_DEBUG_DSA_FORCE="${MEGATRON_NUMERIC_DEBUG_DSA_FORCE:-0}"
export MEGATRON_NUMERIC_DEBUG_DSA_LIMIT="${MEGATRON_NUMERIC_DEBUG_DSA_LIMIT:-64}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_LIMIT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_LIMIT:-32}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_ADAM_LIMIT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_ADAM_LIMIT:-32}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST:-0}"
export MEGATRON_NUMERIC_DEBUG_FLASHOPT_ABORT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_ABORT:-${MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE:-1}}"
export MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS="${MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS:-0}"
export MEGATRON_NUMERIC_DEBUG_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_GRAD_ABORT:-1}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD:-0}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_ABORT:-1}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD:-0}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_FULL_FINITE:-1}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_ABORT:-1}"
export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_STAGE_LIMIT="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_STAGE_LIMIT:-8}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD:-0}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX:-shared_experts\\.linear_fc2\\.weight}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_STAGE_LIMIT="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_STAGE_LIMIT:-4}"
export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_COPY_LIMIT="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_COPY_LIMIT:-8}"
export MEGATRON_NUMERIC_DEBUG_LOSS="${MEGATRON_NUMERIC_DEBUG_LOSS:-0}"
export MEGATRON_NUMERIC_DEBUG_BATCH="${MEGATRON_NUMERIC_DEBUG_BATCH:-0}"
export MEGATRON_FLASH_ADAMW_NVFP4_USE_MAIN_GRAD="${MEGATRON_FLASH_ADAMW_NVFP4_USE_MAIN_GRAD:-0}"
export MEGATRON_GRAD_OWNERSHIP="${MEGATRON_GRAD_OWNERSHIP:-0}"
export MEGATRON_GRAD_OWNERSHIP_RANKS="${MEGATRON_GRAD_OWNERSHIP_RANKS:-all}"
export MEGATRON_GRAD_OWNERSHIP_START_ITER="${MEGATRON_GRAD_OWNERSHIP_START_ITER:-1}"
export MEGATRON_GRAD_OWNERSHIP_FIRST_N="${MEGATRON_GRAD_OWNERSHIP_FIRST_N:-8}"
export MEGATRON_GRAD_OWNERSHIP_INTERVAL="${MEGATRON_GRAD_OWNERSHIP_INTERVAL:-1}"
export MEGATRON_GRAD_OWNERSHIP_TOP_OWNERS="${MEGATRON_GRAD_OWNERSHIP_TOP_OWNERS:-32}"
export MEGATRON_GRAD_OWNERSHIP_TOP_PARAMS="${MEGATRON_GRAD_OWNERSHIP_TOP_PARAMS:-0}"
export HF_UPLOAD_CHECKPOINTS="${HF_UPLOAD_CHECKPOINTS:-1}"
export HF_REPO_ID="${HF_REPO_ID:-BlaiseAI/corsaire-1-research-preview}"
export HF_UPLOAD_FOLDER_PREFIX="${HF_UPLOAD_FOLDER_PREFIX:-corsaire-1-research-preview}"
export HF_UPLOAD_INTERVAL="${HF_UPLOAD_INTERVAL:-500}"
export HF_UPLOAD_RETAIN="${HF_UPLOAD_RETAIN:-1}"
export HF_UPLOAD_STABLE_SECONDS="${HF_UPLOAD_STABLE_SECONDS:-180}"
export HF_UPLOAD_POLL_SECONDS="${HF_UPLOAD_POLL_SECONDS:-60}"
export HF_UPLOAD_PRIVATE="${HF_UPLOAD_PRIVATE:-1}"
export NODE_RANK="$node_rank"
mkdir -p "\$TRITON_CACHE_DIR"
EOF
}

NODE0_RUNNER="$LOG_DIR/${RUN_NAME}_node0_runner.sh"
NODE1_LOCAL_RUNNER="$LOG_DIR/${RUN_NAME}_node1_runner.sh"
NODE1_WRAPPER="$LOG_DIR/${RUN_NAME}_node1_wrapper.sh"
LOCAL_MONITOR="$LOG_DIR/${RUN_NAME}_node0_gpu_monitor.sh"
REMOTE_MONITOR="$LOG_DIR/${RUN_NAME}_node1_gpu_monitor.sh"

{
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    write_env_block 0
    echo "cd '$MEGATRON_DIR'"
    echo "if [[ \"\$HF_UPLOAD_CHECKPOINTS\" == \"1\" ]]; then"
    echo "  mkdir -p '$LOG_DIR'"
    echo "  HF_PRIVATE_ARG=(); [[ \"\$HF_UPLOAD_PRIVATE\" == \"1\" ]] && HF_PRIVATE_ARG=(--private)"
    echo "  uv run --no-sync python tools/upload_mcore_checkpoints_to_hf.py \\"
    echo "    --checkpoint-root \"\$SAVE_CKPT\" \\"
    echo "    --repo-id \"\$HF_REPO_ID\" \\"
    echo "    --folder-prefix \"\$HF_UPLOAD_FOLDER_PREFIX\" \\"
    echo "    --node-name node0 \\"
    echo "    --node-rank 0 --expected-nodes 2 \\"
    echo "    --shard-start 0 --shard-end 7 \\"
    echo "    --upload-interval \"\$HF_UPLOAD_INTERVAL\" \\"
    echo "    --retain \"\$HF_UPLOAD_RETAIN\" \\"
    echo "    --stable-seconds \"\$HF_UPLOAD_STABLE_SECONDS\" \\"
    echo "    --poll-seconds \"\$HF_UPLOAD_POLL_SECONDS\" \\"
    echo "    --retention-owner \\"
    echo "    \"\${HF_PRIVATE_ARG[@]}\" > '$LOG_DIR/${RUN_NAME}_hf_upload_node0.log' 2>&1 &"
    echo "  HF_UPLOAD_PID=\$!"
    echo "  trap 'kill \"\$HF_UPLOAD_PID\" 2>/dev/null || true' EXIT"
    echo "fi"
    echo "echo '[node0] starting $RUN_NAME at '\"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    echo "examples/sft/run_sft_deepseek_nvfp4.sh 2>&1 | tee '$LOG0'"
} > "$NODE0_RUNNER"

{
    echo '#!/usr/bin/env bash'
    echo 'set -euo pipefail'
    write_env_block 1
    echo "cd '$REMOTE_MEGATRON_DIR'"
    echo "if [[ \"\$HF_UPLOAD_CHECKPOINTS\" == \"1\" ]]; then"
    echo "  mkdir -p '$LOG_DIR'"
    echo "  HF_PRIVATE_ARG=(); [[ \"\$HF_UPLOAD_PRIVATE\" == \"1\" ]] && HF_PRIVATE_ARG=(--private)"
    echo "  uv run --no-sync python tools/upload_mcore_checkpoints_to_hf.py \\"
    echo "    --checkpoint-root \"\$SAVE_CKPT\" \\"
    echo "    --repo-id \"\$HF_REPO_ID\" \\"
    echo "    --folder-prefix \"\$HF_UPLOAD_FOLDER_PREFIX\" \\"
    echo "    --node-name node1 \\"
    echo "    --node-rank 1 --expected-nodes 2 \\"
    echo "    --shard-start 8 --shard-end 15 \\"
    echo "    --upload-interval \"\$HF_UPLOAD_INTERVAL\" \\"
    echo "    --retain \"\$HF_UPLOAD_RETAIN\" \\"
    echo "    --stable-seconds \"\$HF_UPLOAD_STABLE_SECONDS\" \\"
    echo "    --poll-seconds \"\$HF_UPLOAD_POLL_SECONDS\" \\"
    echo "    \"\${HF_PRIVATE_ARG[@]}\" > '$LOG_DIR/${RUN_NAME}_hf_upload_node1.log' 2>&1 &"
    echo "  HF_UPLOAD_PID=\$!"
    echo "  trap 'kill \"\$HF_UPLOAD_PID\" 2>/dev/null || true' EXIT"
    echo "fi"
    echo "echo '[node1] starting $RUN_NAME at '\"\$(date -u +%Y-%m-%dT%H:%M:%SZ)\""
    echo "examples/sft/run_sft_deepseek_nvfp4.sh"
} > "$NODE1_LOCAL_RUNNER"

chmod +x "$NODE0_RUNNER" "$NODE1_LOCAL_RUNNER"
"${SSH_CMD[@]}" "$REMOTE_HOST" "cat > '$REMOTE_RUNNER' && chmod +x '$REMOTE_RUNNER'" < "$NODE1_LOCAL_RUNNER"

cat > "$NODE1_WRAPPER" <<EOF
#!/usr/bin/env bash
set -euo pipefail
${SSH_TTY_PREFIX} "bash '$REMOTE_RUNNER'" 2>&1 | tee "$LOG1"
EOF

cat > "$LOCAL_MONITOR" <<'EOF'
#!/usr/bin/env bash
set -euo pipefail
if command -v nvtop >/dev/null 2>&1; then
    exec nvtop
fi
exec watch -n 2 'nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw --format=csv'
EOF

cat > "$REMOTE_MONITOR" <<EOF
#!/usr/bin/env bash
set -euo pipefail
exec ${SSH_TTY_PREFIX} 'if command -v nvtop >/dev/null 2>&1; then exec nvtop; fi; exec watch -n 2 "nvidia-smi --query-gpu=index,name,utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw --format=csv"'
EOF

chmod +x "$NODE1_WRAPPER" "$LOCAL_MONITOR" "$REMOTE_MONITOR"

tmux new-session -d -s "$SESSION" -n train
P0="$(tmux display-message -p -t "$SESSION:0" '#{pane_id}')"
tmux send-keys -t "$P0" "bash '$NODE0_RUNNER'; echo; echo '[node0 pane exited]'; exec bash" C-m
tmux split-window -h -t "$P0"
P1="$(tmux display-message -p -t "$SESSION:0" '#{pane_id}')"
tmux send-keys -t "$P1" "bash '$NODE1_WRAPPER'; echo; echo '[node1 pane exited]'; exec bash" C-m
tmux split-window -v -t "$P0" "bash '$LOCAL_MONITOR'"
tmux split-window -v -t "$P1" "bash '$REMOTE_MONITOR'"
tmux select-layout -t "$SESSION:0" tiled >/dev/null
tmux set-option -t "$SESSION" remain-on-exit on >/dev/null
if [[ "$ATTACH" == "1" ]]; then
    tmux attach-session -t "$SESSION"
else
    echo "tmux session '$SESSION' started. Attach with: tmux attach -t '$SESSION'"
fi
