#!/bin/bash
# DeepSeek-V3.2 REAP NVFP4 W4A4KV4 SFT.
#
# This script expects --load to point at a Megatron torch_dist checkpoint. The
# BlaiseAI Hugging Face checkpoint still needs conversion before training.

#SBATCH --job-name=deepseek_v32_reap_sft
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=1
#SBATCH --gpus-per-node=8

set -euo pipefail

# ======================
# Environment
# ======================
USE_MEGATRON_FSDP="${USE_MEGATRON_FSDP:-0}"
export MEGATRON_FSDP_FLUSH_READY_BUCKETS_ON_RESET="${MEGATRON_FSDP_FLUSH_READY_BUCKETS_ON_RESET:-1}"
export MEGATRON_FSDP_LOG_READY_BUCKET_FLUSH="${MEGATRON_FSDP_LOG_READY_BUCKET_FLUSH:-0}"
USE_STREAMBP="${USE_STREAMBP:-0}"
STREAMBP_CHUNK_SIZE="${STREAMBP_CHUNK_SIZE:-}"
STREAMBP_LOGITS_CHUNK_SIZE="${STREAMBP_LOGITS_CHUNK_SIZE:-8192}"
export MEGATRON_STREAMBP_FUSED_LCE="${MEGATRON_STREAMBP_FUSED_LCE:-0}"
export MEGATRON_CHUNKED_LM_HEAD_LOSS="${MEGATRON_CHUNKED_LM_HEAD_LOSS:-0}"
export MEGATRON_STREAMBP_FUSED_LCE_SP_TILE_SIZE="${MEGATRON_STREAMBP_FUSED_LCE_SP_TILE_SIZE:-1024}"
export MEGATRON_STREAMBP_SKIP_PP_RANKS="${MEGATRON_STREAMBP_SKIP_PP_RANKS-}"
export LCE_FWD_VOCAB_SPLIT_SIZE="${LCE_FWD_VOCAB_SPLIT_SIZE:-8192}"
export LCE_BWD_VOCAB_SPLIT_SIZE="${LCE_BWD_VOCAB_SPLIT_SIZE:-8192}"
STREAMBP_MOE_MLP_CHUNKS="${STREAMBP_MOE_MLP_CHUNKS:-1}"
STREAMBP_MOE_MLP_BACKWARD_CHUNKS="${STREAMBP_MOE_MLP_BACKWARD_CHUNKS:-1}"
export MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD="${MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD:-0}"
MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE="${MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE:-}"
MOE_ROUTER_PADDING_FOR_QUANTIZATION="${MOE_ROUTER_PADDING_FOR_QUANTIZATION:-0}"
MEGATRON_FREEZE_ROUTER="${MEGATRON_FREEZE_ROUTER:-1}"
# Freeze router parameters, not the dynamic expert-bias load-balancing state.
MEGATRON_FREEZE_ROUTER_EXPERT_BIAS="${MEGATRON_FREEZE_ROUTER_EXPERT_BIAS:-0}"
export MEGATRON_FREEZE_ROUTER MEGATRON_FREEZE_ROUTER_EXPERT_BIAS
MOE_TOKEN_DISPATCHER_TYPE="${MOE_TOKEN_DISPATCHER_TYPE:-flex}"
MOE_FLEX_DISPATCHER_BACKEND="${MOE_FLEX_DISPATCHER_BACKEND:-deepep}"
export MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS="${MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS:-0}"
export MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD="${MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD:-0}"
export MEGATRON_STREAMBP_HOST_SAVE_HIDDEN="${MEGATRON_STREAMBP_HOST_SAVE_HIDDEN:-0}"
export MEGATRON_STREAMBP_HOST_SAVE_PIN_MEMORY="${MEGATRON_STREAMBP_HOST_SAVE_PIN_MEMORY:-auto}"
export MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD="${MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD:-0}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_MIN_MB="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MIN_MB:-16}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB:-0}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS:-0}"
export MEGATRON_TE_GROUPED_LINEAR_FUSE_WGRAD_ACCUM="${MEGATRON_TE_GROUPED_LINEAR_FUSE_WGRAD_ACCUM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_FREE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_FREE_MB:-2048}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_RESERVE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_RESERVE_MB:-512}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CACHED_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CACHED_MB:-256}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC:-0}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_FREE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_FREE_MB:-2048}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_RESERVE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_RESERVE_MB:-1024}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CACHED_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CACHED_MB:-256}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC:-0}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_LOG="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_LOG:-0}"
export MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG="${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG:-0}"
export MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_RANKS="${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_RANKS:-0,7}"
if [[ "${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM}" == "1" || "${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM}" == "1" ]]; then
    uv run --no-sync python tools/patch_te_grouped_linear_alloc_guard.py
fi
export MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD="${MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD:-0}"
if [[ "${MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD}" == "1" ]]; then
    uv run --no-sync python tools/patch_te_reentrant_backward.py
fi
export MEGATRON_FINE_OFFLOAD_STREAMBP_REPLAY_KEEP_STORAGES="${MEGATRON_FINE_OFFLOAD_STREAMBP_REPLAY_KEEP_STORAGES:-core_attn attn_proj expert_fc1}"
export MEGATRON_FINE_OFFLOAD_FORCE_RELEASE_IN_STREAMBP_REPLAY="${MEGATRON_FINE_OFFLOAD_FORCE_RELEASE_IN_STREAMBP_REPLAY:-0}"
export MEGATRON_FINE_OFFLOAD_PIN_MEMORY="${MEGATRON_FINE_OFFLOAD_PIN_MEMORY:-auto}"
export MEGATRON_FINE_OFFLOAD_PINNED_MAX_MB="${MEGATRON_FINE_OFFLOAD_PINNED_MAX_MB:-64}"
export MEGATRON_FINE_OFFLOAD_STRIDED_COPY_CHUNK_MB="${MEGATRON_FINE_OFFLOAD_STRIDED_COPY_CHUNK_MB:-128}"
export MEGATRON_FINE_OFFLOAD_STRIDED_COPY_NON_BLOCKING="${MEGATRON_FINE_OFFLOAD_STRIDED_COPY_NON_BLOCKING:-0}"
export MEGATRON_PIPELINE_QUEUE_OFFLOAD="${MEGATRON_PIPELINE_QUEUE_OFFLOAD:-0}"
export MEGATRON_PIPELINE_QUEUE_OFFLOAD_MIN_MB="${MEGATRON_PIPELINE_QUEUE_OFFLOAD_MIN_MB:-1}"
export MEGATRON_PIPELINE_QUEUE_OFFLOAD_PIN_MEMORY="${MEGATRON_PIPELINE_QUEUE_OFFLOAD_PIN_MEMORY:-auto}"
export MEGATRON_ACT_ECO_CORRECTION_ROW_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_ROW_CHUNK:-2048}"
export MEGATRON_ACT_ECO_CORRECTION_OUT_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_OUT_CHUNK:-2048}"
export MEGATRON_ACT_ECO_CORRECTION_IN_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_IN_CHUNK:-0}"
OVERLAP_MOE_EXPERT_PARALLEL_COMM="${OVERLAP_MOE_EXPERT_PARALLEL_COMM:-0}"
if [[ -z "${RECOMPUTE+x}" ]]; then
    RECOMPUTE=0
    RECOMPUTE_GRANULARITY="${RECOMPUTE_GRANULARITY:-selective}"
    RECOMPUTE_MODULES="${RECOMPUTE_MODULES:-mla_up_proj}"
fi
if [[ "$USE_MEGATRON_FSDP" == "1" ]]; then
    export CUDA_DEVICE_MAX_CONNECTIONS="${CUDA_DEVICE_MAX_CONNECTIONS:-8}"
elif [[ "$OVERLAP_MOE_EXPERT_PARALLEL_COMM" == "1" ]]; then
    export CUDA_DEVICE_MAX_CONNECTIONS="${CUDA_DEVICE_MAX_CONNECTIONS:-32}"
else
    export CUDA_DEVICE_MAX_CONNECTIONS="${CUDA_DEVICE_MAX_CONNECTIONS:-1}"
fi
if [[ "$USE_MEGATRON_FSDP" == "1" && "$CUDA_DEVICE_MAX_CONNECTIONS" == "1" ]]; then
    echo "USE_MEGATRON_FSDP=1 requires CUDA_DEVICE_MAX_CONNECTIONS to be unset or greater than 1" >&2
    exit 1
fi
export NCCL_IB_DISABLE="${NCCL_IB_DISABLE:-0}"
export NCCL_TIMEOUT="${NCCL_TIMEOUT:-3600}"
export NCCL_DEBUG="${NCCL_DEBUG:-WARN}"
export SUPPRESS_UNBATCHED_P2P_WARN="${SUPPRESS_UNBATCHED_P2P_WARN:-1}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
export MEGATRON_DISABLE_JIT_FUSER="${MEGATRON_DISABLE_JIT_FUSER:-0}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
echo "PYTORCH_CUDA_ALLOC_CONF=${PYTORCH_CUDA_ALLOC_CONF}"
# Broad activation/temp offload is intentionally removed from the default training
# surface. The current fast path has enough GPU residency headroom that these
# CPU-transfer paths obscure kernel and pipeline bottlenecks more than they help.
export MEGATRON_TEMP_ACTIVATION_OFFLOAD=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_MODULES=""
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_MIN_MB=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_EMPTY_CACHE=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_NON_BLOCKING=0
export MEGATRON_MOE_COMBINE_REDUCE_SCATTER_DTYPE="${MEGATRON_MOE_COMBINE_REDUCE_SCATTER_DTYPE:-input}"
export MEGATRON_PIPELINE_PROGRESS_LOG="${MEGATRON_PIPELINE_PROGRESS_LOG:-0}"
export MEGATRON_PIPELINE_PROGRESS_INTERVAL="${MEGATRON_PIPELINE_PROGRESS_INTERVAL:-16}"
export MEGATRON_PIPELINE_PROGRESS_TP_RANKS="${MEGATRON_PIPELINE_PROGRESS_TP_RANKS:-0}"
if [[ "${ENABLE_TRAINING_DEBUG:-0}" != "1" ]]; then
    export MEGATRON_ACT_ECO_DEBUG_SYNC=0
    export MEGATRON_ACT_ECO_DEBUG_VERBOSE=0
    export MEGATRON_STREAMBP_DEBUG_SYNC=0
    export MEGATRON_STREAMBP_DEBUG_VERBOSE=0
    export MEGATRON_DDP_GRAD_DEBUG_SYNC=0
    export MEGATRON_DDP_GRAD_DEBUG_VERBOSE=0
    export MEGATRON_NUMERIC_DEBUG=0
    export MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS=0
    export MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS=0
    export MEGATRON_NUMERIC_DEBUG_PARAM_STATS=0
    export MEGATRON_NUMERIC_DEBUG_ROUTER=0
    export MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE=0
    export MEGATRON_NUMERIC_DEBUG_DSA=0
    export MEGATRON_NUMERIC_DEBUG_DSA_FORCE=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL=0
    export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST=0
    export MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS=0
    export MEGATRON_NUMERIC_DEBUG_DDP_GRAD=0
    export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD=0
    export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD=0
    export MEGATRON_NUMERIC_DEBUG_LOSS=0
    export MEGATRON_NUMERIC_DEBUG_BATCH=0
    export MEGATRON_GRAD_OWNERSHIP=0
fi
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE:-0}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_FREE_MB="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_FREE_MB:-16384}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHED_MB="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHED_MB:-2048}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_SYNC="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_SYNC:-0}"
export MEGATRON_STREAMBP_MOE_REPLAY_FORCE_TRIM="${MEGATRON_STREAMBP_MOE_REPLAY_FORCE_TRIM:-0}"
export MEGATRON_STREAMBP_SUPPRESS_TEMP_OFFLOAD_MODULES="${MEGATRON_STREAMBP_SUPPRESS_TEMP_OFFLOAD_MODULES:-moe_shared}"
export MEGATRON_MOE_UNPADDING_TRIM_CACHE="${MEGATRON_MOE_UNPADDING_TRIM_CACHE:-0}"
export MEGATRON_MOE_UNPADDING_TRIM_FREE_MB="${MEGATRON_MOE_UNPADDING_TRIM_FREE_MB:-16384}"
export MEGATRON_MOE_UNPADDING_TRIM_CACHED_MB="${MEGATRON_MOE_UNPADDING_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE="${MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE:-0}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_FREE_MB="${MEGATRON_MOE_EXPERT_FC1_TRIM_FREE_MB:-16384}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_RESERVE_MB="${MEGATRON_MOE_EXPERT_FC1_TRIM_RESERVE_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_CACHED_MB="${MEGATRON_MOE_EXPERT_FC1_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_SYNC="${MEGATRON_MOE_EXPERT_FC1_TRIM_SYNC:-0}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_GC="${MEGATRON_MOE_EXPERT_FC1_TRIM_GC:-0}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE="${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE:-0}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB="${MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB:-8192}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB="${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC="${MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC:-0}"
export MEGATRON_MOE_EXPERT_RELEASE_PRE_FC2_REFS="${MEGATRON_MOE_EXPERT_RELEASE_PRE_FC2_REFS:-1}"
export MEGATRON_MOE_SORT_TRIM_CACHE="${MEGATRON_MOE_SORT_TRIM_CACHE:-0}"
export MEGATRON_MOE_SORT_TRIM_FREE_MB="${MEGATRON_MOE_SORT_TRIM_FREE_MB:-16384}"
export MEGATRON_MOE_SORT_TRIM_SAFETY_MB="${MEGATRON_MOE_SORT_TRIM_SAFETY_MB:-1024}"
export MEGATRON_MOE_SORT_TRIM_CACHED_MB="${MEGATRON_MOE_SORT_TRIM_CACHED_MB:-2048}"
export MEGATRON_MOE_SORT_TRIM_SYNC="${MEGATRON_MOE_SORT_TRIM_SYNC:-0}"
export MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT="${MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT:-0}"
export MEGATRON_MLA_KEY_CAT_TRIM_MARGIN_MB="${MEGATRON_MLA_KEY_CAT_TRIM_MARGIN_MB:-1024}"
export MEGATRON_MLA_KEY_CAT_TRIM_CACHED_MB="${MEGATRON_MLA_KEY_CAT_TRIM_CACHED_MB:-512}"
export MEGATRON_TENSOR_AUDIT="${MEGATRON_TENSOR_AUDIT:-0}"
export MEGATRON_TENSOR_AUDIT_RANKS="${MEGATRON_TENSOR_AUDIT_RANKS:-all}"
export MEGATRON_TENSOR_AUDIT_LIMIT="${MEGATRON_TENSOR_AUDIT_LIMIT:-128}"
export MEGATRON_TENSOR_AUDIT_FILTER="${MEGATRON_TENSOR_AUDIT_FILTER:-moe_expert}"
export MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE="${MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE:-token_mean}"
export MEGATRON_DSA_TRITON="${MEGATRON_DSA_TRITON:-1}"
export MEGATRON_DSA_TRITON_INDEXER="${MEGATRON_DSA_TRITON_INDEXER:-1}"
export MEGATRON_DSA_SPLIT_QK="${MEGATRON_DSA_SPLIT_QK:-1}"
export MEGATRON_DSA_STREAMING_INDEXER_TOPK="${MEGATRON_DSA_STREAMING_INDEXER_TOPK:-1}"
export MEGATRON_DSA_INDEXER_ROPE_FUSION="${MEGATRON_DSA_INDEXER_ROPE_FUSION:-1}"
export MEGATRON_DSA_INDEXER_ROPE_INPLACE="${MEGATRON_DSA_INDEXER_ROPE_INPLACE:-1}"
export MEGATRON_DSA_INDEXER_TORCH_K_NORM="${MEGATRON_DSA_INDEXER_TORCH_K_NORM:-1}"
export MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE="${MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE:-4096}"
export MEGATRON_DSA_SORT_TOPK_INDICES="${MEGATRON_DSA_SORT_TOPK_INDICES:-0}"
export MEGATRON_DSA_COMPACT_TOPK_INDICES="${MEGATRON_DSA_COMPACT_TOPK_INDICES:-1}"
export MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS="${MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS:-1}"
export MEGATRON_DSA_TRITON_BLOCK_K_BWD="${MEGATRON_DSA_TRITON_BLOCK_K_BWD:-32}"
export MEGATRON_DSA_TRITON_BWD_NUM_WARPS="${MEGATRON_DSA_TRITON_BWD_NUM_WARPS:-2}"
export MEGATRON_DSA_BACKWARD_TRIM_CACHE="${MEGATRON_DSA_BACKWARD_TRIM_CACHE:-0}"
export MEGATRON_DSA_BACKWARD_TRIM_SAFETY_MB="${MEGATRON_DSA_BACKWARD_TRIM_SAFETY_MB:-1024}"
export MEGATRON_DSA_BACKWARD_TRIM_CACHED_MB="${MEGATRON_DSA_BACKWARD_TRIM_CACHED_MB:-2048}"
export MEGATRON_DSA_BACKWARD_TRIM_SYNC="${MEGATRON_DSA_BACKWARD_TRIM_SYNC:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD="${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK="${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK:-32768}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS="${MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD="${MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD:-1}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_RETAIN_GRAPH="${MEGATRON_DSA_SPLIT_QK_REENTRANT_RETAIN_GRAPH:-0}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD:-1}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD:-1}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS:-8}"
export MEGATRON_DSA_CUDA_KV_BWD="${MEGATRON_DSA_CUDA_KV_BWD:-0}"
export MEGATRON_DSA_CUDA_KV_BWD_TILE_Q="${MEGATRON_DSA_CUDA_KV_BWD_TILE_Q:-2}"
export MEGATRON_DSA_CUDA_KV_BWD_TILE_K="${MEGATRON_DSA_CUDA_KV_BWD_TILE_K:-4}"
export MEGATRON_DSA_VALIDATE_TOPK_INDICES="${MEGATRON_DSA_VALIDATE_TOPK_INDICES:-0}"
export MEGATRON_HISA_CANDIDATE_SLOT_GROUP="${MEGATRON_HISA_CANDIDATE_SLOT_GROUP:-8}"
export MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB="${MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB:-0}"
export MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB="${MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB:-0}"
export MEGATRON_HISA_CANDIDATE_TRIM_CACHE="${MEGATRON_HISA_CANDIDATE_TRIM_CACHE:-0}"
export MEGATRON_HISA_COMPACT_CANDIDATE_TOPK="${MEGATRON_HISA_COMPACT_CANDIDATE_TOPK:-1}"
export MEGATRON_HISA_SELECTOR_BACKEND="${MEGATRON_HISA_SELECTOR_BACKEND:-megakernel}"
export MEGATRON_HISA_SELECTOR_CUDA="${MEGATRON_HISA_SELECTOR_CUDA:-1}"
export MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH="${MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH:-0}"
export MEGATRON_HISA_SELECTOR_ROW_CHUNK="${MEGATRON_HISA_SELECTOR_ROW_CHUNK:-512}"
export MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES="${MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES:-1}"
export MEGATRON_HISA_BMM_CUBLASDX_REFINE="${MEGATRON_HISA_BMM_CUBLASDX_REFINE:-1}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_HEAD_GROUP="${MEGATRON_HISA_SELECTED_SCORE_BWD_HEAD_GROUP:-8}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_WARP_GROUPED="${MEGATRON_HISA_SELECTED_SCORE_BWD_WARP_GROUPED:-1}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N="${MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N:-32}"
export MEGATRON_HISA_ASSUME_SORTED_POSITIONS="${MEGATRON_HISA_ASSUME_SORTED_POSITIONS:-1}"
export MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT="${MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT:-0}"
export MEGATRON_HISA_FUSED_INDEXER_LOSS="${MEGATRON_HISA_FUSED_INDEXER_LOSS:-1}"
export MEGATRON_DSA_COMPACT_TOPK_INDICES="${MEGATRON_DSA_COMPACT_TOPK_INDICES:-1}"
export MEGATRON_DSA_STREAM_TRITON_ATTENTION_CHUNKS="${MEGATRON_DSA_STREAM_TRITON_ATTENTION_CHUNKS:-1}"
export MEGATRON_DSA_SP_PROJECT_BEFORE_GATHER="${MEGATRON_DSA_SP_PROJECT_BEFORE_GATHER:-1}"
export MEGATRON_HISA_TARGET_TRITON="${MEGATRON_HISA_TARGET_TRITON:-1}"
export MEGATRON_HISA_TARGET_BLOCK_K="${MEGATRON_HISA_TARGET_BLOCK_K:-64}"
export MEGATRON_HISA_TARGET_ROW_CHUNK="${MEGATRON_HISA_TARGET_ROW_CHUNK:-512}"
export MEGATRON_HISA_KL_GRAD_TRITON="${MEGATRON_HISA_KL_GRAD_TRITON:-1}"
export MEGATRON_PREWARM_PIPELINE_P2P="${MEGATRON_PREWARM_PIPELINE_P2P:-1}"
export MEGATRON_DSA_TEACHER_SCORE_SCRATCH="${MEGATRON_DSA_TEACHER_SCORE_SCRATCH:-1}"
export MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH="${MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH:-1}"
export MEGATRON_WEIGHTED_SWIGLU_FUSER="${MEGATRON_WEIGHTED_SWIGLU_FUSER:-triton}"
export MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE="${MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE:-1}"
export MEGATRON_DEEPEP_COMPACT_STABLE_MAP="${MEGATRON_DEEPEP_COMPACT_STABLE_MAP:-0}"
export MEGATRON_DEEPEP_COMPACT_ROW_CHUNK="${MEGATRON_DEEPEP_COMPACT_ROW_CHUNK:-131072}"
export MEGATRON_DEEPEP_COMPACT_BACKEND="${MEGATRON_DEEPEP_COMPACT_BACKEND:-rowcuda}"
export MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE="${MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE:-1}"
export MEGATRON_DEEPEP_COMPACT_CUDA_BACKWARD="${MEGATRON_DEEPEP_COMPACT_CUDA_BACKWARD:-0}"
export MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH="${MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH:-1}"
export MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE="${MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE:-0}"
export MEGATRON_DEEPEP_NUM_SMS="${MEGATRON_DEEPEP_NUM_SMS:-24}"
export MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE="${MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE:-8}"
export MEGATRON_DEEPEP_COMBINE_NUM_SMS="${MEGATRON_DEEPEP_COMBINE_NUM_SMS:-24}"
export MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS="${MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS:-16}"
export MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS="${MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS:-256}"
export MEGATRON_DEEPEP_COMBINE_RDMA_SEND_TOKENS="${MEGATRON_DEEPEP_COMBINE_RDMA_SEND_TOKENS:-}"
export MEGATRON_DEEPEP_COMBINE_RDMA_RECV_TOKENS="${MEGATRON_DEEPEP_COMBINE_RDMA_RECV_TOKENS:-}"
export MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST="${MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST:-1}"
export MEGATRON_REAP_LR_GROUPS="${MEGATRON_REAP_LR_GROUPS:-1}"
export MEGATRON_REAP_BACKBONE_LR_MULT="${MEGATRON_REAP_BACKBONE_LR_MULT:-0.2}"
export MEGATRON_REAP_NEW_COMPONENT_LR_MULT="${MEGATRON_REAP_NEW_COMPONENT_LR_MULT:-1.0}"
export MEGATRON_REAP_BACKBONE_UPDATE_CAP_RATIO="${MEGATRON_REAP_BACKBONE_UPDATE_CAP_RATIO:-2.0e-3}"
export MEGATRON_REAP_BACKBONE_UPDATE_CAP_STEPS="${MEGATRON_REAP_BACKBONE_UPDATE_CAP_STEPS:-500}"
export MEGATRON_REAP_BACKBONE_UPDATE_CAP_PARAM_RMS_FLOOR="${MEGATRON_REAP_BACKBONE_UPDATE_CAP_PARAM_RMS_FLOOR:-0.0}"
export MEGATRON_REAP_LR_GROUP_AUDIT="${MEGATRON_REAP_LR_GROUP_AUDIT:-1}"
export MEGATRON_REAP_LR_GROUP_AUDIT_SAMPLE="${MEGATRON_REAP_LR_GROUP_AUDIT_SAMPLE:-32}"
export FLASH_ADAMW_ECO_LR_FLOOR="${FLASH_ADAMW_ECO_LR_FLOOR:-base}"
export FLASH_ADAMW_ECO_PROJECTION="${FLASH_ADAMW_ECO_PROJECTION:-gain}"
export FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET:-2.0}"
export FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET:-0.25}"
export FLASH_ADAMW_ECO_PROJECTION_STEPS="${FLASH_ADAMW_ECO_PROJECTION_STEPS:-16}"
export FINE_GRAINED_ACTIVATION_OFFLOADING="${FINE_GRAINED_ACTIVATION_OFFLOADING:-0}"
export OFFLOAD_MODULES="${OFFLOAD_MODULES:-}"
if [[ "$FINE_GRAINED_ACTIVATION_OFFLOADING" == "1" ]]; then
    export NVTE_CPU_OFFLOAD_V1="${NVTE_CPU_OFFLOAD_V1:-1}"
fi
APPLY_ROPE_FUSION="${APPLY_ROPE_FUSION:-}"
DISTRIBUTED_TIMEOUT_MINUTES="${DISTRIBUTED_TIMEOUT_MINUTES:-60}"

DISTRIBUTED_BACKEND="${DISTRIBUTED_BACKEND:-nccl}"
if [[ "$DISTRIBUTED_BACKEND" == "ncclx" ]]; then
    if ulimit -Sn "$(ulimit -Hn)" 2>/dev/null; then
        :
    fi
    export MEGATRON_USE_TORCHCOMMS="${MEGATRON_USE_TORCHCOMMS:-1}"
    export MEGATRON_NCCLX_MEM_POOL="${MEGATRON_NCCLX_MEM_POOL:-1}"
    export MEGATRON_NCCLX_RDMA="${MEGATRON_NCCLX_RDMA:-1}"
    export MEGATRON_NCCLX_RDMA_PROFILE="${MEGATRON_NCCLX_RDMA_PROFILE:-roce}"
    export MEGATRON_NCCLX_RDMA_BACKENDS="${MEGATRON_NCCLX_RDMA_BACKENDS:-ib,nvl,socket}"
    export TORCHCOMM_TIMEOUT_SECONDS="${TORCHCOMM_TIMEOUT_SECONDS:-$((DISTRIBUTED_TIMEOUT_MINUTES * 60))}"
    if [[ -z "${NCCL_SOCKET_IFNAME:-}" || "$NCCL_SOCKET_IFNAME" == "gpu" ]]; then
        export NCCL_SOCKET_IFNAME="gpu0rdma0"
    fi
    export GLOO_SOCKET_IFNAME="${GLOO_SOCKET_IFNAME:-$NCCL_SOCKET_IFNAME}"
    export NCCL_NVLS_ENABLE="${NCCL_NVLS_ENABLE:-0}"
    export NCCL_IGNORE_TOPO_LOAD_FAILURE="${NCCL_IGNORE_TOPO_LOAD_FAILURE:-0}"
    if [[ -z "${NCCL_TOPO_FILE_PATH:-}" && -f "$HOME/ncclx_topology.env" ]]; then
        export NCCL_TOPO_FILE_PATH="$HOME/ncclx_topology.env"
    fi
    if [[ -z "${NCCL_TOPO_FILE_PATH:-}" || ! -f "$NCCL_TOPO_FILE_PATH" ]]; then
        echo "DISTRIBUTED_BACKEND=ncclx requires NCCL_TOPO_FILE_PATH or $HOME/ncclx_topology.env" >&2
        exit 1
    fi
fi

# ======================
# Path setup
# ======================
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MEGATRON_DIR="${MEGATRON_DIR:-"${SCRIPT_DIR}/../.."}"
cd "$MEGATRON_DIR"

if [[ -z "${CUDA_HOME:-}" && -x "$MEGATRON_DIR/.venv/lib/python3.12/site-packages/nvidia/cu13/bin/nvcc" ]]; then
    export CUDA_HOME="$MEGATRON_DIR/.venv/lib/python3.12/site-packages/nvidia/cu13"
fi
if [[ -n "${CUDA_HOME:-}" ]]; then
    export CUDA_PATH="${CUDA_PATH:-$CUDA_HOME}"
    export PATH="$CUDA_HOME/bin:$PATH"
    export LD_LIBRARY_PATH="$CUDA_HOME/lib64:$CUDA_HOME/lib:${LD_LIBRARY_PATH:-}"
fi
export DG_JIT_CACHE_DIR="${DG_JIT_CACHE_DIR:-$HOME/.cache/deep_gemm/deepseek_v32_reap_sft}"
mkdir -p "$DG_JIT_CACHE_DIR"
if [[ -z "${CC:-}" && -x /usr/bin/gcc ]]; then
    export CC=/usr/bin/gcc
fi
if [[ -z "${CXX:-}" && -x /usr/bin/g++ ]]; then
    export CXX=/usr/bin/g++
fi

MODEL_ID="${MODEL_ID:-BlaiseAI/DeepSeek-V3.2-REAP-345B-SpinQuant-ActKV-NVFP4}"
TOKENIZER_MODEL="${TOKENIZER_MODEL:-$MODEL_ID}"

LOAD_CKPT="${LOAD_CKPT:-"$HOME/checkpoints/deepseek_v32_reap_spinquant_actkv_nvfp4_megatron_tp8_pp1_ep8"}"
SAVE_CKPT="${SAVE_CKPT:-"$HOME/checkpoints/sft_deepseek_v32_reap_spinquant_actkv_nvfp4_tp8_pp5_ep8"}"
DATA_PATH="${DATA_PATH:-"$HOME/data/sft/blaise-sft-training-mix/blaise-sft-training-mix-full.jsonl"}"
export MEGATRON_SFT_SHUFFLE_ROWS="${MEGATRON_SFT_SHUFFLE_ROWS:-1}"
export MEGATRON_SFT_SHUFFLE_SEED="${MEGATRON_SFT_SHUFFLE_SEED:-1234}"
export MEGATRON_SFT_SHUFFLE_BUILD_IF_MISSING="${MEGATRON_SFT_SHUFFLE_BUILD_IF_MISSING:-1}"
TENSORBOARD_LOGS_PATH="${TENSORBOARD_LOGS_PATH:-"$HOME/tensorboard_logs/sft_deepseek_v32_reap_nvfp4"}"

mkdir -p "$SAVE_CKPT" "$TENSORBOARD_LOGS_PATH"

# ======================
# Distributed setup
# ======================
GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
NNODES="${SLURM_NNODES:-${NNODES:-2}}"
NODE_RANK="${SLURM_NODEID:-${NODE_RANK:-0}}"
MASTER_ADDR="${MASTER_ADDR:-}"
if [[ -z "$MASTER_ADDR" && -n "${SLURM_JOB_NODELIST:-}" ]]; then
    MASTER_ADDR="$(scontrol show hostnames "$SLURM_JOB_NODELIST" | head -1)"
fi
MASTER_ADDR="${MASTER_ADDR:-localhost}"
MASTER_PORT="${MASTER_PORT:-29500}"

DISTRIBUTED_ARGS=(
    --nproc_per_node "$GPUS_PER_NODE"
    --nnodes "$NNODES"
    --node_rank "$NODE_RANK"
    --master_addr "$MASTER_ADDR"
    --master_port "$MASTER_PORT"
)

TORCHRUN_LOG_ARGS=()
if [[ -n "${TORCHRUN_LOG_DIR:-}" ]]; then
    mkdir -p "$TORCHRUN_LOG_DIR"
    TORCHRUN_LOG_ARGS+=(--log-dir "$TORCHRUN_LOG_DIR")
fi
if [[ -n "${TORCHRUN_REDIRECTS:-}" ]]; then
    TORCHRUN_LOG_ARGS+=(--redirects "$TORCHRUN_REDIRECTS")
fi
if [[ -n "${TORCHRUN_TEE:-}" ]]; then
    TORCHRUN_LOG_ARGS+=(--tee "$TORCHRUN_TEE")
fi
if [[ -n "${TORCHRUN_LOCAL_RANKS_FILTER:-}" ]]; then
    TORCHRUN_LOG_ARGS+=(--local-ranks-filter "$TORCHRUN_LOCAL_RANKS_FILTER")
fi

DISTRIBUTED_BACKEND_ARGS=(
    --distributed-backend "$DISTRIBUTED_BACKEND"
)

# ======================
# Parallelism
# ======================
# Fleet launchers should override the parallel shape explicitly. The current
# GCP A4 profile uses TP=8, PP=1, CP=4, EP=8 on 12x8 GPUs with Megatron FSDP.
TP="${TP:-4}"
PP="${PP:-2}"
CP="${CP:-1}"
EP="${EP:-4}"
ETP="${ETP:-1}"
if [[ -z "$APPLY_ROPE_FUSION" ]]; then
    if (( CP > 1 )) || [[ "${MEGATRON_DSA_SPLIT_QK:-1}" == "1" ]]; then
        APPLY_ROPE_FUSION=0
    else
        APPLY_ROPE_FUSION=1
    fi
fi
export APPLY_ROPE_FUSION
if [[ "$USE_STREAMBP" == "1" && "$CP" != "1" ]]; then
    echo "USE_STREAMBP=1 requires CP=1; StreamBP does not yet support context parallelism" >&2
    exit 1
fi
if [[ -z "${DECODER_FIRST_PIPELINE_NUM_LAYERS:-}" ]]; then
    if [[ "$PP" -eq 4 ]]; then
        DECODER_FIRST_PIPELINE_NUM_LAYERS=16
    else
        DECODER_FIRST_PIPELINE_NUM_LAYERS=31
    fi
fi

ENABLE_VPP="${ENABLE_VPP:-1}"
if [[ "$PP" -eq 5 && -z "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" && -z "${NUM_LAYERS_PER_VIRTUAL_PIPELINE_STAGE:-}" && -z "${NUM_VIRTUAL_STAGES_PER_PIPELINE_RANK:-}" ]]; then
    if [[ "$ENABLE_VPP" == "1" ]]; then
        PIPELINE_MODEL_PARALLEL_LAYOUT="Et*7|t*6|t*6|t*6|t*6|t*6|t*6|t*6|t*6|t*6L"
    else
        PIPELINE_MODEL_PARALLEL_LAYOUT="Et*13|t*12|t*12|t*12|t*12L"
    fi
elif [[ "$PP" -eq 4 && -z "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" && -z "${NUM_LAYERS_PER_VIRTUAL_PIPELINE_STAGE:-}" && -z "${NUM_VIRTUAL_STAGES_PER_PIPELINE_RANK:-}" ]]; then
    if [[ "$ENABLE_VPP" == "1" ]]; then
        PIPELINE_MODEL_PARALLEL_LAYOUT="Et*5|t*4|t*4|t*3|t*4|t*4|t*4|t*4|t*4|t*4|t*4|t*4|t*3|t*4|t*3|t*3L"
    else
        PIPELINE_MODEL_PARALLEL_LAYOUT="Et*16|t*15|t*15|t*15L"
    fi
fi
if [[ -z "${OVERLAP_P2P_COMM_WARMUP_FLUSH:-}" ]]; then
    if [[ "$ENABLE_VPP" == "1" ]]; then
        OVERLAP_P2P_COMM_WARMUP_FLUSH=1
    else
        OVERLAP_P2P_COMM_WARMUP_FLUSH=0
    fi
fi

MODEL_PARALLEL_ARGS=(
    --tensor-model-parallel-size "$TP"
    --pipeline-model-parallel-size "$PP"
    --context-parallel-size "$CP"
    --expert-model-parallel-size "$EP"
    --expert-tensor-parallel-size "$ETP"
)
if [[ "${USE_TP_PP_DP_MAPPING:-0}" == "1" ]]; then
    MODEL_PARALLEL_ARGS+=(--use-tp-pp-dp-mapping)
fi

if [[ "${SEQUENCE_PARALLEL:-auto}" == "1" || ( "${SEQUENCE_PARALLEL:-auto}" == "auto" && "$TP" -gt 1 ) ]]; then
    MODEL_PARALLEL_ARGS+=(--sequence-parallel)
fi

if [[ "$PP" -gt 1 && -n "$DECODER_FIRST_PIPELINE_NUM_LAYERS" ]]; then
    if [[ -z "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" ]]; then
        MODEL_PARALLEL_ARGS+=(--decoder-first-pipeline-num-layers "$DECODER_FIRST_PIPELINE_NUM_LAYERS")
    fi
fi
if [[ "$PP" -gt 1 && -n "${DECODER_LAST_PIPELINE_NUM_LAYERS:-}" ]]; then
    if [[ -z "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" ]]; then
        MODEL_PARALLEL_ARGS+=(--decoder-last-pipeline-num-layers "$DECODER_LAST_PIPELINE_NUM_LAYERS")
    fi
fi
if [[ "$PP" -gt 1 && -n "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" ]]; then
    MODEL_PARALLEL_ARGS+=(--pipeline-model-parallel-layout "$PIPELINE_MODEL_PARALLEL_LAYOUT")
fi
if [[ "$PP" -gt 1 && -n "${PIPELINE_PARALLEL_SCHEDULE:-}" ]]; then
    MODEL_PARALLEL_ARGS+=(--pipeline-parallel-schedule "$PIPELINE_PARALLEL_SCHEDULE")
fi
if [[ "${OVERLAP_MOE_EXPERT_PARALLEL_COMM:-0}" == "1" ]]; then
    MODEL_PARALLEL_ARGS+=(--overlap-moe-expert-parallel-comm)
fi
if [[ "${HIGH_PRIORITY_A2A_COMM_STREAM:-0}" == "1" ]]; then
    MODEL_PARALLEL_ARGS+=(--high-priority-a2a-comm-stream)
fi
if [[ "${OVERLAP_P2P_COMM_WARMUP_FLUSH:-1}" == "1" ]]; then
    MODEL_PARALLEL_ARGS+=(--overlap-p2p-communication-warmup-flush)
fi
if [[ "${EP_OVERLAP_EARLY_ATTN_MEMORY_RELEASE:-0}" == "1" ]]; then
    MODEL_PARALLEL_ARGS+=(--ep-overlap-early-attn-memory-release)
fi
if [[ "${DELAY_WGRAD_COMPUTE:-0}" == "1" ]]; then
    MODEL_PARALLEL_ARGS+=(--delay-wgrad-compute)
fi
if [[ "${OVERLAP_DISPATCH_BACKWARD_WITH_EXPERTS_WGRAD:-0}" == "1" ]]; then
    echo "ERROR: OVERLAP_DISPATCH_BACKWARD_WITH_EXPERTS_WGRAD is disabled in this SFT launcher: focused parity still shows BF16 delayed expert-wgrad drift/NaNs with non-fused accumulation." >&2
    exit 1
fi
if [[ -n "${MOE_HYBRIDEP_NUM_SMS_PREPROCESSING:-}" ]]; then
    MODEL_PARALLEL_ARGS+=(--moe-hybridep-num-sms-preprocessing "$MOE_HYBRIDEP_NUM_SMS_PREPROCESSING")
fi
if [[ "$PP" -gt 1 && -n "${NUM_LAYERS_PER_VIRTUAL_PIPELINE_STAGE:-}" ]]; then
    MODEL_PARALLEL_ARGS+=(
        --num-layers-per-virtual-pipeline-stage "$NUM_LAYERS_PER_VIRTUAL_PIPELINE_STAGE"
    )
fi
if [[ "$PP" -gt 1 && -n "${NUM_VIRTUAL_STAGES_PER_PIPELINE_RANK:-}" ]]; then
    MODEL_PARALLEL_ARGS+=(
        --num-virtual-stages-per-pipeline-rank "$NUM_VIRTUAL_STAGES_PER_PIPELINE_RANK"
    )
fi

# ======================
# Model args
# ======================
SEQ_LENGTH="${SEQ_LENGTH:-32768}"
MOE_LAYER_FREQ="${MOE_LAYER_FREQ:-([0]*3+[1]*58)}"

if [[ -z "${STREAMBP_LOCAL_SEQ_LENGTH:-}" ]]; then
    if [[ "${SEQUENCE_PARALLEL:-auto}" == "1" || ( "${SEQUENCE_PARALLEL:-auto}" == "auto" && "$TP" -gt 1 ) ]]; then
        STREAMBP_LOCAL_SEQ_LENGTH=$(( (SEQ_LENGTH + TP - 1) / TP ))
    else
        STREAMBP_LOCAL_SEQ_LENGTH="$SEQ_LENGTH"
    fi
fi
if [[ -z "${STREAMBP_CHUNK_SIZE:-}" ]]; then
    # StreamBP disables itself when there is only one chunk. Default to the
    # smallest active chunking for the local sequence-parallel length.
    STREAMBP_CHUNK_SIZE=$(( (STREAMBP_LOCAL_SEQ_LENGTH + 1) / 2 ))
fi
if (( STREAMBP_CHUNK_SIZE >= STREAMBP_LOCAL_SEQ_LENGTH )); then
    echo "WARNING: STREAMBP_CHUNK_SIZE=$STREAMBP_CHUNK_SIZE >= local sequence length $STREAMBP_LOCAL_SEQ_LENGTH; layer StreamBP will not reduce activation residency" >&2
fi
export MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE="${MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE:-$STREAMBP_CHUNK_SIZE}"

MODEL_ARGS=(
    --use-mcore-models
    --transformer-impl transformer_engine
    --num-layers 61
    --hidden-size 7168
    --ffn-hidden-size 18432
    --num-attention-heads 128
    --kv-channels 128
    --seq-length "$SEQ_LENGTH"
    --max-position-embeddings 163840
    --position-embedding-type rope
    --rope-type yarn
    --rotary-base 10000
    --rotary-percent 1.0
    --rotary-scaling-factor 40
    --mscale 1.0
    --mscale-all-dim 1.0
    --attention-dropout 0.0
    --hidden-dropout 0.0
    --swiglu
    --normalization RMSNorm
    --norm-epsilon 1e-6
    --init-method-std 0.02
    --attention-backend fused
    --attention-softmax-in-fp32
    --qk-layernorm
    --attention-output-gate
    --gated-norm
    --gated-norm-rank 16
    --untie-embeddings-and-output-weights
    --disable-bias-linear
    --bf16
)

# ======================
# MLA + DSA
# ======================
MLA_ARGS=(
    --multi-latent-attention
    --kv-lora-rank 512
    --q-lora-rank 1536
    --qk-head-dim 128
    --qk-pos-emb-head-dim 64
    --v-head-dim 128
)

if [[ -z "${DSA_CHUNK_SIZE:-}" ]]; then
    DSA_CHUNK_SIZE="${DSA_STREAMBP_CHUNK_SIZE:-$STREAMBP_CHUNK_SIZE}"
fi

DSA_ARGS=(
    --experimental-attention-variant dsa
    --dsa-indexer-n-heads 64
    --dsa-indexer-head-dim 128
    --dsa-indexer-topk "${DSA_INDEXER_TOPK:-1024}"
    --dsa-indexer-loss-coeff "${DSA_INDEXER_LOSS_COEFF:-0.1}"
    --dsa-chunk-size "$DSA_CHUNK_SIZE"
)
if [[ "$APPLY_ROPE_FUSION" != "1" ]]; then
    MODEL_ARGS+=(--no-rope-fusion)
fi

# ======================
# MoE
# ======================
MOE_ARGS=(
    --num-experts 128
    --moe-layer-freq "$MOE_LAYER_FREQ"
    --moe-ffn-hidden-size 2048
    --moe-shared-expert-intermediate-size 2048
    --moe-router-load-balancing-type "${MOE_ROUTER_LOAD_BALANCING_TYPE:-seq_aux_loss}"
    --moe-router-topk 8
    --moe-router-topk-scaling-factor 2.5
    --moe-router-num-groups 8
    --moe-router-group-topk 4
    --moe-router-pre-softmax
    --moe-router-score-function sigmoid
    --moe-router-enable-expert-bias
    --moe-router-bias-update-rate "${MOE_ROUTER_BIAS_UPDATE_RATE:-1e-3}"
    --moe-router-expert-bias-update-method "${MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD:-sign}"
    --moe-router-quantile-bias-iters "${MOE_ROUTER_QUANTILE_BIAS_ITERS:-5}"
    --moe-router-quantile-bias-application "${MOE_ROUTER_QUANTILE_BIAS_APPLICATION:-delayed}"
    --moe-router-quantile-bias-warmup-steps "${MOE_ROUTER_QUANTILE_BIAS_WARMUP_STEPS:-0}"
    --moe-router-dtype fp32
    --moe-aux-loss-coeff "${MOE_AUX_LOSS_COEFF:-0.0}"
    --moe-token-dispatcher-type "$MOE_TOKEN_DISPATCHER_TYPE"
)

if [[ "$MOE_TOKEN_DISPATCHER_TYPE" == "flex" ]]; then
    MOE_ARGS+=(--moe-flex-dispatcher-backend "$MOE_FLEX_DISPATCHER_BACKEND")
fi

if [[ "${MOE_GROUPED_GEMM:-1}" == "1" ]]; then
    MOE_ARGS+=(--moe-grouped-gemm)
fi
if [[ "${MOE_PERMUTE_FUSION:-1}" == "1" ]]; then
    MOE_ARGS+=(--moe-permute-fusion)
fi
if [[ "${MOE_PER_LAYER_LOGGING:-1}" == "1" ]]; then
    MOE_ARGS+=(--moe-per-layer-logging)
fi
if [[ "${MOE_ROUTER_PADDING_FOR_QUANTIZATION:-0}" == "1" ]]; then
    MOE_ARGS+=(--moe-router-padding-for-quantization)
fi
if [[ "${MOE_ROUTER_QUANTILE_BIAS_SYNC_SCORES:-1}" == "0" ]]; then
    MOE_ARGS+=(--no-moe-router-quantile-bias-sync-scores)
fi
if [[ -n "${MOE_EXPERT_CAPACITY_FACTOR:-}" ]]; then
    MOE_ARGS+=(--moe-expert-capacity-factor "$MOE_EXPERT_CAPACITY_FACTOR")
fi
if [[ "${MOE_PAD_EXPERT_INPUT_TO_CAPACITY:-0}" == "1" ]]; then
    MOE_ARGS+=(--moe-pad-expert-input-to-capacity)
fi

# ======================
# NVFP4, SpinQuant, TurboQuant, IndexCache
# ======================
export SPINQUANT="${SPINQUANT:-1}"
export USE_HIGGS="${USE_HIGGS:-1}"
export HIGGS_KV_PRESET="${HIGGS_KV_PRESET:-dense_2bit}"
export TURBOQUANT="${TURBOQUANT:-0}"
export INDEXCACHE="${INDEXCACHE:-1}"
export DSA_INDEXCACHE_HISA="${DSA_INDEXCACHE_HISA:-1}"
export DSA_INDEXCACHE_QUANTIZATION="${DSA_INDEXCACHE_QUANTIZATION:-nvfp4_e2m1_ue8m0}"
export DSA_INDEXCACHE_QUANT_EPS="${DSA_INDEXCACHE_QUANT_EPS:-1e-4}"
export DSA_INDEXCACHE_HISA_BLOCK_SIZE="${DSA_INDEXCACHE_HISA_BLOCK_SIZE:-128}"
export DSA_INDEXCACHE_HISA_BLOCK_TOPK="${DSA_INDEXCACHE_HISA_BLOCK_TOPK:-64}"
export DSA_INDEXCACHE_HISA_COMPRESSION_RATIO="${DSA_INDEXCACHE_HISA_COMPRESSION_RATIO:-8.0}"

DTYPE_ARGS=(
    --fp4-format e2m1
    --fp4-recipe nvfp4
    --fp4-param-gather
)

SPINQUANT_ARGS=()
if [[ "${SPINQUANT:-1}" == "1" ]]; then
    SPINQUANT_ARGS+=(
        --spinquant
        --spinquant-mode "${SPINQUANT_MODE:-random}"
        --spinquant-w-bits 4
        --spinquant-a-bits 4
        --spinquant-k-bits 4
        --spinquant-v-bits 4
    )
    if [[ "${SPINQUANT_FUSE_WEIGHTS:-0}" == "1" ]]; then
        SPINQUANT_ARGS+=(--spinquant-fuse-weights)
    fi
    if [[ -n "${SPINQUANT_ROTATION_PATH:-}" ]]; then
        SPINQUANT_ARGS+=(--spinquant-rotation-path "$SPINQUANT_ROTATION_PATH")
    fi
fi

TURBOQUANT_ARGS=()
if [[ "${TURBOQUANT:-0}" == "1" ]]; then
    TURBOQUANT_ARGS+=(
        --turboquant-kv-enabled
        --turboquant-kv-preset "${TURBOQUANT_KV_PRESET:-latent_2p5bit_nc}"
        --turboquant-kv-seed "${TURBOQUANT_KV_SEED:-0}"
    )
fi

HIGGS_ARGS=()
if [[ "${USE_HIGGS:-0}" == "1" ]]; then
    HIGGS_ARGS+=(
        --enable-higgs-dense-2bit-kv-cache
        --higgs-kv-preset "${HIGGS_KV_PRESET:-dense_2bit}"
    )
fi

INDEXCACHE_ARGS=()
if [[ "${INDEXCACHE:-1}" == "1" ]]; then
    INDEXCACHE_QUANT_METHOD="$DSA_INDEXCACHE_QUANTIZATION"
    INDEXCACHE_ARGS+=(
        --dsa-indexcache-quantization "${INDEXCACHE_QUANT_METHOD}"
        --dsa-indexcache-quant-eps "${DSA_INDEXCACHE_QUANT_EPS:-1e-4}"
    )
    if [[ "${DSA_INDEXCACHE_HISA:-0}" == "1" ]]; then
        INDEXCACHE_ARGS+=(
            --dsa-indexcache-hisa-enabled
            --dsa-indexcache-hisa-block-size "${DSA_INDEXCACHE_HISA_BLOCK_SIZE:-128}"
            --dsa-indexcache-hisa-block-topk "${DSA_INDEXCACHE_HISA_BLOCK_TOPK:-64}"
            --dsa-indexcache-hisa-compression-ratio "${DSA_INDEXCACHE_HISA_COMPRESSION_RATIO:-8.0}"
        )
    fi
fi

# ======================
# Training
# ======================
MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-4}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-16}"
round_samples_to_updates() {
    local raw_samples="$1"
    local batch_size="$2"
    echo $(( ((raw_samples + batch_size - 1) / batch_size) * batch_size ))
}
TRAIN_TOKEN_TARGET="${TRAIN_TOKEN_TARGET:-24691703808}"
if [[ -z "${TRAIN_SAMPLES:-}" ]]; then
    RAW_TRAIN_SAMPLES=$(( (TRAIN_TOKEN_TARGET + SEQ_LENGTH - 1) / SEQ_LENGTH ))
    TRAIN_SAMPLES="$(round_samples_to_updates "$RAW_TRAIN_SAMPLES" "$GLOBAL_BATCH_SIZE")"
fi
LR_DECAY_SAMPLES="${LR_DECAY_SAMPLES:-$TRAIN_SAMPLES}"
LR_WARMUP_TOKEN_TARGET="${LR_WARMUP_TOKEN_TARGET:-$((TRAIN_TOKEN_TARGET / 20))}"
if [[ -z "${LR_WARMUP_SAMPLES:-}" ]]; then
    RAW_WARMUP_SAMPLES=$(( (LR_WARMUP_TOKEN_TARGET + SEQ_LENGTH - 1) / SEQ_LENGTH ))
    LR_WARMUP_SAMPLES="$(round_samples_to_updates "$RAW_WARMUP_SAMPLES" "$GLOBAL_BATCH_SIZE")"
fi
LR="${LR:-5.0e-6}"
MIN_LR="${MIN_LR:-$LR}"

TRAINING_ARGS=(
    --micro-batch-size "$MICRO_BATCH_SIZE"
    --global-batch-size "$GLOBAL_BATCH_SIZE"
    --train-samples "$TRAIN_SAMPLES"
    --lr-decay-samples "$LR_DECAY_SAMPLES"
    --lr-warmup-samples "$LR_WARMUP_SAMPLES"
    --lr "$LR"
    --min-lr "$MIN_LR"
    --lr-decay-style "${LR_DECAY_STYLE:-cosine}"
    --clip-grad "${CLIP_GRAD:-1.0}"
    --weight-decay "${WEIGHT_DECAY:-0.0}"
    --adam-beta1 "${ADAM_BETA1:-0.9}"
    --adam-beta2 "${ADAM_BETA2:-0.95}"
    --adam-eps "${ADAM_EPS:-1.0e-6}"
    --log-interval "${LOG_INTERVAL:-10}"
    --empty-unused-memory-level "${EMPTY_UNUSED_MEMORY_LEVEL:-0}"
    --rerun-mode "${RERUN_MODE:-disabled}"
    --optimizer flash_adamw
    --use-distributed-optimizer
    --no-gradient-accumulation-fusion
)
if [[ "${CALCULATE_PER_TOKEN_LOSS:-1}" == "1" ]]; then
    TRAINING_ARGS+=(--calculate-per-token-loss)
fi

if [[ "${FLASH_ADAMW_ECO:-0}" == "1" ]]; then
    TRAINING_ARGS+=(--flash-adamw-eco)
fi
if [[ "${FLASH_ADAMW_FSDP_ECO_INJECT:-0}" == "1" ]]; then
    TRAINING_ARGS+=(--flash-adamw-fsdp-eco-inject)
fi
if [[ "${OVERLAP_GRAD_REDUCE:-1}" == "1" ]]; then
    TRAINING_ARGS+=(--overlap-grad-reduce)
fi
if [[ "${OVERLAP_PARAM_GATHER:-1}" == "1" ]]; then
    TRAINING_ARGS+=(--overlap-param-gather)
fi
if [[ "${GRAD_REDUCE_IN_BF16:-1}" == "1" ]]; then
    TRAINING_ARGS+=(--grad-reduce-in-bf16)
fi
if [[ "${FLASH_ADAMW_COMPRESS_STATE_DICT:-1}" == "1" ]]; then
    TRAINING_ARGS+=(--flash-adamw-compress-state-dict)
fi
if [[ "${MEGATRON_DISABLE_JIT_FUSER:-0}" == "1" ]]; then
    TRAINING_ARGS+=(--disable-jit-fuser)
fi

STREAMBP_ARGS=()
if [[ "$USE_STREAMBP" == "1" ]]; then
    if [[ "$RECOMPUTE" == "1" ]]; then
        if [[ "${RECOMPUTE_GRANULARITY:-full}" != "selective" ]]; then
            echo "USE_STREAMBP=1 is incompatible with full activation recompute; use RECOMPUTE_GRANULARITY=selective or set RECOMPUTE=0" >&2
            exit 1
        fi
    fi
    STREAMBP_ARGS+=(--use-streambp)
    if [[ -n "${STREAMBP_CHUNK_SIZE:-}" ]]; then
        STREAMBP_ARGS+=(--streambp-chunk-size "$STREAMBP_CHUNK_SIZE")
    fi
    if [[ -n "${STREAMBP_LOGITS_CHUNK_SIZE:-}" ]]; then
        STREAMBP_ARGS+=(--streambp-logits-chunk-size "$STREAMBP_LOGITS_CHUNK_SIZE")
    fi
    if [[ -n "${STREAMBP_CHUNK_FORWARD:-}" ]]; then
        if [[ "$STREAMBP_CHUNK_FORWARD" == "1" ]]; then
            STREAMBP_ARGS+=(--streambp-chunk-forward)
        else
            STREAMBP_ARGS+=(--no-streambp-chunk-forward)
        fi
    fi
    if [[ -n "${STREAMBP_MOE_CHUNK_FORWARD:-}" ]]; then
        if [[ "$STREAMBP_MOE_CHUNK_FORWARD" == "1" ]]; then
            STREAMBP_ARGS+=(--streambp-moe-chunk-forward)
        else
            STREAMBP_ARGS+=(--no-streambp-moe-chunk-forward)
        fi
    fi
    if [[ -n "${STREAMBP_MOE_MLP_CHUNKS:-}" ]]; then
        STREAMBP_ARGS+=(--streambp-moe-mlp-chunks "$STREAMBP_MOE_MLP_CHUNKS")
    fi
    if [[ -n "${STREAMBP_MOE_MLP_BACKWARD_CHUNKS:-}" ]]; then
        STREAMBP_ARGS+=(
            --streambp-moe-mlp-backward-chunks "$STREAMBP_MOE_MLP_BACKWARD_CHUNKS"
        )
    fi
    if [[ "${STREAMBP_SKIP_MOE:-0}" == "1" ]]; then
        STREAMBP_ARGS+=(--streambp-skip-moe)
    else
        STREAMBP_ARGS+=(--no-streambp-skip-moe)
    fi
    if [[ "${STREAMBP_SKIP_DSA:-0}" == "1" ]]; then
        STREAMBP_ARGS+=(--streambp-skip-dsa)
    else
        STREAMBP_ARGS+=(--no-streambp-skip-dsa)
    fi
    if [[ "${STREAMBP_VALIDATE:-0}" == "1" ]]; then
        STREAMBP_ARGS+=(--streambp-validate)
    fi
    if [[ "${STREAMBP_PROFILE:-0}" == "1" ]]; then
        STREAMBP_ARGS+=(--streambp-profile)
        STREAMBP_ARGS+=(--streambp-profile-rank "${STREAMBP_PROFILE_RANK:-0}")
        STREAMBP_ARGS+=(--streambp-profile-limit "${STREAMBP_PROFILE_LIMIT:-4}")
        if [[ -n "${STREAMBP_PROFILE_DIR:-}" ]]; then
            STREAMBP_ARGS+=(--streambp-profile-dir "$STREAMBP_PROFILE_DIR")
        fi
        if [[ -n "${STREAMBP_PROFILE_FILTER:-}" ]]; then
            STREAMBP_ARGS+=(--streambp-profile-filter "$STREAMBP_PROFILE_FILTER")
        fi
        if [[ "${STREAMBP_PROFILE_RECORD_SHAPES:-0}" == "1" ]]; then
            STREAMBP_ARGS+=(--streambp-profile-record-shapes)
        fi
        if [[ "${STREAMBP_PROFILE_WITH_STACK:-0}" == "1" ]]; then
            STREAMBP_ARGS+=(--streambp-profile-with-stack)
        fi
    fi
fi

ZCC_ARGS=()
if [[ "${ENABLE_ZCC:-0}" == "1" ]]; then
    export MEGATRON_FLASH_FUSE_STATE_BUFFER="${MEGATRON_FLASH_FUSE_STATE_BUFFER:-0}"
    ZCC_ARGS+=(
        --enable-zero-cost-checkpoint
        --zcc-workers-num "${ZCC_WORKERS_NUM:-1}"
        --zcc-flash-device "${ZCC_FLASH_DEVICE:-/dev/shm/megatron_zcc}"
        --zcc-durable-interval "${ZCC_DURABLE_INTERVAL:-10}"
        --zcc-compress "${ZCC_COMPRESS:-zstd:1}"
        --zcc-retain-latest "${ZCC_RETAIN_LATEST:-1}"
    )
    if [[ -n "${ZCC_FLASH_STRIPE:-}" ]]; then
        ZCC_ARGS+=(--zcc-flash-stripe "$ZCC_FLASH_STRIPE")
    fi
    if [[ -n "${ZCC_DURABLE_DIR:-}" ]]; then
        ZCC_ARGS+=(--zcc-durable-dir "$ZCC_DURABLE_DIR")
    fi
    if [[ -n "${ZCC_EXTRA_TENSOR_ATTRS:-}" ]]; then
        ZCC_ARGS+=(--zcc-extra-tensor-attrs "$ZCC_EXTRA_TENSOR_ATTRS")
    fi
fi

FSDP_ARGS=()
if [[ "$USE_MEGATRON_FSDP" == "1" ]]; then
    FSDP_ARGS+=(
        --use-megatron-fsdp
        --data-parallel-sharding-strategy "${DATA_PARALLEL_SHARDING_STRATEGY:-optim_grads_params}"
    )
    if [[ "${FSDP_INIT_MODEL_WITH_META_DEVICE:-1}" == "1" ]]; then
        FSDP_ARGS+=(--init-model-with-meta-device)
    fi
    if [[ "${FSDP_USE_NCCL_UB:-0}" == "1" ]]; then
        FSDP_ARGS+=(--use-nccl-ub)
    fi
    if [[ "${FSDP_DOUBLE_BUFFER:-0}" == "1" ]]; then
        FSDP_ARGS+=(--fsdp-double-buffer)
    fi
    if [[ "${FSDP_CREATE_ALL_GATHER_GROUP:-0}" == "1" ]]; then
        FSDP_ARGS+=(--create-all-gather-group)
    fi
    if [[ "${FSDP_MANUAL_REGISTRATION:-0}" == "1" ]]; then
        FSDP_ARGS+=(--fsdp-manual-registration)
    fi
    if [[ "${FSDP_DISABLE_SYMMETRIC_REGISTRATION:-0}" == "1" ]]; then
        FSDP_ARGS+=(--disable-symmetric-registration)
    fi
    if [[ -n "${SUGGESTED_COMMUNICATION_UNIT_SIZE:-}" ]]; then
        FSDP_ARGS+=(--suggested-communication-unit-size "$SUGGESTED_COMMUNICATION_UNIT_SIZE")
    fi
fi

RECOMPUTE_ARGS=()
if [[ "${RECOMPUTE:-0}" == "1" ]]; then
    RECOMPUTE_ARGS+=(
        --recompute-granularity "${RECOMPUTE_GRANULARITY:-full}"
    )
    if [[ "${RECOMPUTE_GRANULARITY:-full}" == "selective" ]]; then
        RECOMPUTE_MODULES_VALUE="${RECOMPUTE_MODULES:-core_attn}"
        # shellcheck disable=SC2206
        RECOMPUTE_MODULE_LIST=(${RECOMPUTE_MODULES_VALUE})
        RECOMPUTE_ARGS+=(--recompute-modules "${RECOMPUTE_MODULE_LIST[@]}")
    else
        RECOMPUTE_ARGS+=(
            --recompute-method "${RECOMPUTE_METHOD:-uniform}"
            --recompute-num-layers "${RECOMPUTE_NUM_LAYERS:-1}"
        )
    fi
fi

OFFLOAD_ARGS=()
if [[ "${FINE_GRAINED_ACTIVATION_OFFLOADING:-0}" == "1" ]]; then
    if [[ -z "${OFFLOAD_MODULES:-}" ]]; then
        echo "FINE_GRAINED_ACTIVATION_OFFLOADING=1 requires OFFLOAD_MODULES" >&2
        exit 1
    fi
    # shellcheck disable=SC2206
    OFFLOAD_MODULE_LIST=(${OFFLOAD_MODULES})
    OFFLOAD_ARGS+=(
        --fine-grained-activation-offloading
        --offload-modules "${OFFLOAD_MODULE_LIST[@]}"
    )
    if [[ -n "${MIN_OFFLOADED_TENSOR_SIZE:-}" ]]; then
        OFFLOAD_ARGS+=(--min-offloaded-tensor-size "$MIN_OFFLOADED_TENSOR_SIZE")
    fi
fi

ACTIVATION_ECO_ARGS=()
if [[ "${NVFP4_ACTIVATION_ECO:-0}" == "1" ]]; then
    ACTIVATION_ECO_ARGS+=(--nvfp4-activation-eco)
    ACT_ECO_MODULES_VALUE="${NVFP4_ACTIVATION_ECO_MODULES:-all}"
    # shellcheck disable=SC2206
    ACT_ECO_MODULE_LIST=(${ACT_ECO_MODULES_VALUE})
    if ((${#ACT_ECO_MODULE_LIST[@]} == 0)); then
        echo "NVFP4_ACTIVATION_ECO=1 requires NVFP4_ACTIVATION_ECO_MODULES to name at least one module" >&2
        exit 1
    fi
    ACTIVATION_ECO_ARGS+=(--nvfp4-activation-eco-modules "${ACT_ECO_MODULE_LIST[@]}")
    if [[ "${NVFP4_ACTIVATION_ECO_RECOMPUTE_ONLY:-1}" == "0" ]]; then
        ACTIVATION_ECO_ARGS+=(--no-nvfp4-activation-eco-recompute-only)
    fi
    ACTIVATION_ECO_ARGS+=(
        --nvfp4-activation-eco-quantizer-backend "${NVFP4_ACTIVATION_ECO_QUANTIZER_BACKEND:-te}"
        --nvfp4-activation-eco-correction-dtype "${NVFP4_ACTIVATION_ECO_CORRECTION_DTYPE:-bf16}"
    )
fi

# ======================
# SFT + tokenizer
# ======================
SFT_ARGS=(
    --sft
    --sft-tokenizer-prompt-format deepseek-v3.2
)
if [[ "${SFT_FINETUNE:-1}" == "1" ]]; then
    SFT_ARGS+=(--finetune)
fi

TOKENIZER_ARGS=(
    --tokenizer-type SFTTokenizer
    --tokenizer-model "$TOKENIZER_MODEL"
    --padded-vocab-size 129280
)

# ======================
# Data
# ======================
DATA_ARGS=(
    --data-path "$DATA_PATH"
    --split 100,0,0
    --dataloader-type "${DATALOADER_TYPE:-cyclic}"
    --no-create-attention-mask-in-dataloader
    --no-mmap-bin-files
    --num-workers "${NUM_WORKERS:-1}"
)

# ======================
# Logging, profiling, checkpointing
# ======================
TENSORBOARD_ARGS=()
if [[ "${ENABLE_TENSORBOARD_LOGGING:-1}" == "1" ]]; then
    TENSORBOARD_ARGS+=(
        --tensorboard-dir "$TENSORBOARD_LOGS_PATH"
        --tensorboard-log-interval "${TENSORBOARD_LOG_INTERVAL:-10}"
    )
    if [[ "${LOG_THROUGHPUT:-1}" == "1" ]]; then
        TENSORBOARD_ARGS+=(--log-throughput)
    fi
    if [[ "${LOG_MEMORY_TO_TENSORBOARD:-1}" == "1" ]]; then
        TENSORBOARD_ARGS+=(--log-memory-to-tensorboard)
    fi
    if [[ "${LOG_WORLD_SIZE_TO_TENSORBOARD:-1}" == "1" ]]; then
        TENSORBOARD_ARGS+=(--log-world-size-to-tensorboard)
    fi
    if [[ "${LOG_TIMERS_TO_TENSORBOARD:-1}" == "1" ]]; then
        TENSORBOARD_ARGS+=(
            --log-timers-to-tensorboard
            --timing-log-level "${TIMING_LOG_LEVEL:-1}"
            --timing-log-option "${TIMING_LOG_OPTION:-minmax}"
        )
    fi
    if [[ -n "${LOG_MEMORY_INTERVAL:-}" ]]; then
        TENSORBOARD_ARGS+=(--log-memory-interval "$LOG_MEMORY_INTERVAL")
    fi
fi
if [[ "${LOG_PARAMS_NORM:-0}" == "1" ]]; then
    TENSORBOARD_ARGS+=(--log-params-norm)
fi
if [[ "${LOG_NUM_ZEROS_IN_GRAD:-0}" == "1" ]]; then
    TENSORBOARD_ARGS+=(--log-num-zeros-in-grad)
fi
if [[ "${LOG_MAX_ATTENTION_LOGIT:-0}" == "1" ]]; then
    TENSORBOARD_ARGS+=(--log-max-attention-logit)
fi
if [[ "${LOG_ENERGY:-0}" == "1" ]]; then
    TENSORBOARD_ARGS+=(--log-energy)
fi

# Offline is the default for every training run. To intentionally publish live,
# set both WANDB_FORCE_OFFLINE=0 and WANDB_MODE=online at launch.
export WANDB_FORCE_OFFLINE="${WANDB_FORCE_OFFLINE:-1}"
if [[ "$WANDB_FORCE_OFFLINE" == "1" ]]; then
    export WANDB_MODE=offline
else
    export WANDB_MODE="${WANDB_MODE:-offline}"
fi

WANDB_ARGS=()
if [[ -n "${WANDB_PROJECT:-}" ]]; then
    WANDB_ARGS+=(
        --wandb-project "$WANDB_PROJECT"
        --wandb-exp-name "${WANDB_EXP_NAME:-sft_deepseek_v32_reap_nvfp4}"
        --wandb-save-dir "${WANDB_SAVE_DIR:-"$SAVE_CKPT/wandb"}"
    )
    if [[ -n "${WANDB_ENTITY:-}" ]]; then
        WANDB_ARGS+=(--wandb-entity "$WANDB_ENTITY")
    fi
fi

ONE_LOGGER_ARGS=()
if [[ "${ENABLE_ONE_LOGGER:-1}" == "0" ]]; then
    ONE_LOGGER_ARGS+=(--no-one-logger)
else
    if [[ -n "${ONE_LOGGER_PROJECT:-}" ]]; then
        ONE_LOGGER_ARGS+=(--one-logger-project "$ONE_LOGGER_PROJECT")
    fi
    if [[ -n "${ONE_LOGGER_RUN_NAME:-}" ]]; then
        ONE_LOGGER_ARGS+=(--one-logger-run-name "$ONE_LOGGER_RUN_NAME")
    fi
    if [[ "${ONE_LOGGER_ASYNC:-0}" == "1" ]]; then
        ONE_LOGGER_ARGS+=(--one-logger-async)
    fi
fi

PROFILING_ARGS=()
if [[ "${ENABLE_PROFILING:-0}" == "1" ]]; then
    PROFILING_ARGS+=(
        --profile
        --profile-step-start "${PROFILE_STEP_START:-4}"
        --profile-step-end "${PROFILE_STEP_END:-6}"
    )
    if [[ "${USE_PYTORCH_PROFILER:-0}" == "1" ]]; then
        PROFILING_ARGS+=(--use-pytorch-profiler)
    fi
    if [[ "${PYTORCH_PROFILER_COLLECT_SHAPES:-0}" == "1" ]]; then
        PROFILING_ARGS+=(--pytorch-profiler-collect-shapes)
    fi
    if [[ "${PYTORCH_PROFILER_COLLECT_CALLSTACK:-0}" == "1" ]]; then
        PROFILING_ARGS+=(--pytorch-profiler-collect-callstack)
    fi
    if [[ "${PYTORCH_PROFILER_COLLECT_CHAKRA:-0}" == "1" ]]; then
        PROFILING_ARGS+=(--pytorch-profiler-collect-chakra)
    fi
    if [[ "${PYTORCH_PROFILER_PROFILE_MEMORY:-0}" == "1" ]]; then
        PROFILING_ARGS+=(--pytorch-profiler-profile-memory)
    fi
    if [[ "${PYTORCH_PROFILER_WITH_FLOPS:-0}" == "1" ]]; then
        PROFILING_ARGS+=(--pytorch-profiler-with-flops)
    fi
    if [[ "${PYTORCH_PROFILER_WITH_MODULES:-0}" == "1" ]]; then
        PROFILING_ARGS+=(--pytorch-profiler-with-modules)
    fi
    if [[ -n "${PROFILE_RANKS:-}" ]]; then
        # shellcheck disable=SC2206
        PROFILE_RANK_ARGS=(${PROFILE_RANKS//,/ })
        PROFILING_ARGS+=(--profile-ranks "${PROFILE_RANK_ARGS[@]}")
    fi
fi

if [[ "$USE_MEGATRON_FSDP" == "1" ]]; then
    CKPT_FORMAT_VALUE="${CKPT_FORMAT:-fsdp_dtensor}"
else
    CKPT_FORMAT_VALUE="${CKPT_FORMAT:-torch_dist}"
fi

CKPT_ARGS=(
    --eval-interval "${EVAL_INTERVAL:-100}"
    --eval-iters "${EVAL_ITERS:-0}"
    --load "$LOAD_CKPT"
    --distributed-timeout-minutes "$DISTRIBUTED_TIMEOUT_MINUTES"
    --ckpt-format "$CKPT_FORMAT_VALUE"
    --auto-detect-ckpt-format
)
if [[ "${CKPT_FULLY_PARALLEL_LOAD:-1}" == "1" ]]; then
    CKPT_ARGS+=(
        --ckpt-fully-parallel-load
        --ckpt-fully-parallel-load-process-group "${CKPT_FULLY_PARALLEL_LOAD_PROCESS_GROUP:-dp}"
        --ckpt-fully-parallel-load-exchange-algo "${CKPT_FULLY_PARALLEL_LOAD_EXCHANGE_ALGO:-broadcast}"
    )
fi
if [[ "${DISABLE_SAVE:-0}" != "1" ]]; then
    CKPT_ARGS+=(
        --save-interval "${SAVE_INTERVAL:-500}"
        --save "$SAVE_CKPT"
    )
    if [[ -n "${SAVE_RETAIN_INTERVAL:-}" ]]; then
        CKPT_ARGS+=(--save-retain-interval "$SAVE_RETAIN_INTERVAL")
    fi
fi
if [[ "${NO_SAVE_OPTIM:-0}" == "1" ]]; then
    CKPT_ARGS+=(--no-save-optim)
fi
if [[ "${NO_SAVE_RNG:-0}" == "1" ]]; then
    CKPT_ARGS+=(--no-save-rng)
fi

EXTRA_MEGATRON_ARGS_ARRAY=()
if [[ -n "${EXTRA_MEGATRON_ARGS:-}" ]]; then
    # shellcheck disable=SC2206
    EXTRA_MEGATRON_ARGS_ARRAY=(${EXTRA_MEGATRON_ARGS})
fi

CMD=(
    uv run --no-sync torchrun
    "${TORCHRUN_LOG_ARGS[@]}"
    "${DISTRIBUTED_ARGS[@]}"
    pretrain_gpt.py
    "${DISTRIBUTED_BACKEND_ARGS[@]}"
    "${MODEL_ARGS[@]}"
    "${MLA_ARGS[@]}"
    "${DSA_ARGS[@]}"
    "${MOE_ARGS[@]}"
    "${MODEL_PARALLEL_ARGS[@]}"
    "${TRAINING_ARGS[@]}"
    "${STREAMBP_ARGS[@]}"
    "${ZCC_ARGS[@]}"
    "${FSDP_ARGS[@]}"
    "${RECOMPUTE_ARGS[@]}"
    "${OFFLOAD_ARGS[@]}"
    "${ACTIVATION_ECO_ARGS[@]}"
    "${DTYPE_ARGS[@]}"
    "${SPINQUANT_ARGS[@]}"
    "${TURBOQUANT_ARGS[@]}"
    "${HIGGS_ARGS[@]}"
    "${INDEXCACHE_ARGS[@]}"
    "${SFT_ARGS[@]}"
    "${TOKENIZER_ARGS[@]}"
    "${DATA_ARGS[@]}"
    "${TENSORBOARD_ARGS[@]}"
    "${WANDB_ARGS[@]}"
    "${ONE_LOGGER_ARGS[@]}"
    "${PROFILING_ARGS[@]}"
    "${CKPT_ARGS[@]}"
    "${EXTRA_MEGATRON_ARGS_ARRAY[@]}"
)

if [[ "${DRY_RUN:-0}" == "1" ]]; then
    printf '%q ' "${CMD[@]}"
    printf '\n'
    exit 0
fi

prebuild_torch_cuda_ext() {
    local label="$1"
    local ext_name="$2"
    local module="$3"
    local ext_root="${TORCH_EXTENSIONS_DIR:-$HOME/.cache/torch_extensions/py312_cu130}"
    local ext_dir="$ext_root/$ext_name"

    if [[ -f "$ext_dir/lock" && ! -f "$ext_dir/$ext_name.so" ]]; then
        echo "Removing stale $label CUDA extension lock at $ext_dir/lock" >&2
        rm -f "$ext_dir/lock"
    fi
    echo "Prebuilding/loading $label CUDA extension before torchrun..." >&2
    CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}" \
    TORCH_CUDA_ARCH_LIST="${TORCH_CUDA_ARCH_LIST:-10.0}" \
    PREBUILD_EXT_LABEL="$label" \
    PREBUILD_EXT_MODULE="$module" \
    uv run --no-sync python - <<'PY'
import importlib
import os

label = os.environ["PREBUILD_EXT_LABEL"]
module = importlib.import_module(os.environ["PREBUILD_EXT_MODULE"])
get_ext = getattr(module, "get_ext")
get_ext()
print(f"{label} CUDA extension ready", flush=True)
PY
}

if [[ "${PREBUILD_HISA_EXT:-1}" == "1" && "${INDEXCACHE:-1}" == "1" ]]; then
    prebuild_torch_cuda_ext \
        "HISA" \
        "megatron_hisa_indexer" \
        "megatron.core.extensions.hisa_indexer.kernels.build"
fi

if [[ "${PREBUILD_QUANT_EXTS:-1}" == "1" ]]; then
    if [[ "${USE_HIGGS:-1}" == "1" ]]; then
        prebuild_torch_cuda_ext \
            "HIGGS" \
            "megatron_higgs_kv" \
            "megatron.core.quantization.higgs.kernels.build"
    fi
    if [[ "${INDEXCACHE:-1}" == "1" ]]; then
        prebuild_torch_cuda_ext \
            "IndexCache" \
            "megatron_indexcache_kv" \
            "megatron.core.quantization.indexcache.kernels.build"
    fi
    if [[ "${TURBOQUANT:-0}" == "1" ]]; then
        prebuild_torch_cuda_ext \
            "TurboQuant" \
            "megatron_turboquant_kv" \
            "megatron.core.quantization.turboquant.kernels.build"
    fi
fi

if [[ -n "${SLURM_JOB_ID:-}" && "${USE_SRUN:-1}" == "1" ]]; then
    if [[ "${SUPPRESS_UNBATCHED_P2P_WARN:-1}" == "1" ]]; then
        srun --mpi=pmix -l "${CMD[@]}" 2> >(grep -Fv "Warning: An unbatched P2P op (send/recv) was called on this ProcessGroup" >&2)
    else
        srun --mpi=pmix -l "${CMD[@]}"
    fi
else
    if [[ "${SUPPRESS_UNBATCHED_P2P_WARN:-1}" == "1" ]]; then
        "${CMD[@]}" 2> >(grep -Fv "Warning: An unbatched P2P op (send/recv) was called on this ProcessGroup" >&2)
    else
        "${CMD[@]}"
    fi
fi
