#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="${REPO_DIR:-"$(cd "$SCRIPT_DIR/../../.." && pwd)"}"
cd "$REPO_DIR"

GPUS_PER_NODE="${GPUS_PER_NODE:-8}"
# Baseline 12x8 A4 shape after the pipeline warmup residency audit:
# TP8 x CP4 keeps the full model on each data-parallel replica with Megatron
# FSDP sharding params/grads/optimizer state across DP=3. PP is kept at 1
# because every tested 32k DSA/HISA VPP/PP warmup shape OOMed before steady
# state, while this no-PP shape completed cleanly.
TP="${TP:-8}"
PP="${PP:-1}"
CP="${CP:-4}"
EP="${EP:-8}"
ETP="${ETP:-1}"
STRICT_ALL_NODES="${STRICT_ALL_NODES:-1}"
MAX_NODES="${MAX_NODES:-12}"

MODEL_PARALLEL_SIZE=$((TP * PP * CP))
EXPERT_MODEL_PARALLEL_SIZE=$((ETP * EP * PP))

names=()
ips=()
if [[ -n "${SLURM_JOB_NODELIST:-}" && "${FORCE_GCLOUD_DISCOVERY:-0}" != "1" ]]; then
  mapfile -t names < <(scontrol show hostnames "$SLURM_JOB_NODELIST")
  for name in "${names[@]}"; do
    ip="$(scontrol show node "$name" | awk '{for (i=1; i<=NF; i++) if ($i ~ /^NodeAddr=/) {sub(/^NodeAddr=/, "", $i); print $i; exit}}')"
    ips+=("${ip:-$name}")
  done
else
  mapfile -t rows < <(OUTPUT=csv "$SCRIPT_DIR/discover_nodes.sh" | tail -n +2)
  if (( ${#rows[@]} == 0 )); then
    echo "No running nodes matched INSTANCE_REGEX=${INSTANCE_REGEX:-^instance-group-1-} in ZONE=${ZONE:-us-east1-b}" >&2
    exit 2
  fi
  for row in "${rows[@]}"; do
    IFS=, read -r _rank name internal_ip _nat_ip <<<"$row"
    names+=("$name")
    ips+=("$internal_ip")
  done
fi

discovered_count="${#names[@]}"
if [[ -n "$MAX_NODES" ]]; then
  use_count="$MAX_NODES"
  if (( use_count > discovered_count )); then
    echo "MAX_NODES=$MAX_NODES exceeds discovered node count $discovered_count" >&2
    exit 2
  fi
else
  use_count="$discovered_count"
fi

while (( use_count > 0 )); do
  world_size=$((use_count * GPUS_PER_NODE))
  if (( world_size % MODEL_PARALLEL_SIZE == 0 && world_size % EXPERT_MODEL_PARALLEL_SIZE == 0 )); then
    break
  fi

  if [[ "$STRICT_ALL_NODES" == "1" || -n "$MAX_NODES" ]]; then
    cat >&2 <<EOF
Invalid distributed shape:
  nodes=$use_count gpus_per_node=$GPUS_PER_NODE world_size=$world_size
  TP=$TP PP=$PP CP=$CP EP=$EP ETP=$ETP
  required: world_size divisible by $MODEL_PARALLEL_SIZE and $EXPERT_MODEL_PARALLEL_SIZE
EOF
    exit 2
  fi

  use_count=$((use_count - 1))
done

if (( use_count == 0 )); then
  echo "Could not select a valid node count for the requested shape" >&2
  exit 2
fi

world_size=$((use_count * GPUS_PER_NODE))
dp=$((world_size / MODEL_PARALLEL_SIZE))
expert_dp=$((world_size / EXPERT_MODEL_PARALLEL_SIZE))

host_short="${HOSTNAME_SHORT:-$(hostname -s)}"
node_rank="${NODE_RANK:-}"
if [[ -z "$node_rank" ]]; then
  for idx in $(seq 0 $((use_count - 1))); do
    if [[ "${names[$idx]}" == "$host_short" ]]; then
      node_rank="$idx"
      break
    fi
  done
fi

if [[ -z "$node_rank" ]]; then
  cat >&2 <<EOF
This host ($host_short) is not in the selected node set.
Selected nodes:
$(for idx in $(seq 0 $((use_count - 1))); do printf "  %s %s %s\n" "$idx" "${names[$idx]}" "${ips[$idx]}"; done)
EOF
  exit 2
fi

MICRO_BATCH_SIZE="${MICRO_BATCH_SIZE:-1}"
# MBS=1 was the first stable 32k no-PP shape. Keep grad accumulation modest by
# default; larger values are mainly an optimizer/checkpoint amortization knob,
# not a memory fix.
GRAD_ACCUM_STEPS="${GRAD_ACCUM_STEPS:-4}"
GLOBAL_BATCH_SIZE="${GLOBAL_BATCH_SIZE:-$((MICRO_BATCH_SIZE * dp * GRAD_ACCUM_STEPS))}"
if (( GLOBAL_BATCH_SIZE % (MICRO_BATCH_SIZE * dp) != 0 )); then
  echo "GLOBAL_BATCH_SIZE=$GLOBAL_BATCH_SIZE must be divisible by MICRO_BATCH_SIZE*DP=$((MICRO_BATCH_SIZE * dp))" >&2
  exit 2
fi
NUM_MICROBATCHES=$((GLOBAL_BATCH_SIZE / (MICRO_BATCH_SIZE * dp)))

if (( discovered_count != use_count )); then
  echo "Discovered $discovered_count nodes; selected $use_count for this shape." >&2
  echo "Skipped nodes:" >&2
  for idx in $(seq "$use_count" $((discovered_count - 1))); do
    printf "  %s %s\n" "${names[$idx]}" "${ips[$idx]}" >&2
  done
fi

export NNODES="$use_count"
export GPUS_PER_NODE
export WORLD_SIZE="$world_size"
export NODE_RANK="$node_rank"
export MASTER_ADDR="${MASTER_ADDR:-${ips[0]}}"
export MASTER_PORT="${MASTER_PORT:-29673}"
export TP PP CP EP ETP
export ENABLE_VPP="${ENABLE_VPP:-0}"
export VPP_SIZE="${VPP_SIZE:-2}"
export USE_TP_PP_DP_MAPPING="${USE_TP_PP_DP_MAPPING:-1}"
if [[ "$ENABLE_VPP" == "1" && "${ALLOW_VPP_OOM_EXPERIMENT:-0}" != "1" ]]; then
  cat >&2 <<EOF
VPP is disabled for the current 32k DSA/HISA fleet profile.
The PP15/VPP2 and PP5/VPP experiments OOMed from pipeline warmup activation
residency before useful 1F1B steady state. Use plain PP unless intentionally
running a short OOM experiment with ALLOW_VPP_OOM_EXPERIMENT=1.
EOF
  exit 2
fi
if [[ "$ENABLE_VPP" == "1" && "$NUM_MICROBATCHES" -lt "$PP" ]]; then
  cat >&2 <<EOF
Invalid VPP batch shape:
  PP=$PP VPP_SIZE=$VPP_SIZE microbatches=$NUM_MICROBATCHES
  VPP interleaving requires microbatches >= PP.
  At MBS=$MICRO_BATCH_SIZE and DP=$dp, GLOBAL_BATCH_SIZE must be at least $((MICRO_BATCH_SIZE * dp * PP)).
EOF
  exit 2
fi
if [[ -z "${OVERLAP_P2P_COMM_WARMUP_FLUSH:-}" ]]; then
  if [[ "$ENABLE_VPP" == "1" ]]; then
    OVERLAP_P2P_COMM_WARMUP_FLUSH=1
  else
    OVERLAP_P2P_COMM_WARMUP_FLUSH=0
  fi
fi
export OVERLAP_P2P_COMM_WARMUP_FLUSH
if [[ -z "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" ]]; then
  if [[ "$PP" -eq 15 && "$ENABLE_VPP" == "1" && "$VPP_SIZE" == "2" ]]; then
    # PP15/VPP2/DP1: one TP4 x CP2 pipeline rank per A4 node. Each physical
    # PP rank owns four decoder layers except the middle rank, which owns five.
    PIPELINE_MODEL_PARALLEL_LAYOUT="Et*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*2|t*3|t*2|t*2|t*2|t*2|t*2|t*2|t*2L"
  elif [[ "$PP" -eq 15 && "$ENABLE_VPP" == "1" ]]; then
    echo "Unsupported VPP_SIZE=$VPP_SIZE for PP=$PP; expected 2" >&2
    exit 2
  elif [[ "$PP" -eq 15 ]]; then
    PIPELINE_MODEL_PARALLEL_LAYOUT="Et*4|t*4|t*4|t*4|t*4|t*4|t*4|t*5|t*4|t*4|t*4|t*4|t*4|t*4|t*4L"
  elif [[ "$PP" -eq 5 && "$ENABLE_VPP" == "1" && "$VPP_SIZE" == "4" ]]; then
    # PP5/VPP4 maximizes bubble reduction but keeps many 32k MoE activations
    # resident during warmup; leave it opt-in until the smaller layout is stable.
    PIPELINE_MODEL_PARALLEL_LAYOUT="Et*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*3|t*4|t*3|t*3|t*3|t*3L"
  elif [[ "$PP" -eq 5 && "$ENABLE_VPP" == "1" && "$VPP_SIZE" == "2" ]]; then
    # PP5/VPP2 with a memory-skewed 11/12/12/13/13 physical layer balance.
    # The uniform-ish 13/12/12/12/12 layout OOMed on PP0 during the full VPP
    # forward queue; later PP stages had substantially more memory headroom.
    PIPELINE_MODEL_PARALLEL_LAYOUT="Et*6|t*6|t*6|t*6|t*7|t*5|t*6|t*6|t*7|t*6L"
  elif [[ "$PP" -eq 5 && "$ENABLE_VPP" == "1" ]]; then
    echo "Unsupported VPP_SIZE=$VPP_SIZE for PP=$PP; expected 2 or 4" >&2
    exit 2
  elif [[ "$PP" -eq 5 ]]; then
    PIPELINE_MODEL_PARALLEL_LAYOUT="Et*13|t*12|t*12|t*12|t*12L"
  elif [[ "$PP" -eq 4 ]]; then
    # Plain PP4 trial for the FSDP/EP shape. Keep stage 0 and the loss stage
    # slightly lighter while PP absorbs layer residency and lets us reduce TP.
    PIPELINE_MODEL_PARALLEL_LAYOUT="Et*14|t*16|t*16|t*15L"
  fi
fi
export PIPELINE_MODEL_PARALLEL_LAYOUT="${PIPELINE_MODEL_PARALLEL_LAYOUT:-}"
INFERRED_VPP_SIZE="none"
if [[ -n "${PIPELINE_MODEL_PARALLEL_LAYOUT:-}" ]]; then
  layout_without_pipes="${PIPELINE_MODEL_PARALLEL_LAYOUT//|/}"
  layout_stage_count=$(( ${#PIPELINE_MODEL_PARALLEL_LAYOUT} - ${#layout_without_pipes} + 1 ))
  if (( PP > 0 && layout_stage_count % PP == 0 )); then
    INFERRED_VPP_SIZE=$(( layout_stage_count / PP ))
  else
    INFERRED_VPP_SIZE="invalid:${layout_stage_count}/PP${PP}"
  fi
fi
export MICRO_BATCH_SIZE GLOBAL_BATCH_SIZE
export SEQ_LENGTH="${SEQ_LENGTH:-32768}"
export DSA_INDEXER_TOPK="${DSA_INDEXER_TOPK:-1024}"
export DSA_INDEXER_LOSS_COEFF="${DSA_INDEXER_LOSS_COEFF:-0.1}"
export MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE="${MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE:-token_mean}"
export TRAIN_TOKEN_TARGET="${TRAIN_TOKEN_TARGET:-24691703808}"
export LR="${LR:-5.0e-6}"
export MIN_LR="${MIN_LR:-$LR}"
export LR_WARMUP_SAMPLES="${LR_WARMUP_SAMPLES:-0}"
export NUM_WORKERS="${NUM_WORKERS:-16}"
export EMPTY_UNUSED_MEMORY_LEVEL="${EMPTY_UNUSED_MEMORY_LEVEL:-0}"
export MEGATRON_DISABLE_JIT_FUSER="${MEGATRON_DISABLE_JIT_FUSER:-0}"
export MEGATRON_RUN_STATS_LOG="${MEGATRON_RUN_STATS_LOG:-1}"
export GRAD_REDUCE_IN_BF16="${GRAD_REDUCE_IN_BF16:-1}"
export MEGATRON_SKIP_NONFINITE_GRAD_NORM="${MEGATRON_SKIP_NONFINITE_GRAD_NORM:-1}"
export MEGATRON_NONFINITE_GRAD_OWNERSHIP="${MEGATRON_NONFINITE_GRAD_OWNERSHIP:-1}"
export MEGATRON_GRAD_OWNERSHIP_NONFINITE_PARAMS="${MEGATRON_GRAD_OWNERSHIP_NONFINITE_PARAMS:-16}"
export CALCULATE_PER_TOKEN_LOSS="${CALCULATE_PER_TOKEN_LOSS:-1}"
export SFT_FINETUNE="${SFT_FINETUNE:-1}"
export OVERLAP_PARAM_GATHER="${OVERLAP_PARAM_GATHER:-1}"
export USE_MEGATRON_FSDP="${USE_MEGATRON_FSDP:-1}"
export DATA_PARALLEL_SHARDING_STRATEGY="${DATA_PARALLEL_SHARDING_STRATEGY:-optim_grads_params}"
export FSDP_INIT_MODEL_WITH_META_DEVICE="${FSDP_INIT_MODEL_WITH_META_DEVICE:-1}"
export FSDP_USE_NCCL_UB="${FSDP_USE_NCCL_UB:-0}"
export FSDP_DOUBLE_BUFFER="${FSDP_DOUBLE_BUFFER:-0}"
export FSDP_CREATE_ALL_GATHER_GROUP="${FSDP_CREATE_ALL_GATHER_GROUP:-0}"
export FSDP_MANUAL_REGISTRATION="${FSDP_MANUAL_REGISTRATION:-0}"
export FSDP_DISABLE_SYMMETRIC_REGISTRATION="${FSDP_DISABLE_SYMMETRIC_REGISTRATION:-0}"
export MEGATRON_FSDP_FLUSH_READY_BUCKETS_ON_RESET="${MEGATRON_FSDP_FLUSH_READY_BUCKETS_ON_RESET:-1}"
export MEGATRON_FSDP_LOG_READY_BUCKET_FLUSH="${MEGATRON_FSDP_LOG_READY_BUCKET_FLUSH:-0}"
export OVERLAP_MOE_EXPERT_PARALLEL_COMM="${OVERLAP_MOE_EXPERT_PARALLEL_COMM:-0}"
if [[ "$USE_MEGATRON_FSDP" == "1" ]]; then
  export CUDA_DEVICE_MAX_CONNECTIONS="${CUDA_DEVICE_MAX_CONNECTIONS:-8}"
elif [[ "$OVERLAP_MOE_EXPERT_PARALLEL_COMM" == "1" ]]; then
  export CUDA_DEVICE_MAX_CONNECTIONS="${CUDA_DEVICE_MAX_CONNECTIONS:-32}"
else
  export CUDA_DEVICE_MAX_CONNECTIONS="${CUDA_DEVICE_MAX_CONNECTIONS:-1}"
fi
if [[ "$USE_MEGATRON_FSDP" == "1" && "$CUDA_DEVICE_MAX_CONNECTIONS" == "1" ]]; then
  echo "USE_MEGATRON_FSDP=1 requires CUDA_DEVICE_MAX_CONNECTIONS to be unset or greater than 1" >&2
  exit 1
fi
export HIGH_PRIORITY_A2A_COMM_STREAM="${HIGH_PRIORITY_A2A_COMM_STREAM:-0}"
export EP_OVERLAP_EARLY_ATTN_MEMORY_RELEASE="${EP_OVERLAP_EARLY_ATTN_MEMORY_RELEASE:-0}"
export DELAY_WGRAD_COMPUTE="${DELAY_WGRAD_COMPUTE:-0}"
export OVERLAP_DISPATCH_BACKWARD_WITH_EXPERTS_WGRAD="${OVERLAP_DISPATCH_BACKWARD_WITH_EXPERTS_WGRAD:-0}"
export MOE_HYBRIDEP_NUM_SMS_PREPROCESSING="${MOE_HYBRIDEP_NUM_SMS_PREPROCESSING:-}"
export LOAD_CKPT="${LOAD_CKPT:-$HOME/checkpoints/deepseek_v32_reap_spinquant_actkv_nvfp4_megatron_tp8_pp1_ep8}"
export SAVE_CKPT="${SAVE_CKPT:-$HOME/checkpoints/sft_deepseek_v32_reap_spinquant_actkv_nvfp4_tp${TP}_pp${PP}_cp${CP}_ep${EP}}"
export DATA_PATH="${DATA_PATH:-$HOME/data/sft/blaise-sft-training-mix/blaise-sft-training-mix-full.jsonl}"
export DATALOADER_TYPE="${DATALOADER_TYPE:-cyclic}"
export MEGATRON_SFT_SHUFFLE_ROWS="${MEGATRON_SFT_SHUFFLE_ROWS:-1}"
export MEGATRON_SFT_SHUFFLE_SEED="${MEGATRON_SFT_SHUFFLE_SEED:-1234}"
export MEGATRON_SFT_SHUFFLE_BUILD_IF_MISSING="${MEGATRON_SFT_SHUFFLE_BUILD_IF_MISSING:-1}"
export MODEL_ID="${MODEL_ID:-BlaiseAI/DeepSeek-V3.2-REAP-345B-SpinQuant-ActKV-NVFP4}"
export TOKENIZER_MODEL="${TOKENIZER_MODEL:-$MODEL_ID}"
export MEGATRON_SFT_MASK_SYNTHETIC_TOOL_CALLS="${MEGATRON_SFT_MASK_SYNTHETIC_TOOL_CALLS:-1}"
export SAVE_INTERVAL="${SAVE_INTERVAL:-5}"
# Megatron deletes the previous checkpoint only when that previous iteration is
# not itself a retain interval. Use a large multiple of SAVE_INTERVAL so the
# production run keeps only the most recent ordinary checkpoint on local disk.
export SAVE_RETAIN_INTERVAL="${SAVE_RETAIN_INTERVAL:-1000000}"
export CKPT_FULLY_PARALLEL_LOAD="${CKPT_FULLY_PARALLEL_LOAD:-1}"
export CKPT_FULLY_PARALLEL_LOAD_PROCESS_GROUP="${CKPT_FULLY_PARALLEL_LOAD_PROCESS_GROUP:-dp}"
export CKPT_FULLY_PARALLEL_LOAD_EXCHANGE_ALGO="${CKPT_FULLY_PARALLEL_LOAD_EXCHANGE_ALGO:-broadcast}"
export WANDB_ENTITY="${WANDB_ENTITY:-blaise-ai}"
export WANDB_PROJECT="${WANDB_PROJECT:-corsaire-1}"
export WANDB_EXP_NAME="${WANDB_EXP_NAME:-corsaire-1-research-preview}"
export WANDB_SAVE_DIR="${WANDB_SAVE_DIR:-$SAVE_CKPT/wandb}"
# Offline is the default for every training run. To intentionally publish live,
# set both WANDB_FORCE_OFFLINE=0 and WANDB_MODE=online at launch.
export WANDB_FORCE_OFFLINE="${WANDB_FORCE_OFFLINE:-1}"
if [[ "$WANDB_FORCE_OFFLINE" == "1" ]]; then
  export WANDB_MODE=offline
else
  export WANDB_MODE="${WANDB_MODE:-offline}"
fi
export ENABLE_ONE_LOGGER="${ENABLE_ONE_LOGGER:-1}"
export ONE_LOGGER_PROJECT="${ONE_LOGGER_PROJECT:-${WANDB_PROJECT:-megatron-lm}}"
export ONE_LOGGER_RUN_NAME="${ONE_LOGGER_RUN_NAME:-${WANDB_EXP_NAME:-gcp-a4-deepseek-sft}-${SLURM_JOB_ID:-manual}}"
export ONE_LOGGER_DIR="${ONE_LOGGER_DIR:-$HOME/logs/one_logger}"
export ZCC_RUN_NAME="${ZCC_RUN_NAME:-$WANDB_EXP_NAME}"
export ENABLE_ZCC="${ENABLE_ZCC:-1}"
export ZCC_WORKERS_NUM="${ZCC_WORKERS_NUM:-8}"
export ZCC_FLASH_DEVICE="${ZCC_FLASH_DEVICE:-/dev/shm/megatron_zcc/$ZCC_RUN_NAME}"
export ZCC_DURABLE_DIR="${ZCC_DURABLE_DIR:-$SAVE_CKPT/zcc/$ZCC_RUN_NAME}"
export ZCC_DURABLE_INTERVAL="${ZCC_DURABLE_INTERVAL:-1}"
export ZCC_COMPRESS="${ZCC_COMPRESS:-zstd:1}"
export ZCC_RETAIN_LATEST="${ZCC_RETAIN_LATEST:-2}"
export HF_UPLOAD_CHECKPOINTS="${HF_UPLOAD_CHECKPOINTS:-0}"
export HF_REPO_ID="${HF_REPO_ID:-BlaiseAI/corsaire-1-research-preview}"
export HF_UPLOAD_FOLDER_PREFIX="${HF_UPLOAD_FOLDER_PREFIX:-corsaire-1-research-preview}"
export HF_UPLOAD_INTERVAL="${HF_UPLOAD_INTERVAL:-500}"
export HF_UPLOAD_RETAIN="${HF_UPLOAD_RETAIN:-1}"
export HF_UPLOAD_STABLE_SECONDS="${HF_UPLOAD_STABLE_SECONDS:-180}"
export HF_UPLOAD_POLL_SECONDS="${HF_UPLOAD_POLL_SECONDS:-60}"
export HF_UPLOAD_FINALIZE_TIMEOUT_SECONDS="${HF_UPLOAD_FINALIZE_TIMEOUT_SECONDS:-7200}"
export HF_UPLOAD_PRIVATE="${HF_UPLOAD_PRIVATE:-1}"
export HF_UPLOAD_RETENTION_NODE_RANK="${HF_UPLOAD_RETENTION_NODE_RANK:-0}"
export HF_UPLOAD_EXPECTED_NODES="${HF_UPLOAD_EXPECTED_NODES:-$NNODES}"
export TORCH_EXTENSIONS_DIR="${TORCH_EXTENSIONS_DIR:-/tmp/torch_extensions_${USER:-sjpat}_${SLURM_JOB_ID:-manual}}"
mkdir -p "$TORCH_EXTENSIONS_DIR"

if [[ "${PROFILE_RUN:-0}" == "1" ]]; then
  export PROFILE_HEAVY="${PROFILE_HEAVY:-1}"
  export ENABLE_PROFILING="${ENABLE_PROFILING:-1}"
  export USE_PYTORCH_PROFILER="${USE_PYTORCH_PROFILER:-1}"
  if [[ "$PROFILE_HEAVY" == "1" ]]; then
    export PYTORCH_PROFILER_COLLECT_SHAPES="${PYTORCH_PROFILER_COLLECT_SHAPES:-1}"
    export PYTORCH_PROFILER_COLLECT_CALLSTACK="${PYTORCH_PROFILER_COLLECT_CALLSTACK:-1}"
    export PYTORCH_PROFILER_PROFILE_MEMORY="${PYTORCH_PROFILER_PROFILE_MEMORY:-1}"
    export PYTORCH_PROFILER_WITH_FLOPS="${PYTORCH_PROFILER_WITH_FLOPS:-1}"
    export PYTORCH_PROFILER_WITH_MODULES="${PYTORCH_PROFILER_WITH_MODULES:-1}"
  else
    export PYTORCH_PROFILER_COLLECT_SHAPES="${PYTORCH_PROFILER_COLLECT_SHAPES:-0}"
    export PYTORCH_PROFILER_COLLECT_CALLSTACK="${PYTORCH_PROFILER_COLLECT_CALLSTACK:-0}"
    export PYTORCH_PROFILER_PROFILE_MEMORY="${PYTORCH_PROFILER_PROFILE_MEMORY:-0}"
    export PYTORCH_PROFILER_WITH_FLOPS="${PYTORCH_PROFILER_WITH_FLOPS:-0}"
    export PYTORCH_PROFILER_WITH_MODULES="${PYTORCH_PROFILER_WITH_MODULES:-0}"
  fi
  export PROFILE_STEP_START="${PROFILE_STEP_START:-1}"
  export PROFILE_STEP_END="${PROFILE_STEP_END:-3}"
  export MEGATRON_FINE_PROFILE="${MEGATRON_FINE_PROFILE:-1}"
  export MEGATRON_FINE_PROFILE_TIMERS="${MEGATRON_FINE_PROFILE_TIMERS:-1}"
  export MEGATRON_FINE_PROFILE_TIMER_TOP_N="${MEGATRON_FINE_PROFILE_TIMER_TOP_N:-160}"
  export MEGATRON_FINE_PROFILE_TIMER_FILTER="${MEGATRON_FINE_PROFILE_TIMER_FILTER:-*}"
  export MEGATRON_FINE_PROFILE_RANKS="${MEGATRON_FINE_PROFILE_RANKS:-${PROFILE_RANKS:-0,7,88,95}}"
  export PROFILE_RANKS="${PROFILE_RANKS:-$MEGATRON_FINE_PROFILE_RANKS}"
  export TENSORBOARD_LOGS_PATH="${TENSORBOARD_LOGS_PATH:-$HOME/tensorboard_logs/sft_deepseek_v32_reap_nvfp4/profiles/${SLURM_JOB_ID:-manual}/tb}"
  export MEGATRON_MOE_STAGE_PROGRESS_LOG="${MEGATRON_MOE_STAGE_PROGRESS_LOG:-0}"
  export MEGATRON_MOE_STAGE_PROGRESS_RANKS="${MEGATRON_MOE_STAGE_PROGRESS_RANKS:-$PROFILE_RANKS}"
  export MEGATRON_MOE_STAGE_PROGRESS_SYNC="${MEGATRON_MOE_STAGE_PROGRESS_SYNC:-0}"
  export MEGATRON_LOSS_DIAGNOSTICS="${MEGATRON_LOSS_DIAGNOSTICS:-1}"
  export MEGATRON_LOSS_DIAGNOSTIC_RANKS="${MEGATRON_LOSS_DIAGNOSTIC_RANKS:-all}"
  export MEGATRON_LOSS_DIAGNOSTIC_EVERY="${MEGATRON_LOSS_DIAGNOSTIC_EVERY:-1}"
  export MEGATRON_BATCH_DIAGNOSTICS="${MEGATRON_BATCH_DIAGNOSTICS:-1}"
  export MEGATRON_BATCH_DIAGNOSTIC_RANKS="${MEGATRON_BATCH_DIAGNOSTIC_RANKS:-all}"
  export MEGATRON_BATCH_DIAGNOSTIC_EVERY="${MEGATRON_BATCH_DIAGNOSTIC_EVERY:-1}"
  export LOG_INTERVAL="${LOG_INTERVAL:-1}"
  export TENSORBOARD_LOG_INTERVAL="${TENSORBOARD_LOG_INTERVAL:-1}"
  export LOG_MEMORY_INTERVAL="${LOG_MEMORY_INTERVAL:-1}"
  export LOG_PARAMS_NORM="${LOG_PARAMS_NORM:-1}"
  export LOG_NUM_ZEROS_IN_GRAD="${LOG_NUM_ZEROS_IN_GRAD:-1}"
  export LOG_MAX_ATTENTION_LOGIT="${LOG_MAX_ATTENTION_LOGIT:-1}"
  export LOG_ENERGY="${LOG_ENERGY:-1}"
  export TRAIN_SAMPLES="${TRAIN_SAMPLES:-$((GLOBAL_BATCH_SIZE * 5))}"
  export LR_DECAY_SAMPLES="${LR_DECAY_SAMPLES:-$TRAIN_SAMPLES}"
  export LR_WARMUP_SAMPLES="${LR_WARMUP_SAMPLES:-$GLOBAL_BATCH_SIZE}"
  export DISABLE_SAVE="${DISABLE_SAVE:-1}"
  export ENABLE_ZCC="${PROFILE_ENABLE_ZCC:-0}"
  export HF_UPLOAD_CHECKPOINTS="${PROFILE_HF_UPLOAD_CHECKPOINTS:-0}"
  export PROFILE_ENABLE_WANDB="${PROFILE_ENABLE_WANDB:-1}"
  if [[ "${PROFILE_ENABLE_WANDB:-1}" != "1" ]]; then
    export WANDB_PROJECT=""
  fi
fi

if [[ "${LOSS_AUTOPSY:-0}" == "1" ]]; then
  # This mode is intentionally intrusive and should only be used for short
  # semantic/loss probes. It trades throughput and log volume for attribution:
  # token supervision, per-token loss tails, router/DSA state, every grad
  # accumulation stage we have hooks for, and optimizer/flashopt numeric probes.
  export ENABLE_TRAINING_DEBUG=1
  export LOG_INTERVAL="${LOG_INTERVAL:-1}"
  export TENSORBOARD_LOG_INTERVAL="${TENSORBOARD_LOG_INTERVAL:-1}"
  export LOG_MEMORY_INTERVAL="${LOG_MEMORY_INTERVAL:-1}"
  export LOG_PARAMS_NORM="${LOG_PARAMS_NORM:-1}"
  export LOG_NUM_ZEROS_IN_GRAD="${LOG_NUM_ZEROS_IN_GRAD:-1}"
  export LOG_MAX_ATTENTION_LOGIT="${LOG_MAX_ATTENTION_LOGIT:-1}"
  export LOG_ENERGY="${LOG_ENERGY:-1}"
  export TRAIN_SAMPLES="${TRAIN_SAMPLES:-$((GLOBAL_BATCH_SIZE * 5))}"
  export LR_DECAY_SAMPLES="${LR_DECAY_SAMPLES:-$TRAIN_SAMPLES}"
  export LR_WARMUP_SAMPLES="${LR_WARMUP_SAMPLES:-$GLOBAL_BATCH_SIZE}"
  export DISABLE_SAVE="${DISABLE_SAVE:-1}"
  export ENABLE_ZCC="${LOSS_AUTOPSY_ENABLE_ZCC:-0}"
  export HF_UPLOAD_CHECKPOINTS="${LOSS_AUTOPSY_HF_UPLOAD_CHECKPOINTS:-0}"
  export WANDB_MODE=offline

  export MEGATRON_RUN_STATS_LOG="${MEGATRON_RUN_STATS_LOG:-1}"
  export MEGATRON_LOSS_DIAGNOSTICS="${MEGATRON_LOSS_DIAGNOSTICS:-1}"
  export MEGATRON_LOSS_DIAGNOSTIC_RANKS="${MEGATRON_LOSS_DIAGNOSTIC_RANKS:-all}"
  export MEGATRON_LOSS_DIAGNOSTIC_EVERY="${MEGATRON_LOSS_DIAGNOSTIC_EVERY:-1}"
  export MEGATRON_LOSS_DIAGNOSTIC_TOPK="${MEGATRON_LOSS_DIAGNOSTIC_TOPK:-64}"
  export MEGATRON_LOSS_DIAGNOSTIC_NONFINITE_TOPK="${MEGATRON_LOSS_DIAGNOSTIC_NONFINITE_TOPK:-64}"
  export MEGATRON_LOSS_DIAGNOSTIC_CONTEXT="${MEGATRON_LOSS_DIAGNOSTIC_CONTEXT:-16}"
  export MEGATRON_LOSS_DIAGNOSTIC_THRESHOLDS="${MEGATRON_LOSS_DIAGNOSTIC_THRESHOLDS:-1,2,5,10,15,20,30,50,100}"
  export MEGATRON_LOSS_DIAGNOSTIC_QUANTILES="${MEGATRON_LOSS_DIAGNOSTIC_QUANTILES:-0.5,0.75,0.9,0.95,0.99,0.999,0.9999}"
  export MEGATRON_BATCH_DIAGNOSTICS="${MEGATRON_BATCH_DIAGNOSTICS:-1}"
  export MEGATRON_BATCH_DIAGNOSTIC_RANKS="${MEGATRON_BATCH_DIAGNOSTIC_RANKS:-all}"
  export MEGATRON_BATCH_DIAGNOSTIC_EVERY="${MEGATRON_BATCH_DIAGNOSTIC_EVERY:-1}"
  export MEGATRON_BATCH_DIAGNOSTIC_CONTEXT="${MEGATRON_BATCH_DIAGNOSTIC_CONTEXT:-16}"

  export MEGATRON_FINE_PROFILE="${MEGATRON_FINE_PROFILE:-1}"
  export MEGATRON_FINE_PROFILE_TIMERS="${MEGATRON_FINE_PROFILE_TIMERS:-1}"
  export MEGATRON_FINE_PROFILE_TIMER_TOP_N="${MEGATRON_FINE_PROFILE_TIMER_TOP_N:-240}"
  export MEGATRON_FINE_PROFILE_TIMER_FILTER="${MEGATRON_FINE_PROFILE_TIMER_FILTER:-*}"
  export MEGATRON_FINE_PROFILE_RANKS="${MEGATRON_FINE_PROFILE_RANKS:-all}"
  export PROFILE_RANKS="${PROFILE_RANKS:-$MEGATRON_FINE_PROFILE_RANKS}"
  export MEGATRON_MOE_STAGE_PROGRESS_LOG="${MEGATRON_MOE_STAGE_PROGRESS_LOG:-1}"
  export MEGATRON_MOE_STAGE_PROGRESS_RANKS="${MEGATRON_MOE_STAGE_PROGRESS_RANKS:-all}"
  export MEGATRON_MOE_STAGE_PROGRESS_SYNC="${MEGATRON_MOE_STAGE_PROGRESS_SYNC:-0}"
  export MEGATRON_MOE_DISPATCH_STATS_LOG="${MEGATRON_MOE_DISPATCH_STATS_LOG:-1}"
  export MEGATRON_MOE_DISPATCH_STATS_RANK_STRIDE="${MEGATRON_MOE_DISPATCH_STATS_RANK_STRIDE:-1}"
  export MEGATRON_MOE_DISPATCH_STATS_TOPK_EXPERTS="${MEGATRON_MOE_DISPATCH_STATS_TOPK_EXPERTS:-32}"

  export MEGATRON_NUMERIC_DEBUG="${MEGATRON_NUMERIC_DEBUG:-1}"
  export MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE="${MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE:-0}"
  export MEGATRON_NUMERIC_DEBUG_RANKS="${MEGATRON_NUMERIC_DEBUG_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_START_ITER="${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}"
  export MEGATRON_NUMERIC_DEBUG_FIRST_N="${MEGATRON_NUMERIC_DEBUG_FIRST_N:-16}"
  export MEGATRON_NUMERIC_DEBUG_INTERVAL="${MEGATRON_NUMERIC_DEBUG_INTERVAL:-1}"
  export MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT="${MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT:-8192}"
  export MEGATRON_NUMERIC_DEBUG_MAX_ELEMS="${MEGATRON_NUMERIC_DEBUG_MAX_ELEMS:-1048576}"
  export MEGATRON_NUMERIC_DEBUG_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_FULL_FINITE:-0}"
  export MEGATRON_NUMERIC_DEBUG_BATCH="${MEGATRON_NUMERIC_DEBUG_BATCH:-1}"
  export MEGATRON_NUMERIC_DEBUG_LOSS="${MEGATRON_NUMERIC_DEBUG_LOSS:-1}"
  export MEGATRON_NUMERIC_DEBUG_PARAM_STATS="${MEGATRON_NUMERIC_DEBUG_PARAM_STATS:-1}"
  export MEGATRON_NUMERIC_DEBUG_PARAM_RANKS="${MEGATRON_NUMERIC_DEBUG_PARAM_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_TOPK="${MEGATRON_NUMERIC_DEBUG_TOPK:-192}"

  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_RANKS="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_TOPK="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_TOPK:-192}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_KINDS="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_KINDS:-main_grad,grad}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_FULL_FINITE:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_LOCAL="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_LOCAL:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_GLOBAL="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_GLOBAL:-1}"

  export MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS="${MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_LOG_ALL="${MEGATRON_NUMERIC_DEBUG_GRAD_LOG_ALL:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_GRAD_ABORT:-0}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_GRAD_REGEX:-dsa|hisa|indexer|indexcache|router|gate|shared_expert|experts|attention|mla|output_layer|word_embeddings|gated_norm|norm|linear_fc1|linear_fc2|linear_q|linear_kv|linear_proj}"

  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"
  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_STAGE_LIMIT="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_STAGE_LIMIT:-8192}"
  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_FULL_FINITE:-1}"
  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_ABORT:-0}"

  export MEGATRON_NUMERIC_DEBUG_DDP_GRAD="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"
  export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_ABORT:-0}"
  export MEGATRON_NUMERIC_DEBUG_FSDP_GRAD="${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"
  export MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_ABORT:-0}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_STAGE_LIMIT="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_STAGE_LIMIT:-8192}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_COPY_LIMIT="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_COPY_LIMIT:-8192}"

  export MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS="${MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS:-1}"
  export MEGATRON_NUMERIC_DEBUG_HOOK_RANKS="${MEGATRON_NUMERIC_DEBUG_HOOK_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_VERBOSE_HOOKS="${MEGATRON_NUMERIC_DEBUG_VERBOSE_HOOKS:-1}"
  export MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS="${MEGATRON_NUMERIC_DEBUG_HOOK_INPUTS:-1}"
  export MEGATRON_NUMERIC_DEBUG_HOOK_CLASSES="${MEGATRON_NUMERIC_DEBUG_HOOK_CLASSES:-GPTModel,TransformerLayer,MoELayer,TopKRouter,DSAttention,DSAIndexer,SelfAttention,MLP,GroupedMLP,ColumnParallelLinear,RowParallelLinear}"

  export MEGATRON_NUMERIC_DEBUG_ROUTER="${MEGATRON_NUMERIC_DEBUG_ROUTER:-1}"
  export MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS="${MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE="${MEGATRON_NUMERIC_DEBUG_ROUTER_FORCE:-1}"
  export MEGATRON_NUMERIC_DEBUG_ROUTER_LIMIT="${MEGATRON_NUMERIC_DEBUG_ROUTER_LIMIT:-8192}"
  export MEGATRON_NUMERIC_DEBUG_DSA="${MEGATRON_NUMERIC_DEBUG_DSA:-1}"
  export MEGATRON_NUMERIC_DEBUG_DSA_RANKS="${MEGATRON_NUMERIC_DEBUG_DSA_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_DSA_FORCE="${MEGATRON_NUMERIC_DEBUG_DSA_FORCE:-1}"
  export MEGATRON_NUMERIC_DEBUG_DSA_LIMIT="${MEGATRON_NUMERIC_DEBUG_DSA_LIMIT:-8192}"

  export MEGATRON_NUMERIC_DEBUG_FLASHOPT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT:-1}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_RANKS="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_FORCE:-1}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_ALL:-1}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_CHECK_PRECAST:-1}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_DELTA="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_DELTA:-1}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_ABORT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_ABORT:-0}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_ADAM_LIMIT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_ADAM_LIMIT:-8192}"
  export MEGATRON_NUMERIC_DEBUG_FLASHOPT_LIMIT="${MEGATRON_NUMERIC_DEBUG_FLASHOPT_LIMIT:-8192}"
  export MEGATRON_UPDATE_DELTA_DEBUG="${MEGATRON_UPDATE_DELTA_DEBUG:-1}"
  export MEGATRON_UPDATE_DELTA_RANKS="${MEGATRON_UPDATE_DELTA_RANKS:-all}"
  export MEGATRON_UPDATE_DELTA_START_ITER="${MEGATRON_UPDATE_DELTA_START_ITER:-1}"
  export MEGATRON_UPDATE_DELTA_FIRST_N="${MEGATRON_UPDATE_DELTA_FIRST_N:-8}"
  export MEGATRON_UPDATE_DELTA_INTERVAL="${MEGATRON_UPDATE_DELTA_INTERVAL:-1}"
  export MEGATRON_UPDATE_DELTA_PARAM_LIMIT="${MEGATRON_UPDATE_DELTA_PARAM_LIMIT:-96}"
  export MEGATRON_UPDATE_DELTA_FORCE_PARAM_LIMIT="${MEGATRON_UPDATE_DELTA_FORCE_PARAM_LIMIT:-256}"
  export MEGATRON_UPDATE_DELTA_SAMPLE_ELEMS="${MEGATRON_UPDATE_DELTA_SAMPLE_ELEMS:-4096}"
  export MEGATRON_UPDATE_DELTA_REGEX="${MEGATRON_UPDATE_DELTA_REGEX:-dense_mlp|mlp|self_attention|linear_q|linear_kv|linear_proj|shared_experts|experts|gated_norm|norm|dsa|hisa|indexer|indexcache|output_layer|word_embeddings|router}"
  export MEGATRON_UPDATE_DELTA_FORCE_REGEX="${MEGATRON_UPDATE_DELTA_FORCE_REGEX:-decoder\\.layers\\.(0|1|2)\\.mlp\\.linear_fc[12]\\.weight|decoder\\.layers\\.(0|1|2)\\.self_attention\\.linear_(q_down_proj|q_up_proj|kv_up_proj|proj)\\.weight|decoder\\.layers\\.[0-9]+\\.mlp\\.shared_experts\\.linear_fc[12]\\.weight|core_attention\\.indexer\\.(linear_wk|linear_weights_proj|linear_wq_b|k_norm)}"

  export MEGATRON_TENSOR_AUDIT="${MEGATRON_TENSOR_AUDIT:-1}"
  export MEGATRON_TENSOR_AUDIT_RANKS="${MEGATRON_TENSOR_AUDIT_RANKS:-all}"
  export MEGATRON_TENSOR_AUDIT_LIMIT="${MEGATRON_TENSOR_AUDIT_LIMIT:-8192}"
  export MEGATRON_TENSOR_AUDIT_FILTER="${MEGATRON_TENSOR_AUDIT_FILTER:-}"
  export MEGATRON_TENSOR_AUDIT_SMALL_TENSOR_VALUES="${MEGATRON_TENSOR_AUDIT_SMALL_TENSOR_VALUES:-128}"
  export MEGATRON_TENSOR_AUDIT_SYNC="${MEGATRON_TENSOR_AUDIT_SYNC:-0}"
  export MEGATRON_OPTIMIZER_STEP_PROBE="${MEGATRON_OPTIMIZER_STEP_PROBE:-1}"
fi

if [[ "${GRAD_FORENSICS:-0}" == "1" || "${MEGATRON_GRAD_PROVENANCE:-0}" == "1" ]]; then
  # Extremely intrusive provenance mode for short diagnostics. This prints
  # exact module/function gradient boundaries, including DSA/HISA custom
  # autograd, MoE dispatch/combine, FSDP/DDP accumulation, and optimizer grad
  # movement. Keep it out of production runs.
  export ENABLE_TRAINING_DEBUG=1
  export LOG_INTERVAL="${LOG_INTERVAL:-1}"
  export TENSORBOARD_LOG_INTERVAL="${TENSORBOARD_LOG_INTERVAL:-1}"
  export LOG_MEMORY_INTERVAL="${LOG_MEMORY_INTERVAL:-1}"
  export DISABLE_SAVE="${DISABLE_SAVE:-1}"
  export ENABLE_ZCC="${GRAD_FORENSICS_ENABLE_ZCC:-0}"
  export HF_UPLOAD_CHECKPOINTS="${GRAD_FORENSICS_HF_UPLOAD_CHECKPOINTS:-0}"
  export WANDB_MODE=offline

  export MEGATRON_RUN_STATS_LOG="${MEGATRON_RUN_STATS_LOG:-1}"
  export MEGATRON_LOSS_DIAGNOSTICS="${MEGATRON_LOSS_DIAGNOSTICS:-1}"
  export MEGATRON_LOSS_DIAGNOSTIC_RANKS="${MEGATRON_LOSS_DIAGNOSTIC_RANKS:-all}"
  export MEGATRON_LOSS_DIAGNOSTIC_EVERY="${MEGATRON_LOSS_DIAGNOSTIC_EVERY:-1}"
  export MEGATRON_BATCH_DIAGNOSTICS="${MEGATRON_BATCH_DIAGNOSTICS:-1}"
  export MEGATRON_BATCH_DIAGNOSTIC_RANKS="${MEGATRON_BATCH_DIAGNOSTIC_RANKS:-all}"
  export MEGATRON_BATCH_DIAGNOSTIC_EVERY="${MEGATRON_BATCH_DIAGNOSTIC_EVERY:-1}"

  export MEGATRON_NUMERIC_DEBUG="${MEGATRON_NUMERIC_DEBUG:-1}"
  export MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE="${MEGATRON_NUMERIC_DEBUG_ABORT_ON_NONFINITE:-0}"
  export MEGATRON_NUMERIC_DEBUG_RANKS="${MEGATRON_NUMERIC_DEBUG_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_START_ITER="${MEGATRON_NUMERIC_DEBUG_START_ITER:-1}"
  export MEGATRON_NUMERIC_DEBUG_FIRST_N="${MEGATRON_NUMERIC_DEBUG_FIRST_N:-8}"
  export MEGATRON_NUMERIC_DEBUG_INTERVAL="${MEGATRON_NUMERIC_DEBUG_INTERVAL:-1}"
  export MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT="${MEGATRON_NUMERIC_DEBUG_EVENT_LIMIT:-16384}"
  export MEGATRON_NUMERIC_DEBUG_MAX_ELEMS="${MEGATRON_NUMERIC_DEBUG_MAX_ELEMS:-262144}"
  export MEGATRON_NUMERIC_DEBUG_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_FULL_FINITE:-0}"

  export MEGATRON_GRAD_PROVENANCE=1
  export MEGATRON_NUMERIC_DEBUG_GRAD_PROVENANCE=1
  export MEGATRON_GRAD_PROVENANCE_RANKS="${MEGATRON_GRAD_PROVENANCE_RANKS:-0,7,88,95}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_PROVENANCE_RANKS="${MEGATRON_NUMERIC_DEBUG_GRAD_PROVENANCE_RANKS:-$MEGATRON_GRAD_PROVENANCE_RANKS}"
  export MEGATRON_GRAD_PROVENANCE_MODULE_REGEX="${MEGATRON_GRAD_PROVENANCE_MODULE_REGEX:-dsa|hisa|index|attention|self_attention|mlp|moe|expert|router|gate|embedding|output|norm|linear|decoder|layers}"
  export MEGATRON_GRAD_PROVENANCE_CLASS_REGEX="${MEGATRON_GRAD_PROVENANCE_CLASS_REGEX:-TransformerLayer|DSAttention|DSAIndexer|SelfAttention|MoELayer|TopKRouter|GroupedMLP|MLP|Linear|ColumnParallel|RowParallel|LayerNorm|RMSNorm|Gated}"
  export MEGATRON_GRAD_PROVENANCE_MAX_MODULES="${MEGATRON_GRAD_PROVENANCE_MAX_MODULES:-768}"
  export MEGATRON_GRAD_PROVENANCE_MAX_TENSORS="${MEGATRON_GRAD_PROVENANCE_MAX_TENSORS:-16}"
  export MEGATRON_GRAD_PROVENANCE_EVENT_LIMIT="${MEGATRON_GRAD_PROVENANCE_EVENT_LIMIT:-32768}"
  export MEGATRON_GRAD_PROVENANCE_MAX_ELEMS="${MEGATRON_GRAD_PROVENANCE_MAX_ELEMS:-65536}"
  export MEGATRON_GRAD_PROVENANCE_FULL_FINITE="${MEGATRON_GRAD_PROVENANCE_FULL_FINITE:-0}"

  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_RANKS="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_TOPK="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_TOPK:-256}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_KINDS="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_KINDS:-main_grad,grad}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_FULL_FINITE="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_FULL_FINITE:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_LOCAL="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_LOCAL:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_GLOBAL="${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY_GLOBAL:-1}"

  export MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS="${MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_GRAD_RANKS:-$MEGATRON_GRAD_PROVENANCE_RANKS}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_LOG_ALL="${MEGATRON_NUMERIC_DEBUG_GRAD_LOG_ALL:-1}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_ABORT="${MEGATRON_NUMERIC_DEBUG_GRAD_ABORT:-0}"
  export MEGATRON_NUMERIC_DEBUG_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_GRAD_REGEX:-dsa|hisa|indexer|indexcache|router|gate|shared_expert|experts|attention|mla|output_layer|word_embeddings|gated_norm|norm|linear_fc1|linear_fc2|linear_q|linear_kv|linear_proj}"

  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"
  export MEGATRON_NUMERIC_DEBUG_DDP_GRAD="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_DDP_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"
  export MEGATRON_NUMERIC_DEBUG_FSDP_GRAD="${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD:-1}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX="${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD_REGEX:-$MEGATRON_NUMERIC_DEBUG_GRAD_REGEX}"

  export MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS="${MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS:-0}"
  export MEGATRON_NUMERIC_DEBUG_ROUTER="${MEGATRON_NUMERIC_DEBUG_ROUTER:-1}"
  export MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS="${MEGATRON_NUMERIC_DEBUG_ROUTER_RANKS:-all}"
  export MEGATRON_NUMERIC_DEBUG_DSA="${MEGATRON_NUMERIC_DEBUG_DSA:-1}"
  export MEGATRON_NUMERIC_DEBUG_DSA_RANKS="${MEGATRON_NUMERIC_DEBUG_DSA_RANKS:-$MEGATRON_GRAD_PROVENANCE_RANKS}"
  export MEGATRON_DSA_INDEXER_K_GRAD_DEBUG="${MEGATRON_DSA_INDEXER_K_GRAD_DEBUG:-1}"
  export MEGATRON_DSA_INDEXER_K_GRAD_DEBUG_RANKS="${MEGATRON_DSA_INDEXER_K_GRAD_DEBUG_RANKS:-$MEGATRON_GRAD_PROVENANCE_RANKS}"
  export MEGATRON_DSA_INDEXER_K_GRAD_DEBUG_LIMIT="${MEGATRON_DSA_INDEXER_K_GRAD_DEBUG_LIMIT:-4096}"
fi

export MEGATRON_LOSS_DIAGNOSTICS="${MEGATRON_LOSS_DIAGNOSTICS:-0}"
export MEGATRON_BATCH_DIAGNOSTICS="${MEGATRON_BATCH_DIAGNOSTICS:-0}"
export MEGATRON_NUMERIC_DEBUG="${MEGATRON_NUMERIC_DEBUG:-0}"
export MEGATRON_NUMERIC_DEBUG_RANKS="${MEGATRON_NUMERIC_DEBUG_RANKS:-}"
export MEGATRON_GRAD_PROVENANCE="${MEGATRON_GRAD_PROVENANCE:-0}"
export MEGATRON_NUMERIC_DEBUG_GRAD_PROVENANCE="${MEGATRON_NUMERIC_DEBUG_GRAD_PROVENANCE:-0}"
export MEGATRON_GRAD_PROVENANCE_RANKS="${MEGATRON_GRAD_PROVENANCE_RANKS:-}"
export MEGATRON_TENSOR_AUDIT="${MEGATRON_TENSOR_AUDIT:-0}"
export MEGATRON_TENSOR_AUDIT_FILTER="${MEGATRON_TENSOR_AUDIT_FILTER:-}"
export MEGATRON_MOE_STAGE_PROGRESS_LOG="${MEGATRON_MOE_STAGE_PROGRESS_LOG:-0}"
export MEGATRON_MOE_DISPATCH_STATS_LOG="${MEGATRON_MOE_DISPATCH_STATS_LOG:-0}"

export LOG_INTERVAL="${LOG_INTERVAL:-1}"
export TENSORBOARD_LOG_INTERVAL="${TENSORBOARD_LOG_INTERVAL:-1}"

export USE_STREAMBP=0
export MEGATRON_USE_STREAMBP=0
if [[ -z "${STREAMBP_LOCAL_SEQ_LENGTH:-}" ]]; then
  if [[ "${SEQUENCE_PARALLEL:-auto}" == "1" || ( "${SEQUENCE_PARALLEL:-auto}" == "auto" && "$TP" -gt 1 ) ]]; then
    STREAMBP_LOCAL_SEQ_LENGTH=$(( (SEQ_LENGTH + TP - 1) / TP ))
  else
    STREAMBP_LOCAL_SEQ_LENGTH="$SEQ_LENGTH"
  fi
fi
export STREAMBP_LOCAL_SEQ_LENGTH
if [[ -z "${STREAMBP_CHUNK_SIZE:-}" ]]; then
  STREAMBP_CHUNK_SIZE=$(( (STREAMBP_LOCAL_SEQ_LENGTH + 1) / 2 ))
fi
export STREAMBP_CHUNK_SIZE
export STREAMBP_LOGITS_CHUNK_SIZE="${STREAMBP_LOGITS_CHUNK_SIZE:-8192}"
export STREAMBP_MOE_CHUNK_FORWARD="${STREAMBP_MOE_CHUNK_FORWARD:-0}"
export STREAMBP_MOE_MLP_CHUNKS="${STREAMBP_MOE_MLP_CHUNKS:-1}"
export STREAMBP_MOE_MLP_BACKWARD_CHUNKS="${STREAMBP_MOE_MLP_BACKWARD_CHUNKS:-1}"
export MEGATRON_STREAMBP_SKIP_PP_RANKS="${MEGATRON_STREAMBP_SKIP_PP_RANKS-}"
export MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD="${MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD:-0}"
export MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE="${MEGATRON_STREAMBP_MOE_ATTENTION_BACKWARD_CHUNK_SIZE:-$STREAMBP_CHUNK_SIZE}"
export MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS="${MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS:-0}"
export MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD="${MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD:-0}"
export MEGATRON_STREAMBP_HOST_SAVE_HIDDEN="${MEGATRON_STREAMBP_HOST_SAVE_HIDDEN:-0}"
export MEGATRON_STREAMBP_HOST_SAVE_PIN_MEMORY="${MEGATRON_STREAMBP_HOST_SAVE_PIN_MEMORY:-auto}"
export MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD="${MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD:-0}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_MIN_MB="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MIN_MB:-16}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB:-0}"
export MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS="${MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS:-0}"
export MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE="${MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE:-0}"
export MEGATRON_STREAMBP_MOE_REPLAY_FORCE_TRIM="${MEGATRON_STREAMBP_MOE_REPLAY_FORCE_TRIM:-0}"
export MEGATRON_STREAMBP_SUPPRESS_TEMP_OFFLOAD_MODULES="${MEGATRON_STREAMBP_SUPPRESS_TEMP_OFFLOAD_MODULES:-moe_shared}"
export MEGATRON_TE_GROUPED_LINEAR_FUSE_WGRAD_ACCUM="${MEGATRON_TE_GROUPED_LINEAR_FUSE_WGRAD_ACCUM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_FREE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_FREE_MB:-2048}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_RESERVE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_RESERVE_MB:-512}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CACHED_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CACHED_MB:-256}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC:-0}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CRITICAL_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CRITICAL_SYNC:-0}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_FREE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_FREE_MB:-2048}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_RESERVE_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_RESERVE_MB:-1024}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CACHED_MB="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CACHED_MB:-256}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC:-0}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CRITICAL_SYNC="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CRITICAL_SYNC:-1}"
export MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_LOG="${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_LOG:-0}"
export MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG="${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG:-0}"
export MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_RANKS="${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_RANKS:-0,7}"
export MEGATRON_TE_GROUPED_LINEAR_SKIP_RAW_WEIGHT_SAVE="${MEGATRON_TE_GROUPED_LINEAR_SKIP_RAW_WEIGHT_SAVE:-1}"
export MEGATRON_GATED_NORM_TORCH_MM_MIN_TOKENS="${MEGATRON_GATED_NORM_TORCH_MM_MIN_TOKENS:--1}"
export MEGATRON_GATED_NORM_DISABLE_CUTE="${MEGATRON_GATED_NORM_DISABLE_CUTE:-0}"
# Queue offload and tighter DSA/HISA chunks should absorb the long-lived memory
# pressure. Keep TE activation offload opt-in because it adds CPU transfer work
# on the expert path.
export FINE_GRAINED_ACTIVATION_OFFLOADING="${FINE_GRAINED_ACTIVATION_OFFLOADING:-0}"
if [[ "$FINE_GRAINED_ACTIVATION_OFFLOADING" == "1" ]]; then
  export OFFLOAD_MODULES="${OFFLOAD_MODULES:-expert_fc1}"
  export NVTE_CPU_OFFLOAD_V1="${NVTE_CPU_OFFLOAD_V1:-1}"
else
  export OFFLOAD_MODULES="${OFFLOAD_MODULES:-}"
fi
export MEGATRON_TEMP_ACTIVATION_OFFLOAD=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_MODULES=""
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_MIN_MB=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_EMPTY_CACHE=0
export MEGATRON_TEMP_ACTIVATION_OFFLOAD_NON_BLOCKING=0
export MEGATRON_FINE_OFFLOAD_STREAMBP_REPLAY_KEEP_STORAGES="${MEGATRON_FINE_OFFLOAD_STREAMBP_REPLAY_KEEP_STORAGES:-core_attn attn_proj expert_fc1}"
export MEGATRON_FINE_OFFLOAD_FORCE_RELEASE_IN_STREAMBP_REPLAY="${MEGATRON_FINE_OFFLOAD_FORCE_RELEASE_IN_STREAMBP_REPLAY:-0}"
export MEGATRON_FINE_OFFLOAD_PIN_MEMORY="${MEGATRON_FINE_OFFLOAD_PIN_MEMORY:-auto}"
export MEGATRON_FINE_OFFLOAD_PINNED_MAX_MB="${MEGATRON_FINE_OFFLOAD_PINNED_MAX_MB:-64}"
export MEGATRON_FINE_OFFLOAD_STRIDED_COPY_CHUNK_MB="${MEGATRON_FINE_OFFLOAD_STRIDED_COPY_CHUNK_MB:-128}"
export MEGATRON_FINE_OFFLOAD_STRIDED_COPY_NON_BLOCKING="${MEGATRON_FINE_OFFLOAD_STRIDED_COPY_NON_BLOCKING:-0}"
if [[ -z "${MEGATRON_PIPELINE_QUEUE_OFFLOAD+x}" ]]; then
  if (( PP == 1 )); then
    # No pipeline queues exist in the PP=1/no-pipeline profile, so do not carry
    # the previous PP warmup-residency offload knob into this experiment.
    export MEGATRON_PIPELINE_QUEUE_OFFLOAD=0
  else
    export MEGATRON_PIPELINE_QUEUE_OFFLOAD=1
  fi
else
  export MEGATRON_PIPELINE_QUEUE_OFFLOAD
fi
export MEGATRON_PIPELINE_QUEUE_OFFLOAD_MIN_MB="${MEGATRON_PIPELINE_QUEUE_OFFLOAD_MIN_MB:-1}"
if [[ -z "${MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH+x}" ]]; then
  if (( PP == 1 )); then
    export MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH=0
  else
    export MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH=1
  fi
else
  export MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH
fi
export MEGATRON_PIPELINE_QUEUE_OFFLOAD_PIN_MEMORY="${MEGATRON_PIPELINE_QUEUE_OFFLOAD_PIN_MEMORY:-auto}"
if [[ -z "${APPLY_ROPE_FUSION:-}" ]]; then
  if (( CP > 1 )) || [[ "${MEGATRON_DSA_SPLIT_QK:-1}" == "1" ]]; then
    # The fused MLA RoPE path currently bypasses split-Q/K DSA construction.
    # Use generic RoPE for the training profile so DSAttention actually receives
    # split noPE/PE tensors and dispatches the split-Q/K sparse Triton kernels.
    APPLY_ROPE_FUSION=0
  else
    APPLY_ROPE_FUSION=1
  fi
fi
export APPLY_ROPE_FUSION
export INDEXCACHE="${INDEXCACHE:-1}"
export DSA_INDEXCACHE_HISA="${DSA_INDEXCACHE_HISA:-1}"
export DSA_INDEXCACHE_QUANTIZATION="${DSA_INDEXCACHE_QUANTIZATION:-nvfp4_e2m1_ue8m0}"
export DSA_INDEXCACHE_QUANT_EPS="${DSA_INDEXCACHE_QUANT_EPS:-1e-4}"
export DSA_INDEXCACHE_HISA_BLOCK_SIZE="${DSA_INDEXCACHE_HISA_BLOCK_SIZE:-128}"
export DSA_INDEXCACHE_HISA_BLOCK_TOPK="${DSA_INDEXCACHE_HISA_BLOCK_TOPK:-64}"
# Ratio 8.0 is the faster production envelope; the row-shuffled SFT sidecar is
# the data-path fix for short diagnostics no longer seeing only JSONL prefix rows.
export DSA_INDEXCACHE_HISA_COMPRESSION_RATIO="${DSA_INDEXCACHE_HISA_COMPRESSION_RATIO:-8.0}"
export SPINQUANT="${SPINQUANT:-1}"
export USE_HIGGS="${USE_HIGGS:-1}"
export HIGGS_KV_PRESET="${HIGGS_KV_PRESET:-dense_2bit}"
export TURBOQUANT="${TURBOQUANT:-0}"
export MEGATRON_CHUNKED_LM_HEAD_LOSS="${MEGATRON_CHUNKED_LM_HEAD_LOSS:-0}"
export MEGATRON_STREAMBP_FUSED_LCE="${MEGATRON_STREAMBP_FUSED_LCE:-0}"
export MEGATRON_STREAMBP_FUSED_LCE_SP_TILE_SIZE="${MEGATRON_STREAMBP_FUSED_LCE_SP_TILE_SIZE:-1024}"
export LCE_FWD_VOCAB_SPLIT_SIZE="${LCE_FWD_VOCAB_SPLIT_SIZE:-8192}"
export LCE_BWD_VOCAB_SPLIT_SIZE="${LCE_BWD_VOCAB_SPLIT_SIZE:-8192}"
export DSA_LOCAL_QUERY_LENGTH="${DSA_LOCAL_QUERY_LENGTH:-$(( (SEQ_LENGTH + CP - 1) / CP ))}"
# Keep DSA query chunks large enough for throughput while capping transient
# HISA/DSA memory under 32k context.
export DSA_CHUNK_SIZE="${DSA_CHUNK_SIZE:-2048}"
export MEGATRON_DSA_TRITON="${MEGATRON_DSA_TRITON:-1}"
export MEGATRON_DSA_TRITON_INDEXER="${MEGATRON_DSA_TRITON_INDEXER:-1}"
export MEGATRON_DSA_SPLIT_QK="${MEGATRON_DSA_SPLIT_QK:-1}"
export MEGATRON_DSA_REQUIRE_SPLIT_QK="${MEGATRON_DSA_REQUIRE_SPLIT_QK:-1}"
export MEGATRON_DSA_STREAMING_INDEXER_TOPK="${MEGATRON_DSA_STREAMING_INDEXER_TOPK:-1}"
export MEGATRON_DSA_INDEXER_ROPE_FUSION="${MEGATRON_DSA_INDEXER_ROPE_FUSION:-1}"
export MEGATRON_DSA_INDEXER_ROPE_INPLACE="${MEGATRON_DSA_INDEXER_ROPE_INPLACE:-1}"
export MEGATRON_DSA_INDEXER_TORCH_K_NORM="${MEGATRON_DSA_INDEXER_TORCH_K_NORM:-1}"
export MEGATRON_DSA_CP_GATHER_SPLIT_KV_REF="${MEGATRON_DSA_CP_GATHER_SPLIT_KV_REF:-0}"
# Gather CP zigzag halves directly into absolute-position order. This avoids
# the full gathered key/value reorder copies that OOMed job 91.
export MEGATRON_DSA_CP_SORTED_ZIGZAG_GATHER="${MEGATRON_DSA_CP_SORTED_ZIGZAG_GATHER:-1}"
export MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE="${MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE:-4096}"
export MEGATRON_DSA_SORT_TOPK_INDICES="${MEGATRON_DSA_SORT_TOPK_INDICES:-0}"
export MEGATRON_DSA_COMPACT_TOPK_INDICES="${MEGATRON_DSA_COMPACT_TOPK_INDICES:-1}"
export MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS="${MEGATRON_DSA_TRITON_BF16_GRAD_ATOMICS:-1}"
export MEGATRON_DSA_TRITON_BLOCK_K_BWD="${MEGATRON_DSA_TRITON_BLOCK_K_BWD:-32}"
export MEGATRON_DSA_TRITON_BWD_NUM_WARPS="${MEGATRON_DSA_TRITON_BWD_NUM_WARPS:-2}"
export MEGATRON_DSA_BACKWARD_TRIM_CACHE="${MEGATRON_DSA_BACKWARD_TRIM_CACHE:-0}"
export MEGATRON_DSA_SP_Q_PROJ_TRIM_CACHE="${MEGATRON_DSA_SP_Q_PROJ_TRIM_CACHE:-0}"
export MEGATRON_DSA_INDEXER_AUX_LOSS_AUTOSCALE="${MEGATRON_DSA_INDEXER_AUX_LOSS_AUTOSCALE:-1}"
export MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE="${MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE:-token_mean}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD="${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK="${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK:-32768}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS="${MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS:-0}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD="${MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD:-1}"
export MEGATRON_DSA_SPLIT_QK_REENTRANT_RETAIN_GRAPH="${MEGATRON_DSA_SPLIT_QK_REENTRANT_RETAIN_GRAPH:-0}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD:-1}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD:-1}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS:-8}"
export MEGATRON_DSA_CUDA_SPLIT_QK_CUBLASDX_FWD="${MEGATRON_DSA_CUDA_SPLIT_QK_CUBLASDX_FWD:-0}"
export MEGATRON_DSA_CUDA_SPLIT_QK_ROW_FWD="${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_FWD:-0}"
export MEGATRON_DSA_CUDA_KV_BWD="${MEGATRON_DSA_CUDA_KV_BWD:-0}"
export MEGATRON_DSA_CUDA_KV_BWD_TILE_Q="${MEGATRON_DSA_CUDA_KV_BWD_TILE_Q:-2}"
export MEGATRON_DSA_CUDA_KV_BWD_TILE_K="${MEGATRON_DSA_CUDA_KV_BWD_TILE_K:-4}"
export MEGATRON_DSA_VALIDATE_TOPK_INDICES="${MEGATRON_DSA_VALIDATE_TOPK_INDICES:-0}"
export MEGATRON_DSA_STREAM_TRITON_ATTENTION_CHUNKS="${MEGATRON_DSA_STREAM_TRITON_ATTENTION_CHUNKS:-1}"
export MEGATRON_DSA_SP_PROJECT_BEFORE_GATHER="${MEGATRON_DSA_SP_PROJECT_BEFORE_GATHER:-1}"
export MEGATRON_DSA_TEACHER_SCORE_SCRATCH="${MEGATRON_DSA_TEACHER_SCORE_SCRATCH:-1}"
export MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH="${MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH:-1}"
export MEGATRON_HISA_CANDIDATE_SLOT_GROUP="${MEGATRON_HISA_CANDIDATE_SLOT_GROUP:-8}"
export MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB="${MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB:-0}"
export MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB="${MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB:-0}"
export MEGATRON_HISA_CANDIDATE_TRIM_CACHE="${MEGATRON_HISA_CANDIDATE_TRIM_CACHE:-0}"
export MEGATRON_HISA_COMPACT_CANDIDATE_TOPK="${MEGATRON_HISA_COMPACT_CANDIDATE_TOPK:-1}"
export MEGATRON_HISA_SELECTOR_BACKEND="${MEGATRON_HISA_SELECTOR_BACKEND:-megakernel}"
export MEGATRON_HISA_SELECTOR_CUDA="${MEGATRON_HISA_SELECTOR_CUDA:-1}"
export MEGATRON_HISA_MEGAKERNEL_PARALLEL_REFINE="${MEGATRON_HISA_MEGAKERNEL_PARALLEL_REFINE:-1}"
export MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH="${MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH:-0}"
# 32k A4 fine-profile job 129: 512 halves HISA row/candidate-refine calls
# versus 256 and improved the four-step diagnostic without OOM.
export MEGATRON_HISA_SELECTOR_ROW_CHUNK="${MEGATRON_HISA_SELECTOR_ROW_CHUNK:-512}"
export MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES="${MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES:-1}"
export MEGATRON_HISA_BMM_CUBLASDX_REFINE="${MEGATRON_HISA_BMM_CUBLASDX_REFINE:-1}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_HEAD_GROUP="${MEGATRON_HISA_SELECTED_SCORE_BWD_HEAD_GROUP:-8}"
export MEGATRON_HISA_SELECTED_SCORE_BWD_WARP_GROUPED="${MEGATRON_HISA_SELECTED_SCORE_BWD_WARP_GROUPED:-1}"
# Job 175/tile sweep: TILE_N=64 is a small but consistent HISA selected-score
# backward win at the production q=2048/sk=32768/topk=1024 chunk shape; 128 is slower.
export MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N="${MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N:-64}"
export MEGATRON_HISA_ASSUME_SORTED_POSITIONS="${MEGATRON_HISA_ASSUME_SORTED_POSITIONS:-1}"
export MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT="${MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT:-0}"
export MEGATRON_HISA_FUSED_INDEXER_LOSS="${MEGATRON_HISA_FUSED_INDEXER_LOSS:-1}"
export MEGATRON_HISA_TARGET_TRITON="${MEGATRON_HISA_TARGET_TRITON:-1}"
export MEGATRON_HISA_TARGET_BLOCK_K="${MEGATRON_HISA_TARGET_BLOCK_K:-64}"
export MEGATRON_HISA_TARGET_ROW_CHUNK="${MEGATRON_HISA_TARGET_ROW_CHUNK:-512}"
export MEGATRON_HISA_KL_GRAD_TRITON="${MEGATRON_HISA_KL_GRAD_TRITON:-1}"
export MEGATRON_WEIGHTED_SWIGLU_FUSER="${MEGATRON_WEIGHTED_SWIGLU_FUSER:-triton}"
export NVFP4_ACTIVATION_ECO="${NVFP4_ACTIVATION_ECO:-0}"
export NVFP4_ACTIVATION_ECO_MODULES="${NVFP4_ACTIVATION_ECO_MODULES:-all}"
export NVFP4_ACTIVATION_ECO_RECOMPUTE_ONLY="${NVFP4_ACTIVATION_ECO_RECOMPUTE_ONLY:-1}"
export NVFP4_ACTIVATION_ECO_QUANTIZER_BACKEND="${NVFP4_ACTIVATION_ECO_QUANTIZER_BACKEND:-te}"
export NVFP4_ACTIVATION_ECO_CORRECTION_DTYPE="${NVFP4_ACTIVATION_ECO_CORRECTION_DTYPE:-bf16}"
export MEGATRON_ACT_ECO_CORRECTION_ROW_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_ROW_CHUNK:-2048}"
export MEGATRON_ACT_ECO_CORRECTION_OUT_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_OUT_CHUNK:-2048}"
export MEGATRON_ACT_ECO_CORRECTION_IN_CHUNK="${MEGATRON_ACT_ECO_CORRECTION_IN_CHUNK:-0}"
export FLASH_ADAMW_ECO="${FLASH_ADAMW_ECO:-0}"
export FLASH_ADAMW_FSDP_ECO_INJECT="${FLASH_ADAMW_FSDP_ECO_INJECT:-0}"
export MEGATRON_FLASH_ADAMW_FSDP_ECO_INJECT="${MEGATRON_FLASH_ADAMW_FSDP_ECO_INJECT:-$FLASH_ADAMW_FSDP_ECO_INJECT}"
export FLASH_ADAMW_ECO_LR_FLOOR="${FLASH_ADAMW_ECO_LR_FLOOR:-base}"
export FLASH_ADAMW_ECO_PROJECTION="${FLASH_ADAMW_ECO_PROJECTION:-gain}"
export FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_SCALE_BUDGET:-2.0}"
export FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET="${FLASH_ADAMW_ECO_PROJECTION_GAIN_BUDGET:-0.25}"
export FLASH_ADAMW_ECO_PROJECTION_STEPS="${FLASH_ADAMW_ECO_PROJECTION_STEPS:-16}"
export MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST="${MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST:-1}"
export ADAM_EPS="${ADAM_EPS:-1.0e-6}"
export MEGATRON_REAP_LR_GROUPS="${MEGATRON_REAP_LR_GROUPS:-1}"
export MEGATRON_REAP_BACKBONE_LR_MULT="${MEGATRON_REAP_BACKBONE_LR_MULT:-0.2}"
export MEGATRON_REAP_NEW_COMPONENT_LR_MULT="${MEGATRON_REAP_NEW_COMPONENT_LR_MULT:-1.0}"
export MEGATRON_REAP_BACKBONE_UPDATE_CAP_RATIO="${MEGATRON_REAP_BACKBONE_UPDATE_CAP_RATIO:-2.0e-3}"
export MEGATRON_REAP_BACKBONE_UPDATE_CAP_STEPS="${MEGATRON_REAP_BACKBONE_UPDATE_CAP_STEPS:-500}"
export MEGATRON_REAP_BACKBONE_UPDATE_CAP_PARAM_RMS_FLOOR="${MEGATRON_REAP_BACKBONE_UPDATE_CAP_PARAM_RMS_FLOOR:-0.0}"
export MEGATRON_REAP_LR_GROUP_AUDIT="${MEGATRON_REAP_LR_GROUP_AUDIT:-1}"
export MEGATRON_REAP_LR_GROUP_AUDIT_SAMPLE="${MEGATRON_REAP_LR_GROUP_AUDIT_SAMPLE:-32}"
# Megatron's compressed FlashAdamW optimizer checkpoint currently only supports
# the dp_reshardable optimizer-state format. The GCP A4 FSDP shape uses
# optim_grads_params, so save the ordinary optimizer state.
export FLASH_ADAMW_COMPRESS_STATE_DICT="${FLASH_ADAMW_COMPRESS_STATE_DICT:-0}"
if [[ -z "${MEGATRON_PIPELINE_PROGRESS_LOG+x}" ]]; then
  if (( PP == 1 )); then
    export MEGATRON_PIPELINE_PROGRESS_LOG=0
  else
    export MEGATRON_PIPELINE_PROGRESS_LOG=1
  fi
else
  export MEGATRON_PIPELINE_PROGRESS_LOG
fi
export MEGATRON_PIPELINE_PROGRESS_INTERVAL="${MEGATRON_PIPELINE_PROGRESS_INTERVAL:-1}"
export MEGATRON_PIPELINE_PROGRESS_TP_RANKS="${MEGATRON_PIPELINE_PROGRESS_TP_RANKS:-0}"

export MOE_TOKEN_DISPATCHER_TYPE="${MOE_TOKEN_DISPATCHER_TYPE:-flex}"
export MOE_FLEX_DISPATCHER_BACKEND="${MOE_FLEX_DISPATCHER_BACKEND:-deepep}"
export MOE_ROUTER_PADDING_FOR_QUANTIZATION="${MOE_ROUTER_PADDING_FOR_QUANTIZATION:-0}"
export MOE_ROUTER_LOAD_BALANCING_TYPE="${MOE_ROUTER_LOAD_BALANCING_TYPE:-seq_aux_loss}"
export MOE_AUX_LOSS_COEFF="${MOE_AUX_LOSS_COEFF:-0.0}"
export MOE_ROUTER_BIAS_UPDATE_RATE="${MOE_ROUTER_BIAS_UPDATE_RATE:-1e-3}"
export MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD="${MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD:-sign}"
export MOE_ROUTER_QUANTILE_BIAS_ITERS="${MOE_ROUTER_QUANTILE_BIAS_ITERS:-5}"
export MOE_ROUTER_QUANTILE_BIAS_APPLICATION="${MOE_ROUTER_QUANTILE_BIAS_APPLICATION:-delayed}"
export MOE_ROUTER_QUANTILE_BIAS_WARMUP_STEPS="${MOE_ROUTER_QUANTILE_BIAS_WARMUP_STEPS:-0}"
export MOE_ROUTER_QUANTILE_BIAS_SYNC_SCORES="${MOE_ROUTER_QUANTILE_BIAS_SYNC_SCORES:-1}"
export MEGATRON_FREEZE_ROUTER="${MEGATRON_FREEZE_ROUTER:-1}"
# Freeze router weights, not the dynamic expert-bias load-balancing state.
export MEGATRON_FREEZE_ROUTER_EXPERT_BIAS="${MEGATRON_FREEZE_ROUTER_EXPERT_BIAS:-0}"
export MEGATRON_FREEZE_TOKEN_EMBEDDINGS="${MEGATRON_FREEZE_TOKEN_EMBEDDINGS:-1}"
export MEGATRON_MOE_UNPADDING_TRIM_CACHE="${MEGATRON_MOE_UNPADDING_TRIM_CACHE:-0}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE="${MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE:-0}"
export MEGATRON_MOE_EXPERT_FC1_TRIM_GC="${MEGATRON_MOE_EXPERT_FC1_TRIM_GC:-0}"
# Keep the broad cache trims off, but retain a narrow MoE fc2 allocator guard:
# job 121 OOMed in TE grouped-linear fc2 with ~866 MiB cached and 252 MiB free
# while requesting 896 MiB. This only fires when free memory is already critical.
export MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE="${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE:-1}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB="${MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB:-2048}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB="${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB:-256}"
export MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC="${MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC:-0}"
export MEGATRON_MOE_EXPERT_RELEASE_PRE_FC2_REFS="${MEGATRON_MOE_EXPERT_RELEASE_PRE_FC2_REFS:-1}"
export MEGATRON_MOE_SORT_TRIM_CACHE="${MEGATRON_MOE_SORT_TRIM_CACHE:-0}"
export MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT="${MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT:-0}"
export MEGATRON_MOE_COMBINE_REDUCE_SCATTER_DTYPE="${MEGATRON_MOE_COMBINE_REDUCE_SCATTER_DTYPE:-input}"
export MEGATRON_PREWARM_PIPELINE_P2P="${MEGATRON_PREWARM_PIPELINE_P2P:-1}"
export MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE="${MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE:-1}"
export MEGATRON_DEEPEP_COMPACT_STABLE_MAP="${MEGATRON_DEEPEP_COMPACT_STABLE_MAP:-0}"
export MEGATRON_DEEPEP_COMPACT_ROW_CHUNK="${MEGATRON_DEEPEP_COMPACT_ROW_CHUNK:-131072}"
export MEGATRON_DEEPEP_COMPACT_BACKEND="${MEGATRON_DEEPEP_COMPACT_BACKEND:-rowcuda}"
export MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE="${MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE:-1}"
export MEGATRON_DEEPEP_COMPACT_CUDA_BACKWARD="${MEGATRON_DEEPEP_COMPACT_CUDA_BACKWARD:-0}"
export MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH="${MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH:-1}"
export MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE="${MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE:-0}"
export MEGATRON_DEEPEP_NUM_SMS="${MEGATRON_DEEPEP_NUM_SMS:-24}"
export MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE="${MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE:-8}"
export MEGATRON_DEEPEP_COMBINE_NUM_SMS="${MEGATRON_DEEPEP_COMBINE_NUM_SMS:-24}"
export MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS="${MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS:-16}"
export MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS="${MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS:-256}"
export MEGATRON_DEEPEP_COMBINE_RDMA_SEND_TOKENS="${MEGATRON_DEEPEP_COMBINE_RDMA_SEND_TOKENS:-}"
export MEGATRON_DEEPEP_COMBINE_RDMA_RECV_TOKENS="${MEGATRON_DEEPEP_COMBINE_RDMA_RECV_TOKENS:-}"

export GLOO_SOCKET_IFNAME="${GLOO_SOCKET_IFNAME:-eth0}"
export NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-eth0}"
export NCCL_NVLS_ENABLE="${NCCL_NVLS_ENABLE:-0}"
export USE_NCCL_GIB="${USE_NCCL_GIB:-0}"
if [[ "$USE_NCCL_GIB" == "1" ]]; then
  if [[ -f /usr/local/gib/scripts/set_nccl_env.sh ]]; then
    # shellcheck disable=SC1091
    source /usr/local/gib/scripts/set_nccl_env.sh
    export LD_LIBRARY_PATH="/usr/local/gib/lib64:${LD_LIBRARY_PATH:-}"
  else
    echo "WARNING: USE_NCCL_GIB=1 but /usr/local/gib/scripts/set_nccl_env.sh is missing" >&2
  fi
fi
if [[ -z "${MEGATRON_LOCAL_RANK_NCCL_HCA+x}" ]]; then
  export MEGATRON_LOCAL_RANK_NCCL_HCA=0
fi
export MEGATRON_NCCL_LOCAL_RANK_HCAS="${MEGATRON_NCCL_LOCAL_RANK_HCAS:-mlx5_0,mlx5_1,mlx5_2,mlx5_3,mlx5_4,mlx5_5,mlx5_6,mlx5_7}"
if [[ "$MEGATRON_LOCAL_RANK_NCCL_HCA" == "1" ]]; then
  unset NCCL_IB_HCA
elif [[ "$USE_NCCL_GIB" != "1" ]]; then
  export NCCL_IB_HCA="${NCCL_IB_HCA:-$MEGATRON_NCCL_LOCAL_RANK_HCAS}"
fi

if ! ulimit -l unlimited 2>/dev/null; then
  echo "WARNING: could not raise memlock soft limit to unlimited" >&2
fi

export TRITON_CACHE_DIR="${TRITON_CACHE_DIR:-$HOME/.cache/triton/deepseek_v32_reap_sft}"
export TRITON_CACHE_AUTOTUNING="${TRITON_CACHE_AUTOTUNING:-1}"
export DG_JIT_CACHE_DIR="${DG_JIT_CACHE_DIR:-$HOME/.cache/deep_gemm/deepseek_v32_reap_sft}"
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"
if [[ -n "${SLURM_JOB_ID:-}" ]]; then
  export TORCHRUN_LOG_DIR="${TORCHRUN_LOG_DIR:-$HOME/logs/torchrun/${SLURM_JOB_NAME:-slurm}-$SLURM_JOB_ID/node${SLURM_NODEID:-0}}"
  export TORCHRUN_REDIRECTS="${TORCHRUN_REDIRECTS:-3}"
  export TORCHRUN_TEE="${TORCHRUN_TEE:-0}"
fi
if [[ -z "${CC:-}" && -x /usr/bin/gcc ]]; then
  export CC=/usr/bin/gcc
fi
if [[ -z "${CXX:-}" && -x /usr/bin/g++ ]]; then
  export CXX=/usr/bin/g++
fi

ensure_patched_deepep() {
  if [[ "${MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH:-0}" != "1" && "${MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE:-0}" != "1" ]]; then
    return
  fi

  if uv run --no-sync python - <<'PY' >/dev/null 2>&1
import deep_ep
missing = [
    name
    for name in ("dispatch_expert_major", "combine_expert_major")
    if not hasattr(deep_ep.Buffer, name)
]
if missing:
    raise SystemExit(f"deep_ep.Buffer missing patched APIs: {missing}")
PY
  then
    return
  fi

  local wheel="${DEEP_EP_WHEEL:-$REPO_DIR/handoff/gcp-a4/wheelhouse/deep_ep-1.2.1+9af0e0d-cp312-cp312-linux_x86_64.whl}"
  if [[ ! -f "$wheel" ]]; then
    echo "Patched DeepEP wheel is required but missing: $wheel" >&2
    exit 2
  fi

  echo "Installing patched DeepEP wheel on $(hostname -s): $wheel" >&2
  uv pip install --force-reinstall "$wheel" >&2
  uv run --no-sync python - <<'PY' >&2
import deep_ep
missing = [
    name
    for name in ("dispatch_expert_major", "combine_expert_major")
    if not hasattr(deep_ep.Buffer, name)
]
if missing:
    raise SystemExit(f"patched DeepEP install failed; missing APIs: {missing}")
print("patched_deepep_ok", deep_ep.__file__)
PY
}

ensure_patched_deepep

# Split-Q/K reentrant K/V backward is disabled in the current fast path, so the
# TE retain patch stays opt-in for diagnostics that explicitly re-enable it.
export MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD="${MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD:-0}"
if [[ "${MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD}" == "1" ]]; then
  uv run --no-sync python tools/patch_te_reentrant_backward.py >&2
fi
if [[ "${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM}" == "1" ]]; then
  uv run --no-sync python tools/patch_te_grouped_linear_alloc_guard.py >&2
fi
# Keep recompute opt-in for the PP5/DP3 baseline. Broad MoE recompute adds heavy
# repeated grouped-GEMM work, so use the plain pipeline shape first and only add
# selective recompute if the next profile proves a specific module needs it.
export RECOMPUTE="${RECOMPUTE:-0}"
export RECOMPUTE_GRANULARITY="${RECOMPUTE_GRANULARITY:-selective}"
export RECOMPUTE_MODULES="${RECOMPUTE_MODULES:-mla_up_proj}"
export RECOMPUTE_METHOD="${RECOMPUTE_METHOD:-}"
export RECOMPUTE_NUM_LAYERS="${RECOMPUTE_NUM_LAYERS:-}"
export FASTPATH_STRICT="${FASTPATH_STRICT:-1}"

if [[ "$FASTPATH_STRICT" == "1" ]]; then
  fastpath_errors=()
  require_fastpath_eq() {
    local name="$1"
    local expected="$2"
    local actual="${!name:-}"
    if [[ "$actual" != "$expected" ]]; then
      fastpath_errors+=("$name=$actual expected $expected")
    fi
  }
  require_fastpath_nonchunked_or_zero() {
    local name="$1"
    local local_seq="$2"
    local actual="${!name:-}"
    if [[ ! "$actual" =~ ^[0-9]+$ ]]; then
      fastpath_errors+=("$name=$actual expected integer 0 or >= $local_seq")
      return
    fi
    if (( actual > 0 && actual < local_seq )); then
      fastpath_errors+=("$name=$actual chunks local sequence length $local_seq")
    fi
  }
  require_fastpath_positive_integer() {
    local name="$1"
    local actual="${!name:-}"
    if [[ ! "$actual" =~ ^[0-9]+$ ]] || (( actual <= 0 )); then
      fastpath_errors+=("$name=$actual expected positive integer")
    fi
  }
  require_fastpath_min_integer() {
    local name="$1"
    local min_value="$2"
    local actual="${!name:-}"
    if [[ ! "$actual" =~ ^[0-9]+$ ]] || (( actual < min_value )); then
      fastpath_errors+=("$name=$actual expected integer >= $min_value")
    fi
  }
  require_fastpath_eq USE_STREAMBP 0
  require_fastpath_eq MEGATRON_USE_STREAMBP 0
  require_fastpath_eq STREAMBP_MOE_CHUNK_FORWARD 0
  require_fastpath_eq STREAMBP_MOE_MLP_CHUNKS 1
  require_fastpath_eq STREAMBP_MOE_MLP_BACKWARD_CHUNKS 1
  require_fastpath_eq MEGATRON_STREAMBP_SPLIT_MOE_MLP_ATTENTION_BACKWARD 0
  require_fastpath_eq MEGATRON_STREAMBP_REPLAY_SAVE_QUANTIZED_TE_INPUTS 0
  require_fastpath_eq MEGATRON_STREAMBP_RELEASE_MLP_INPUT_BEFORE_BACKWARD 0
  require_fastpath_eq MEGATRON_STREAMBP_HOST_SAVE_HIDDEN 0
  require_fastpath_eq MEGATRON_STREAMBP_REPLAY_SAVED_TENSOR_OFFLOAD 0
  require_fastpath_eq MEGATRON_STREAMBP_REPLAY_OFFLOAD_FREE_MB 0
  require_fastpath_eq MEGATRON_STREAMBP_REPLAY_OFFLOAD_MAX_TENSORS 0
  require_fastpath_eq MEGATRON_STREAMBP_MOE_REPLAY_TRIM_CACHE 0
  require_fastpath_eq MEGATRON_STREAMBP_MOE_REPLAY_FORCE_TRIM 0
  require_fastpath_eq MEGATRON_FINE_OFFLOAD_FORCE_RELEASE_IN_STREAMBP_REPLAY 0
  require_fastpath_eq MEGATRON_CHUNKED_LM_HEAD_LOSS 0
  require_fastpath_eq MEGATRON_STREAMBP_FUSED_LCE 0
  if [[ "${FINE_GRAINED_ACTIVATION_OFFLOADING:-0}" == "1" ]]; then
    require_fastpath_eq OFFLOAD_MODULES "expert_fc1"
    require_fastpath_eq NVTE_CPU_OFFLOAD_V1 1
  else
    require_fastpath_eq FINE_GRAINED_ACTIVATION_OFFLOADING 0
    require_fastpath_eq OFFLOAD_MODULES ""
  fi
  require_fastpath_eq MEGATRON_TEMP_ACTIVATION_OFFLOAD 0
  require_fastpath_eq MEGATRON_TEMP_ACTIVATION_OFFLOAD_MODULES ""
  require_fastpath_eq MEGATRON_TEMP_ACTIVATION_OFFLOAD_MIN_MB 0
  require_fastpath_eq MEGATRON_TEMP_ACTIVATION_OFFLOAD_EMPTY_CACHE 0
  require_fastpath_eq MEGATRON_TEMP_ACTIVATION_OFFLOAD_NON_BLOCKING 0
  if (( PP == 1 )); then
    require_fastpath_eq MEGATRON_PIPELINE_QUEUE_OFFLOAD 0
    require_fastpath_eq MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH 0
  else
    require_fastpath_eq MEGATRON_PIPELINE_QUEUE_OFFLOAD 1
    require_fastpath_eq MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH 1
  fi
  require_fastpath_eq RECOMPUTE 0
  require_fastpath_eq NVFP4_ACTIVATION_ECO 0
  require_fastpath_eq FLASH_ADAMW_ECO 0
  require_fastpath_eq FLASH_ADAMW_FSDP_ECO_INJECT 0
  require_fastpath_eq MEGATRON_REAP_LR_GROUPS 1
  require_fastpath_eq MEGATRON_REAP_BACKBONE_LR_MULT "${FASTPATH_EXPECT_REAP_BACKBONE_LR_MULT:-0.2}"
  require_fastpath_eq MEGATRON_REAP_NEW_COMPONENT_LR_MULT "${FASTPATH_EXPECT_REAP_NEW_COMPONENT_LR_MULT:-1.0}"
  require_fastpath_eq MEGATRON_REAP_BACKBONE_UPDATE_CAP_RATIO 2.0e-3
  require_fastpath_eq MEGATRON_DISABLE_JIT_FUSER 0
  if [[ "$USE_MEGATRON_FSDP" == "1" && "$DATA_PARALLEL_SHARDING_STRATEGY" != "dp_reshardable" ]]; then
    require_fastpath_eq FLASH_ADAMW_COMPRESS_STATE_DICT 0
  fi
  require_fastpath_eq EMPTY_UNUSED_MEMORY_LEVEL 0
  if [[ "$USE_MEGATRON_FSDP" == "1" ]]; then
    require_fastpath_min_integer CUDA_DEVICE_MAX_CONNECTIONS 2
  fi
  if [[ "${EXTRA_MEGATRON_ARGS:-}" == *"--cross-entropy-loss-fusion"* ]]; then
    fastpath_errors+=("EXTRA_MEGATRON_ARGS requests --cross-entropy-loss-fusion; expected full-logit vocab_parallel_cross_entropy path")
  fi
  require_fastpath_positive_integer DSA_CHUNK_SIZE
  require_fastpath_eq MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD 0
  require_fastpath_eq MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK 32768
  require_fastpath_eq MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS 0
  require_fastpath_eq MEGATRON_DSA_SPLIT_QK_REENTRANT_PACK_KV_GRAD 1
  require_fastpath_eq MEGATRON_DSA_SPLIT_QK_REENTRANT_RETAIN_GRAPH 0
  require_fastpath_eq MEGATRON_DSA_CP_GATHER_SPLIT_KV_REF 0
  require_fastpath_eq MEGATRON_DSA_CP_SORTED_ZIGZAG_GATHER 1
  require_fastpath_eq MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD 1
  require_fastpath_eq MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD 1
  require_fastpath_eq MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS 8
  require_fastpath_eq MEGATRON_DSA_CUDA_SPLIT_QK_CUBLASDX_FWD 0
  require_fastpath_eq MEGATRON_DSA_CUDA_SPLIT_QK_ROW_FWD 0
  require_fastpath_eq MEGATRON_DSA_TEACHER_SCORE_SCRATCH 1
  require_fastpath_eq MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH 1
  require_fastpath_eq MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE token_mean
  require_fastpath_eq CALCULATE_PER_TOKEN_LOSS 1
  require_fastpath_eq DATALOADER_TYPE cyclic
  require_fastpath_eq MEGATRON_SFT_SHUFFLE_ROWS 1
  require_fastpath_eq MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB 0
  require_fastpath_eq MEGATRON_HISA_CANDIDATE_FREE_MEM_RESERVE_MB 0
  require_fastpath_eq MEGATRON_HISA_CANDIDATE_TRIM_CACHE 0
  require_fastpath_eq MEGATRON_DSA_BACKWARD_TRIM_CACHE 0
  require_fastpath_eq MEGATRON_DSA_SP_Q_PROJ_TRIM_CACHE 0
  require_fastpath_eq MEGATRON_MOE_UNPADDING_TRIM_CACHE 0
  require_fastpath_eq MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE 0
  require_fastpath_eq MEGATRON_MOE_EXPERT_FC1_TRIM_GC 0
  require_fastpath_eq MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE 1
  require_fastpath_eq MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC 0
  require_fastpath_eq MEGATRON_MOE_EXPERT_RELEASE_PRE_FC2_REFS 1
  require_fastpath_eq MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM 1
  require_fastpath_eq MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC 0
  require_fastpath_eq MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CRITICAL_SYNC 0
  require_fastpath_eq MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM 1
  require_fastpath_eq MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC 0
  require_fastpath_eq MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CRITICAL_SYNC 1
  require_fastpath_eq MEGATRON_TE_GROUPED_LINEAR_SKIP_RAW_WEIGHT_SAVE 1
  require_fastpath_eq MEGATRON_GATED_NORM_TORCH_MM_MIN_TOKENS -1
  require_fastpath_eq MEGATRON_GATED_NORM_DISABLE_CUTE 0
  require_fastpath_eq MEGATRON_MOE_SORT_TRIM_CACHE 0
  require_fastpath_eq MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT 0
  require_fastpath_eq MOE_TOKEN_DISPATCHER_TYPE flex
  require_fastpath_eq MOE_FLEX_DISPATCHER_BACKEND deepep
  require_fastpath_eq MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE 1
  require_fastpath_eq MEGATRON_DEEPEP_COMPACT_BACKEND rowcuda
  require_fastpath_eq MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE 1
  require_fastpath_eq MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH 1
  require_fastpath_eq MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE 0
  require_fastpath_eq MEGATRON_DEEPEP_NUM_SMS 24
  require_fastpath_eq MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE 8
  require_fastpath_eq MEGATRON_DEEPEP_COMBINE_NUM_SMS 24
  require_fastpath_eq MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS 16
  require_fastpath_eq MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS 256
  require_fastpath_eq MOE_ROUTER_PADDING_FOR_QUANTIZATION 0
  require_fastpath_eq MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD sign
  require_fastpath_eq MOE_ROUTER_QUANTILE_BIAS_APPLICATION delayed
  require_fastpath_eq MEGATRON_FREEZE_ROUTER 1
  require_fastpath_eq MEGATRON_FREEZE_ROUTER_EXPERT_BIAS 0
  require_fastpath_eq MEGATRON_FREEZE_TOKEN_EMBEDDINGS 1
  require_fastpath_eq INDEXCACHE 1
  require_fastpath_eq DSA_INDEXCACHE_HISA 1
  require_fastpath_eq DSA_INDEXER_TOPK 1024
  require_fastpath_eq DSA_INDEXCACHE_HISA_COMPRESSION_RATIO 8.0
  require_fastpath_eq USE_HIGGS 1
  require_fastpath_eq TURBOQUANT 0
  require_fastpath_eq MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT 0
  require_fastpath_eq MEGATRON_HISA_FUSED_INDEXER_LOSS 1
  require_fastpath_eq MEGATRON_HISA_SELECTOR_BACKEND megakernel
  require_fastpath_eq MEGATRON_HISA_MEGAKERNEL_PARALLEL_REFINE 1
  require_fastpath_eq MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH 0
  require_fastpath_eq MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES 1
  require_fastpath_eq MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N 64
  require_fastpath_min_integer MEGATRON_HISA_CANDIDATE_SLOT_GROUP 8
  require_fastpath_min_integer MEGATRON_HISA_SELECTOR_ROW_CHUNK 512
  require_fastpath_min_integer MEGATRON_HISA_TARGET_ROW_CHUNK 512
  require_fastpath_eq MEGATRON_HISA_COMPACT_CANDIDATE_TOPK 1
  require_fastpath_eq APPLY_ROPE_FUSION 0
  require_fastpath_eq MEGATRON_DSA_SPLIT_QK 1
  require_fastpath_eq MEGATRON_DSA_REQUIRE_SPLIT_QK 1
  require_fastpath_eq MEGATRON_DSA_STREAMING_INDEXER_TOPK 1
  require_fastpath_eq MEGATRON_DSA_COMPACT_TOPK_INDICES 1
  if (( ${#fastpath_errors[@]} > 0 )); then
    {
      echo "FASTPATH_STRICT=1 rejected this launch profile:"
      printf '  %s\n' "${fastpath_errors[@]}"
      echo "Set FASTPATH_STRICT=0 only for an intentional diagnostic run."
    } >&2
    exit 2
  fi
fi

cat >&2 <<EOF
GCP A4 launch shape:
  discovered_nodes=$discovered_count selected_nodes=$NNODES node_rank=$NODE_RANK
  master=$MASTER_ADDR:$MASTER_PORT world_size=$WORLD_SIZE
  TP=$TP PP=$PP CP=$CP EP=$EP ETP=$ETP DP=$dp expert_dp=$expert_dp
  MBS=$MICRO_BATCH_SIZE GBS=$GLOBAL_BATCH_SIZE grad_accum=$NUM_MICROBATCHES
  lr=$LR min_lr=$MIN_LR warmup_samples=$LR_WARMUP_SAMPLES adam_eps=$ADAM_EPS dsa_loss_coeff=$DSA_INDEXER_LOSS_COEFF workers=$NUM_WORKERS reap_lr_groups=$MEGATRON_REAP_LR_GROUPS backbone_lr_mult=$MEGATRON_REAP_BACKBONE_LR_MULT new_component_lr_mult=$MEGATRON_REAP_NEW_COMPONENT_LR_MULT backbone_update_cap=${MEGATRON_REAP_BACKBONE_UPDATE_CAP_RATIO}/${MEGATRON_REAP_BACKBONE_UPDATE_CAP_STEPS}/floor:${MEGATRON_REAP_BACKBONE_UPDATE_CAP_PARAM_RMS_FLOOR} lr_audit=$MEGATRON_REAP_LR_GROUP_AUDIT
  fastpath_strict=$FASTPATH_STRICT streambp=$USE_STREAMBP megatron_use_streambp=$MEGATRON_USE_STREAMBP vpp_enabled=$ENABLE_VPP inferred_vpp=$INFERRED_VPP_SIZE use_tp_pp_dp_mapping=$USE_TP_PP_DP_MAPPING te_reentrant_retain=$MEGATRON_TE_RETAIN_TENSOR_OBJECTS_FOR_REENTRANT_BACKWARD layout=${PIPELINE_MODEL_PARALLEL_LAYOUT:-auto}
  fsdp=$USE_MEGATRON_FSDP sharding=$DATA_PARALLEL_SHARDING_STRATEGY fsdp_meta_init=$FSDP_INIT_MODEL_WITH_META_DEVICE fsdp_nccl_ub=$FSDP_USE_NCCL_UB fsdp_double_buffer=$FSDP_DOUBLE_BUFFER fsdp_flush_ready_buckets=$MEGATRON_FSDP_FLUSH_READY_BUCKETS_ON_RESET fsdp_ag_group=$FSDP_CREATE_ALL_GATHER_GROUP fsdp_manual_registration=$FSDP_MANUAL_REGISTRATION fsdp_disable_symmetric_registration=$FSDP_DISABLE_SYMMETRIC_REGISTRATION
  grad_safety: reduce_bf16=$GRAD_REDUCE_IN_BF16 skip_nonfinite_grad_norm=$MEGATRON_SKIP_NONFINITE_GRAD_NORM nonfinite_ownership=$MEGATRON_NONFINITE_GRAD_OWNERSHIP nonfinite_params=$MEGATRON_GRAD_OWNERSHIP_NONFINITE_PARAMS
  recompute=$RECOMPUTE granularity=$RECOMPUTE_GRANULARITY modules="${RECOMPUTE_MODULES:-}" method=$RECOMPUTE_METHOD num_layers=$RECOMPUTE_NUM_LAYERS
  profile_run=${PROFILE_RUN:-0} loss_autopsy=${LOSS_AUTOPSY:-0} enable_profile=${ENABLE_PROFILING:-0} profiler=${USE_PYTORCH_PROFILER:-0} profile_steps=${PROFILE_STEP_START:-4}-${PROFILE_STEP_END:-6} profile_ranks=${PROFILE_RANKS:-<unset>} fine_profile=${MEGATRON_FINE_PROFILE:-0}:${MEGATRON_FINE_PROFILE_RANKS:-<unset>} profile_memory=${PYTORCH_PROFILER_PROFILE_MEMORY:-0} profile_flops=${PYTORCH_PROFILER_WITH_FLOPS:-0} profile_modules=${PYTORCH_PROFILER_WITH_MODULES:-0} tensorboard_logs=${TENSORBOARD_LOGS_PATH:-<default>} dataloader=${DATALOADER_TYPE} sft_finetune=${SFT_FINETUNE} sft_shuffle=${MEGATRON_SFT_SHUFFLE_ROWS}:${MEGATRON_SFT_SHUFFLE_SEED} sft_mask_synthetic_tools=${MEGATRON_SFT_MASK_SYNTHETIC_TOOL_CALLS} calculate_per_token_loss=${CALCULATE_PER_TOKEN_LOSS} disable_jit_fuser=$MEGATRON_DISABLE_JIT_FUSER
  debug_hooks: numeric=$MEGATRON_NUMERIC_DEBUG ranks=${MEGATRON_NUMERIC_DEBUG_RANKS:-<unset>} loss_diag=$MEGATRON_LOSS_DIAGNOSTICS batch_diag=$MEGATRON_BATCH_DIAGNOSTICS grad_summary=${MEGATRON_NUMERIC_DEBUG_GRAD_SUMMARY:-0} grad_hooks=${MEGATRON_NUMERIC_DEBUG_GRAD_HOOKS:-0} grad_provenance=${MEGATRON_GRAD_PROVENANCE:-0}:${MEGATRON_GRAD_PROVENANCE_RANKS:-<unset>} finalize_grad=${MEGATRON_NUMERIC_DEBUG_FINALIZE_GRAD:-0} ddp_grad=${MEGATRON_NUMERIC_DEBUG_DDP_GRAD:-0} fsdp_grad=${MEGATRON_NUMERIC_DEBUG_FSDP_GRAD:-0} optimizer_grad=${MEGATRON_NUMERIC_DEBUG_OPTIMIZER_GRAD:-0} flashopt=${MEGATRON_NUMERIC_DEBUG_FLASHOPT:-0} update_delta=${MEGATRON_UPDATE_DELTA_DEBUG:-0}:${MEGATRON_UPDATE_DELTA_RANKS:-<unset>}/limit:${MEGATRON_UPDATE_DELTA_PARAM_LIMIT:-<unset>}/force_limit:${MEGATRON_UPDATE_DELTA_FORCE_PARAM_LIMIT:-<unset>}/sample:${MEGATRON_UPDATE_DELTA_SAMPLE_ELEMS:-<unset>} forward_hooks=${MEGATRON_NUMERIC_DEBUG_FORWARD_HOOKS:-0} dsa_debug=${MEGATRON_NUMERIC_DEBUG_DSA:-0} router_debug=${MEGATRON_NUMERIC_DEBUG_ROUTER:-0} tensor_audit=$MEGATRON_TENSOR_AUDIT tensor_audit_filter="${MEGATRON_TENSOR_AUDIT_FILTER:-}" moe_stage_progress=${MEGATRON_MOE_STAGE_PROGRESS_LOG:-0} moe_dispatch_stats=${MEGATRON_MOE_DISPATCH_STATS_LOG:-0}
  torch_extensions_dir=$TORCH_EXTENSIONS_DIR
  torchrun_log_dir=${TORCHRUN_LOG_DIR:-<unset>} torchrun_tee=${TORCHRUN_TEE:-<unset>} torchrun_redirects=${TORCHRUN_REDIRECTS:-<unset>}
  pipeline_progress=$MEGATRON_PIPELINE_PROGRESS_LOG interval=$MEGATRON_PIPELINE_PROGRESS_INTERVAL tp_ranks=$MEGATRON_PIPELINE_PROGRESS_TP_RANKS
  activation_offload=$FINE_GRAINED_ACTIVATION_OFFLOADING temp_activation_offload=$MEGATRON_TEMP_ACTIVATION_OFFLOAD pipeline_queue_offload=$MEGATRON_PIPELINE_QUEUE_OFFLOAD queue_depth=$MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH offload_modules="${OFFLOAD_MODULES}"
  overlap_param_gather=$OVERLAP_PARAM_GATHER cuda_device_max_connections=$CUDA_DEVICE_MAX_CONNECTIONS
  dispatcher=$MOE_TOKEN_DISPATCHER_TYPE backend=$MOE_FLEX_DISPATCHER_BACKEND
  moe_local: compact_deepep=$MEGATRON_DEEPEP_COMPACT_LOCAL_PERMUTE compact_backend=$MEGATRON_DEEPEP_COMPACT_BACKEND expert_major_dispatch=$MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH expert_major_combine=$MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE cuda_unpermute=$MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE cuda_backward=$MEGATRON_DEEPEP_COMPACT_CUDA_BACKWARD stable_map=$MEGATRON_DEEPEP_COMPACT_STABLE_MAP row_chunk=$MEGATRON_DEEPEP_COMPACT_ROW_CHUNK
  deepep_combine_config: group_size=${MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE:-default} sms=${MEGATRON_DEEPEP_COMBINE_NUM_SMS:-default} nvl_send=${MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS:-default} nvl_recv=${MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS:-default} rdma_send=${MEGATRON_DEEPEP_COMBINE_RDMA_SEND_TOKENS:-default} rdma_recv=${MEGATRON_DEEPEP_COMBINE_RDMA_RECV_TOKENS:-default}
  higgs=$USE_HIGGS indexcache=$INDEXCACHE hisa=$DSA_INDEXCACHE_HISA turboquant=$TURBOQUANT flash_adamw_eco=$FLASH_ADAMW_ECO flash_adamw_fsdp_eco_inject=$FLASH_ADAMW_FSDP_ECO_INJECT
  cache_policy: empty_unused_memory_level=$EMPTY_UNUSED_MEMORY_LEVEL allocator="$PYTORCH_CUDA_ALLOC_CONF" dsa_bwd_trim=$MEGATRON_DSA_BACKWARD_TRIM_CACHE dsa_sp_q_trim=$MEGATRON_DSA_SP_Q_PROJ_TRIM_CACHE moe_unpad_trim=$MEGATRON_MOE_UNPADDING_TRIM_CACHE moe_fc1_trim=$MEGATRON_MOE_EXPERT_FC1_TRIM_CACHE moe_fc2_trim=$MEGATRON_MOE_EXPERT_FC2_TRIM_CACHE/free_mb:${MEGATRON_MOE_EXPERT_FC2_TRIM_FREE_MB}/cached_mb:${MEGATRON_MOE_EXPERT_FC2_TRIM_CACHED_MB}/sync:${MEGATRON_MOE_EXPERT_FC2_TRIM_SYNC}/release_pre_refs:${MEGATRON_MOE_EXPERT_RELEASE_PRE_FC2_REFS} te_grouped_linear_pre_input_trim=$MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM/free_mb:${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_FREE_MB}/reserve_mb:${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_RESERVE_MB}/cached_mb:${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CACHED_MB}/sync:${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_SYNC}/critical_sync:${MEGATRON_TE_GROUPED_LINEAR_PRE_INPUT_TRIM_CRITICAL_SYNC} te_grouped_linear_pre_output_trim=$MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM/free_mb:${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_FREE_MB}/reserve_mb:${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_RESERVE_MB}/cached_mb:${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CACHED_MB}/sync:${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_SYNC}/critical_sync:${MEGATRON_TE_GROUPED_LINEAR_PRE_OUTPUT_TRIM_CRITICAL_SYNC}/audit:${MEGATRON_TE_GROUPED_LINEAR_ALLOC_AUDIT_LOG}/skip_raw_weight_save:${MEGATRON_TE_GROUPED_LINEAR_SKIP_RAW_WEIGHT_SAVE} moe_sort_trim=$MEGATRON_MOE_SORT_TRIM_CACHE mla_key_trim=$MEGATRON_MLA_TRIM_CACHE_BEFORE_KEY_CAT fc1_gc=$MEGATRON_MOE_EXPERT_FC1_TRIM_GC
  kernels: apply_rope_fusion=$APPLY_ROPE_FUSION dsa_triton=$MEGATRON_DSA_TRITON dsa_indexer=$MEGATRON_DSA_TRITON_INDEXER dsa_aux_autoscale=$MEGATRON_DSA_INDEXER_AUX_LOSS_AUTOSCALE dsa_aux_scale_mode=$MEGATRON_DSA_INDEXER_AUX_LOSS_SCALE_MODE split_qk=$MEGATRON_DSA_SPLIT_QK require_split_qk=$MEGATRON_DSA_REQUIRE_SPLIT_QK split_qk_reentrant_kv=$MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD reentrant_retain_graph=$MEGATRON_DSA_SPLIT_QK_REENTRANT_RETAIN_GRAPH cp_gather_split_kv_ref=$MEGATRON_DSA_CP_GATHER_SPLIT_KV_REF cp_sorted_zigzag_gather=$MEGATRON_DSA_CP_SORTED_ZIGZAG_GATHER topk=$DSA_INDEXER_TOPK compact_topk=$MEGATRON_DSA_COMPACT_TOPK_INDICES dsa_local_query=$DSA_LOCAL_QUERY_LENGTH dsa_query_chunk=$DSA_CHUNK_SIZE dsa_key_block=$MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE dsa_kv_bwd_chunk=$MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK defer_query_grads=$MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS cuda_split_qk_cublasdx_fwd=$MEGATRON_DSA_CUDA_SPLIT_QK_CUBLASDX_FWD cuda_split_qk_row_fwd=$MEGATRON_DSA_CUDA_SPLIT_QK_ROW_FWD cuda_row_query_bwd=$MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD cuda_row_bwd_warps=$MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS teacher_score_scratch=$MEGATRON_DSA_TEACHER_SCORE_SCRATCH bwd_score_scratch=$MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH
  hisa: selector_backend=$MEGATRON_HISA_SELECTOR_BACKEND selector_cuda=$MEGATRON_HISA_SELECTOR_CUDA parallel_refine=$MEGATRON_HISA_MEGAKERNEL_PARALLEL_REFINE streaming_scratch=$MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH bmm_fp32_accum_tensorcores=$MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES selector_row_chunk=$MEGATRON_HISA_SELECTOR_ROW_CHUNK target_triton=$MEGATRON_HISA_TARGET_TRITON target_row_chunk=$MEGATRON_HISA_TARGET_ROW_CHUNK selected_score_bwd_tile=$MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N fused_indexer_loss=$MEGATRON_HISA_FUSED_INDEXER_LOSS candidate_slot_group=$MEGATRON_HISA_CANDIDATE_SLOT_GROUP candidate_temp_mb=$MEGATRON_HISA_CANDIDATE_MAX_TEMP_MB candidate_trim=$MEGATRON_HISA_CANDIDATE_TRIM_CACHE
  quant_kernels: higgs_preset=$HIGGS_KV_PRESET indexcache_quant=$DSA_INDEXCACHE_QUANTIZATION indexcache_hisa_block=${DSA_INDEXCACHE_HISA_BLOCK_SIZE}x${DSA_INDEXCACHE_HISA_BLOCK_TOPK}/ratio:${DSA_INDEXCACHE_HISA_COMPRESSION_RATIO} activation_eco=$NVFP4_ACTIVATION_ECO/$NVFP4_ACTIVATION_ECO_QUANTIZER_BACKEND flash_adamw_eco=$FLASH_ADAMW_ECO flash_adamw_fsdp_eco_inject=$FLASH_ADAMW_FSDP_ECO_INJECT flash_adamw_compress=$FLASH_ADAMW_COMPRESS_STATE_DICT flash_adamw_immediate_cast=$MEGATRON_FLASH_ADAMW_NVFP4_IMMEDIATE_CAST reap_lr_groups=$MEGATRON_REAP_LR_GROUPS backbone_lr_mult=$MEGATRON_REAP_BACKBONE_LR_MULT new_component_lr_mult=$MEGATRON_REAP_NEW_COMPONENT_LR_MULT backbone_update_cap=${MEGATRON_REAP_BACKBONE_UPDATE_CAP_RATIO}/${MEGATRON_REAP_BACKBONE_UPDATE_CAP_STEPS}/floor:${MEGATRON_REAP_BACKBONE_UPDATE_CAP_PARAM_RMS_FLOOR}
  ce_loss=full_logits_vocab_parallel_cross_entropy chunked_lm_head=$MEGATRON_CHUNKED_LM_HEAD_LOSS fused_streambp_lce=$MEGATRON_STREAMBP_FUSED_LCE inactive_lce_vocab_split=${LCE_FWD_VOCAB_SPLIT_SIZE}/${LCE_BWD_VOCAB_SPLIT_SIZE}
  gated_norm=torch_mm_min_tokens=$MEGATRON_GATED_NORM_TORCH_MM_MIN_TOKENS disable_cute=$MEGATRON_GATED_NORM_DISABLE_CUTE freeze_token_embeddings=$MEGATRON_FREEZE_TOKEN_EMBEDDINGS
  nccl_socket_ifname=$NCCL_SOCKET_IFNAME nccl_net=${NCCL_NET:-<default>} use_nccl_gib=$USE_NCCL_GIB local_rank_hca=$MEGATRON_LOCAL_RANK_NCCL_HCA hcas=$MEGATRON_NCCL_LOCAL_RANK_HCAS parent_NCCL_IB_HCA=${NCCL_IB_HCA:-<unset>}
  memlock_soft=$(ulimit -Sl) memlock_hard=$(ulimit -Hl) nccl_max_ctas=${NCCL_MAX_CTAS:-<unset>} nccl_netdevs_policy=${NCCL_NETDEVS_POLICY:-<unset>} nccl_ib_merge_nics=${NCCL_IB_MERGE_NICS:-<unset>}
  wandb_entity=$WANDB_ENTITY wandb_project=$WANDB_PROJECT wandb_run=$WANDB_EXP_NAME wandb_mode=$WANDB_MODE
  hf_upload=$HF_UPLOAD_CHECKPOINTS repo=$HF_REPO_ID interval=$HF_UPLOAD_INTERVAL retain=$HF_UPLOAD_RETAIN retention_rank=$HF_UPLOAD_RETENTION_NODE_RANK
  zcc=$ENABLE_ZCC workers=$ZCC_WORKERS_NUM flash=$ZCC_FLASH_DEVICE durable=$ZCC_DURABLE_DIR durable_interval=$ZCC_DURABLE_INTERVAL retain=$ZCC_RETAIN_LATEST compress=$ZCC_COMPRESS
  load_ckpt=$LOAD_CKPT
  save_ckpt=$SAVE_CKPT save_interval=$SAVE_INTERVAL retain_interval=$SAVE_RETAIN_INTERVAL
  ckpt_fully_parallel_load=$CKPT_FULLY_PARALLEL_LOAD group=$CKPT_FULLY_PARALLEL_LOAD_PROCESS_GROUP algo=$CKPT_FULLY_PARALLEL_LOAD_EXCHANGE_ALGO
  [path_audit] fastpath_strict=$FASTPATH_STRICT fsdp=${USE_MEGATRON_FSDP}:${DATA_PARALLEL_SHARDING_STRATEGY}/meta:${FSDP_INIT_MODEL_WITH_META_DEVICE}/nccl_ub:${FSDP_USE_NCCL_UB}/double_buffer:${FSDP_DOUBLE_BUFFER}/flush_ready:${MEGATRON_FSDP_FLUSH_READY_BUCKETS_ON_RESET} streambp=$USE_STREAMBP activation_offload=$FINE_GRAINED_ACTIVATION_OFFLOADING temp_offload=$MEGATRON_TEMP_ACTIVATION_OFFLOAD pipeline_queue_offload=$MEGATRON_PIPELINE_QUEUE_OFFLOAD/depth:${MEGATRON_PIPELINE_QUEUE_OFFLOAD_DEPTH} recompute=$RECOMPUTE act_eco=$NVFP4_ACTIVATION_ECO jit_fuser_disabled=$MEGATRON_DISABLE_JIT_FUSER gated_norm=${MEGATRON_GATED_NORM_TORCH_MM_MIN_TOKENS}/${MEGATRON_GATED_NORM_DISABLE_CUTE} freeze_embed=$MEGATRON_FREEZE_TOKEN_EMBEDDINGS dsa=triton:${MEGATRON_DSA_TRITON}/split_qk:${MEGATRON_DSA_SPLIT_QK}/require_split_qk:${MEGATRON_DSA_REQUIRE_SPLIT_QK}/reentrant_retain:${MEGATRON_DSA_SPLIT_QK_REENTRANT_RETAIN_GRAPH}/cp_kv_ref:${MEGATRON_DSA_CP_GATHER_SPLIT_KV_REF}/cp_sorted_gather:${MEGATRON_DSA_CP_SORTED_ZIGZAG_GATHER}/topk:${DSA_INDEXER_TOPK}/local_query:${DSA_LOCAL_QUERY_LENGTH}/query_chunk:${DSA_CHUNK_SIZE}/key_block:${MEGATRON_DSA_INDEXER_KEY_BLOCK_SIZE}/kv_bwd_chunk:${MEGATRON_DSA_SPLIT_QK_REENTRANT_KV_BWD_CHUNK}/defer_query:${MEGATRON_DSA_SPLIT_QK_REENTRANT_DEFER_QUERY_GRADS}/row_query_bwd:${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_QUERY_BWD}/row_bwd_warps:${MEGATRON_DSA_CUDA_SPLIT_QK_ROW_BWD_WARPS}/teacher_score_scratch:${MEGATRON_DSA_TEACHER_SCORE_SCRATCH}/bwd_score_scratch:${MEGATRON_DSA_TRITON_BWD_SCORE_SCRATCH} hisa=enabled:${DSA_INDEXCACHE_HISA}/selector:${MEGATRON_HISA_SELECTOR_BACKEND}/parallel_refine:${MEGATRON_HISA_MEGAKERNEL_PARALLEL_REFINE}/streaming_scratch:${MEGATRON_HISA_MEGAKERNEL_STREAMING_SCRATCH}/bmm_tc:${MEGATRON_HISA_BMM_FP32_ACCUM_TENSORCORES}/selector_row_chunk:${MEGATRON_HISA_SELECTOR_ROW_CHUNK}/target:${MEGATRON_HISA_TARGET_TRITON}/target_row_chunk:${MEGATRON_HISA_TARGET_ROW_CHUNK}/selected_bwd_tile:${MEGATRON_HISA_SELECTED_SCORE_BWD_CUBLASDX_TILE_N}/loss:${MEGATRON_HISA_FUSED_INDEXER_LOSS}/dense_fallback:${MEGATRON_HISA_FALLBACK_DENSE_IF_SHORT} quant=higgs:${USE_HIGGS}:${HIGGS_KV_PRESET}/indexcache:${INDEXCACHE}:${DSA_INDEXCACHE_QUANTIZATION}/turboquant:${TURBOQUANT}/flash_adamw_eco:${FLASH_ADAMW_ECO}/fsdp_inject:${FLASH_ADAMW_FSDP_ECO_INJECT} moe=dispatcher:${MOE_TOKEN_DISPATCHER_TYPE}/backend:${MOE_FLEX_DISPATCHER_BACKEND}/compact:${MEGATRON_DEEPEP_COMPACT_BACKEND}/cuda_unpermute:${MEGATRON_DEEPEP_COMPACT_CUDA_UNPERMUTE}/combine_cfg_group:${MEGATRON_DEEPEP_COMBINE_CONFIG_GROUP_SIZE:-default}/combine_cfg_nvl:${MEGATRON_DEEPEP_COMBINE_NVL_SEND_TOKENS:-default}x${MEGATRON_DEEPEP_COMBINE_NVL_RECV_TOKENS:-default}/expert_major_dispatch:${MEGATRON_DEEPEP_EXPERT_MAJOR_DISPATCH}/expert_major_combine:${MEGATRON_DEEPEP_EXPERT_MAJOR_COMBINE}/router:${MOE_ROUTER_LOAD_BALANCING_TYPE}/aux:${MOE_AUX_LOSS_COEFF}/freeze:${MEGATRON_FREEZE_ROUTER}/freeze_bias:${MEGATRON_FREEZE_ROUTER_EXPERT_BIAS}/bias_method:${MOE_ROUTER_EXPERT_BIAS_UPDATE_METHOD}/quantile_application:${MOE_ROUTER_QUANTILE_BIAS_APPLICATION}/padding_for_quantization:${MOE_ROUTER_PADDING_FOR_QUANTIZATION} checkpoint=zcc:${ENABLE_ZCC}/save_interval:${SAVE_INTERVAL}/hf_upload:${HF_UPLOAD_CHECKPOINTS}
EOF

HF_UPLOAD_PID=""
cleanup_hf_upload() {
  if [[ -n "$HF_UPLOAD_PID" ]]; then
    kill "$HF_UPLOAD_PID" 2>/dev/null || true
  fi
}

if [[ "$HF_UPLOAD_CHECKPOINTS" == "1" && "${DISABLE_SAVE:-0}" != "1" && "${DRY_RUN:-0}" != "1" ]]; then
  mkdir -p "$SAVE_CKPT/hf_upload_logs"
  printf -v node_rank_padded "%03d" "$NODE_RANK"
  HF_PRIVATE_ARG=()
  if [[ "$HF_UPLOAD_PRIVATE" == "1" ]]; then
    HF_PRIVATE_ARG=(--private)
  fi
  HF_RETENTION_ARG=()
  if [[ "$NODE_RANK" == "$HF_UPLOAD_RETENTION_NODE_RANK" ]]; then
    HF_RETENTION_ARG=(--retention-owner)
  fi
  echo "Starting HF checkpoint upload sidecar on node_rank=$NODE_RANK -> $HF_REPO_ID" >&2
  uv run --no-sync python tools/upload_mcore_checkpoints_to_hf.py \
    --checkpoint-root "$SAVE_CKPT" \
    --repo-id "$HF_REPO_ID" \
    --folder-prefix "$HF_UPLOAD_FOLDER_PREFIX" \
    --node-name "node${node_rank_padded}-$(hostname -s)" \
    --node-rank "$NODE_RANK" \
    --expected-nodes "$HF_UPLOAD_EXPECTED_NODES" \
    --upload-interval "$HF_UPLOAD_INTERVAL" \
    --retain "$HF_UPLOAD_RETAIN" \
    --stable-seconds "$HF_UPLOAD_STABLE_SECONDS" \
    --poll-seconds "$HF_UPLOAD_POLL_SECONDS" \
    --finalize-timeout-seconds "$HF_UPLOAD_FINALIZE_TIMEOUT_SECONDS" \
    "${HF_PRIVATE_ARG[@]}" \
    "${HF_RETENTION_ARG[@]}" \
    > "$SAVE_CKPT/hf_upload_logs/node${node_rank_padded}.log" 2>&1 &
  HF_UPLOAD_PID="$!"
  trap cleanup_hf_upload EXIT
fi

examples/sft/run_sft_deepseek_nvfp4.sh
